# coding: utf8
from __future__ import unicode_literals
from spacy.symbols import POS, ADJ, ADP, ADV, AUX, CCONJ, DET, INTJ, NOUN, NUM, PART, PRON, PROPN, PUNCT, SCONJ, VERB, X

TAG_MAP = {
    "Agcfpay":{POS:ADJ, "Case":"Acc", "Definite":"Def", "Degree":"Cmp", "Gender":"Fem", "Number":"Plur"},
    "Agcfpgy":{POS:ADJ, "Case":"Gen", "Definite":"Def", "Degree":"Cmp", "Gender":"Fem", "Number":"Plur"},
    "Agcfpiy":{POS:ADJ, "Case":"Ins", "Definite":"Def", "Degree":"Cmp", "Gender":"Fem", "Number":"Plur"},
    "Agcfply":{POS:ADJ, "Case":"Loc", "Definite":"Def", "Degree":"Cmp", "Gender":"Fem", "Number":"Plur"},
    "Agcfpny":{POS:ADJ, "Case":"Nom", "Definite":"Def", "Degree":"Cmp", "Gender":"Fem", "Number":"Plur"},
    "Agcfsay":{POS:ADJ, "Case":"Acc", "Definite":"Def", "Degree":"Cmp", "Gender":"Fem", "Number":"Sing"},
    "Agcfsdy":{POS:ADJ, "Case":"Dat", "Definite":"Def", "Degree":"Cmp", "Gender":"Fem", "Number":"Sing"},
    "Agcfsgy":{POS:ADJ, "Case":"Gen", "Definite":"Def", "Degree":"Cmp", "Gender":"Fem", "Number":"Sing"},
    "Agcfsiy":{POS:ADJ, "Case":"Ins", "Definite":"Def", "Degree":"Cmp", "Gender":"Fem", "Number":"Sing"},
    "Agcfsly":{POS:ADJ, "Case":"Loc", "Definite":"Def", "Degree":"Cmp", "Gender":"Fem", "Number":"Sing"},
    "Agcfsny":{POS:ADJ, "Case":"Nom", "Definite":"Def", "Degree":"Cmp", "Gender":"Fem", "Number":"Sing"},
    "Agcmpay":{POS:ADJ, "Case":"Acc", "Definite":"Def", "Degree":"Cmp", "Gender":"Masc", "Number":"Plur"},
    "Agcmpgy":{POS:ADJ, "Case":"Gen", "Definite":"Def", "Degree":"Cmp", "Gender":"Masc", "Number":"Plur"},
    "Agcmpiy":{POS:ADJ, "Case":"Ins", "Definite":"Def", "Degree":"Cmp", "Gender":"Masc", "Number":"Plur"},
    "Agcmpny":{POS:ADJ, "Case":"Nom", "Definite":"Def", "Degree":"Cmp", "Gender":"Masc", "Number":"Plur"},
    "Agcmsayn":{POS:ADJ, "Animacy":"Inan", "Case":"Acc", "Definite":"Def", "Degree":"Cmp", "Gender":"Masc", "Number":"Sing"},
    "Agcmsdy":{POS:ADJ, "Case":"Dat", "Definite":"Def", "Degree":"Cmp", "Gender":"Masc", "Number":"Sing"},
    "Agcmsgy":{POS:ADJ, "Case":"Gen", "Definite":"Def", "Degree":"Cmp", "Gender":"Masc", "Number":"Sing"},
    "Agcmsiy":{POS:ADJ, "Case":"Ins", "Definite":"Def", "Degree":"Cmp", "Gender":"Masc", "Number":"Sing"},
    "Agcmsly":{POS:ADJ, "Case":"Loc", "Definite":"Def", "Degree":"Cmp", "Gender":"Masc", "Number":"Sing"},
    "Agcmsny":{POS:ADJ, "Case":"Nom", "Definite":"Def", "Degree":"Cmp", "Gender":"Masc", "Number":"Sing"},
    "Agcnply":{POS:ADJ, "Case":"Loc", "Definite":"Def", "Degree":"Cmp", "Gender":"Neut", "Number":"Plur"},
    "Agcnpny":{POS:ADJ, "Case":"Nom", "Definite":"Def", "Degree":"Cmp", "Gender":"Neut", "Number":"Plur"},
    "Agcnsay":{POS:ADJ, "Case":"Acc", "Definite":"Def", "Degree":"Cmp", "Gender":"Neut", "Number":"Sing"},
    "Agcnsdy":{POS:ADJ, "Case":"Dat", "Definite":"Def", "Degree":"Cmp", "Gender":"Neut", "Number":"Sing"},
    "Agcnsgy":{POS:ADJ, "Case":"Gen", "Definite":"Def", "Degree":"Cmp", "Gender":"Neut", "Number":"Sing"},
    "Agcnsiy":{POS:ADJ, "Case":"Ins", "Definite":"Def", "Degree":"Cmp", "Gender":"Neut", "Number":"Sing"},
    "Agcnsly":{POS:ADJ, "Case":"Loc", "Definite":"Def", "Degree":"Cmp", "Gender":"Neut", "Number":"Sing"},
    "Agcnsny":{POS:ADJ, "Case":"Nom", "Definite":"Def", "Degree":"Cmp", "Gender":"Neut", "Number":"Sing"},
    "Agpfpay":{POS:ADJ, "Case":"Acc", "Definite":"Def", "Degree":"Pos", "Gender":"Fem", "Number":"Plur"},
    "Agpfpdy":{POS:ADJ, "Case":"Dat", "Definite":"Def", "Degree":"Pos", "Gender":"Fem", "Number":"Plur"},
    "Agpfpgy":{POS:ADJ, "Case":"Gen", "Definite":"Def", "Degree":"Pos", "Gender":"Fem", "Number":"Plur"},
    "Agpfpiy":{POS:ADJ, "Case":"Ins", "Definite":"Def", "Degree":"Pos", "Gender":"Fem", "Number":"Plur"},
    "Agpfply":{POS:ADJ, "Case":"Loc", "Definite":"Def", "Degree":"Pos", "Gender":"Fem", "Number":"Plur"},
    "Agpfpny":{POS:ADJ, "Case":"Nom", "Definite":"Def", "Degree":"Pos", "Gender":"Fem", "Number":"Plur"},
    "Agpfsay":{POS:ADJ, "Case":"Acc", "Definite":"Def", "Degree":"Pos", "Gender":"Fem", "Number":"Sing"},
    "Agpfsdy":{POS:ADJ, "Case":"Dat", "Definite":"Def", "Degree":"Pos", "Gender":"Fem", "Number":"Sing"},
    "Agpfsgy":{POS:ADJ, "Case":"Gen", "Definite":"Def", "Degree":"Pos", "Gender":"Fem", "Number":"Sing"},
    "Agpfsiy":{POS:ADJ, "Case":"Ins", "Definite":"Def", "Degree":"Pos", "Gender":"Fem", "Number":"Sing"},
    "Agpfsly":{POS:ADJ, "Case":"Loc", "Definite":"Def", "Degree":"Pos", "Gender":"Fem", "Number":"Sing"},
    "Agpfsny":{POS:ADJ, "Case":"Nom", "Definite":"Def", "Degree":"Pos", "Gender":"Fem", "Number":"Sing"},
    "Agpmpay":{POS:ADJ, "Case":"Acc", "Definite":"Def", "Degree":"Pos", "Gender":"Masc", "Number":"Plur"},
    "Agpmpdy":{POS:ADJ, "Case":"Dat", "Definite":"Def", "Degree":"Pos", "Gender":"Masc", "Number":"Plur"},
    "Agpmpgy":{POS:ADJ, "Case":"Gen", "Definite":"Def", "Degree":"Pos", "Gender":"Masc", "Number":"Plur"},
    "Agpmpiy":{POS:ADJ, "Case":"Ins", "Definite":"Def", "Degree":"Pos", "Gender":"Masc", "Number":"Plur"},
    "Agpmply":{POS:ADJ, "Case":"Loc", "Definite":"Def", "Degree":"Pos", "Gender":"Masc", "Number":"Plur"},
    "Agpmpny":{POS:ADJ, "Case":"Nom", "Definite":"Def", "Degree":"Pos", "Gender":"Masc", "Number":"Plur"},
    "Agpmsann":{POS:ADJ, "Animacy":"Inan", "Case":"Acc", "Definite":"Ind", "Degree":"Pos", "Gender":"Masc", "Number":"Sing"},
    "Agpmsany":{POS:ADJ, "Animacy":"Anim", "Case":"Acc", "Definite":"Ind", "Degree":"Pos", "Gender":"Masc", "Number":"Sing"},
    "Agpmsayn":{POS:ADJ, "Animacy":"Inan", "Case":"Acc", "Definite":"Def", "Degree":"Pos", "Gender":"Masc", "Number":"Sing"},
    "Agpmsayy":{POS:ADJ, "Animacy":"Anim", "Case":"Acc", "Definite":"Def", "Degree":"Pos", "Gender":"Masc", "Number":"Sing"},
    "Agpmsdy":{POS:ADJ, "Case":"Dat", "Definite":"Def", "Degree":"Pos", "Gender":"Masc", "Number":"Sing"},
    "Agpmsgn":{POS:ADJ, "Case":"Gen", "Definite":"Ind", "Degree":"Pos", "Gender":"Masc", "Number":"Sing"},
    "Agpmsgy":{POS:ADJ, "Case":"Gen", "Definite":"Def", "Degree":"Pos", "Gender":"Masc", "Number":"Sing"},
    "Agpmsiy":{POS:ADJ, "Case":"Ins", "Definite":"Def", "Degree":"Pos", "Gender":"Masc", "Number":"Sing"},
    "Agpmsly":{POS:ADJ, "Case":"Loc", "Definite":"Def", "Degree":"Pos", "Gender":"Masc", "Number":"Sing"},
    "Agpmsnn":{POS:ADJ, "Case":"Nom", "Definite":"Ind", "Degree":"Pos", "Gender":"Masc", "Number":"Sing"},
    "Agpmsny":{POS:ADJ, "Case":"Nom", "Definite":"Def", "Degree":"Pos", "Gender":"Masc", "Number":"Sing"},
    "Agpnpay":{POS:ADJ, "Case":"Acc", "Definite":"Def", "Degree":"Pos", "Gender":"Neut", "Number":"Plur"},
    "Agpnpdy":{POS:ADJ, "Case":"Dat", "Definite":"Def", "Degree":"Pos", "Gender":"Neut", "Number":"Plur"},
    "Agpnpgy":{POS:ADJ, "Case":"Gen", "Definite":"Def", "Degree":"Pos", "Gender":"Neut", "Number":"Plur"},
    "Agpnpiy":{POS:ADJ, "Case":"Ins", "Definite":"Def", "Degree":"Pos", "Gender":"Neut", "Number":"Plur"},
    "Agpnply":{POS:ADJ, "Case":"Loc", "Definite":"Def", "Degree":"Pos", "Gender":"Neut", "Number":"Plur"},
    "Agpnpny":{POS:ADJ, "Case":"Nom", "Definite":"Def", "Degree":"Pos", "Gender":"Neut", "Number":"Plur"},
    "Agpnsay":{POS:ADJ, "Case":"Acc", "Definite":"Def", "Degree":"Pos", "Gender":"Neut", "Number":"Sing"},
    "Agpnsdy":{POS:ADJ, "Case":"Dat", "Definite":"Def", "Degree":"Pos", "Gender":"Neut", "Number":"Sing"},
    "Agpnsgn":{POS:NUM, "Case":"Gen", "Definite":"Ind", "Degree":"Pos", "Gender":"Neut", "Number":"Sing"},
    "Agpnsgy":{POS:ADJ, "Case":"Gen", "Definite":"Def", "Degree":"Pos", "Gender":"Neut", "Number":"Sing"},
    "Agpnsiy":{POS:ADJ, "Case":"Ins", "Definite":"Def", "Degree":"Pos", "Gender":"Neut", "Number":"Sing"},
    "Agpnsly":{POS:ADJ, "Case":"Loc", "Definite":"Def", "Degree":"Pos", "Gender":"Neut", "Gender[psor]":"Masc,Neut", "Number":"Sing"},
    "Agpnsny":{POS:ADJ, "Case":"Nom", "Definite":"Def", "Degree":"Pos", "Gender":"Neut", "Number":"Sing"},
    "Agsfpay":{POS:ADJ, "Case":"Acc", "Definite":"Def", "Degree":"Sup", "Gender":"Fem", "Number":"Plur"},
    "Agsfpgy":{POS:ADJ, "Case":"Gen", "Definite":"Def", "Degree":"Sup", "Gender":"Fem", "Number":"Plur"},
    "Agsfpiy":{POS:ADJ, "Case":"Ins", "Definite":"Def", "Degree":"Sup", "Gender":"Fem", "Number":"Plur"},
    "Agsfpny":{POS:ADJ, "Case":"Nom", "Definite":"Def", "Degree":"Sup", "Gender":"Fem", "Number":"Plur"},
    "Agsfsay":{POS:ADJ, "Case":"Acc", "Definite":"Def", "Degree":"Sup", "Gender":"Fem", "Number":"Sing"},
    "Agsfsgy":{POS:ADJ, "Case":"Gen", "Definite":"Def", "Degree":"Sup", "Gender":"Fem", "Number":"Sing"},
    "Agsfsiy":{POS:ADJ, "Case":"Ins", "Definite":"Def", "Degree":"Sup", "Gender":"Fem", "Number":"Sing"},
    "Agsfsly":{POS:ADJ, "Case":"Loc", "Definite":"Def", "Degree":"Sup", "Gender":"Fem", "Number":"Sing"},
    "Agsfsny":{POS:ADJ, "Case":"Nom", "Definite":"Def", "Degree":"Sup", "Gender":"Fem", "Number":"Sing"},
    "Agsmpay":{POS:ADJ, "Case":"Acc", "Definite":"Def", "Degree":"Sup", "Gender":"Masc", "Number":"Plur"},
    "Agsmpdy":{POS:ADJ, "Case":"Dat", "Definite":"Def", "Degree":"Sup", "Gender":"Masc", "Number":"Plur"},
    "Agsmpgy":{POS:ADJ, "Case":"Gen", "Definite":"Def", "Degree":"Sup", "Gender":"Masc", "Number":"Plur"},
    "Agsmpiy":{POS:ADJ, "Case":"Ins", "Definite":"Def", "Degree":"Sup", "Gender":"Masc", "Number":"Plur"},
    "Agsmply":{POS:ADJ, "Case":"Loc", "Definite":"Def", "Degree":"Sup", "Gender":"Masc", "Number":"Plur"},
    "Agsmpny":{POS:ADJ, "Case":"Nom", "Definite":"Def", "Degree":"Sup", "Gender":"Masc", "Number":"Plur"},
    "Agsmsayn":{POS:ADJ, "Animacy":"Inan", "Case":"Acc", "Definite":"Def", "Degree":"Sup", "Gender":"Masc", "Number":"Sing"},
    "Agsmsayy":{POS:ADJ, "Animacy":"Anim", "Case":"Acc", "Definite":"Def", "Degree":"Sup", "Gender":"Masc", "Number":"Sing"},
    "Agsmsdy":{POS:ADJ, "Case":"Dat", "Definite":"Def", "Degree":"Sup", "Gender":"Masc", "Number":"Sing"},
    "Agsmsgy":{POS:ADJ, "Case":"Gen", "Definite":"Def", "Degree":"Sup", "Gender":"Masc", "Number":"Sing"},
    "Agsmsiy":{POS:ADJ, "Case":"Ins", "Definite":"Def", "Degree":"Sup", "Gender":"Masc", "Number":"Sing"},
    "Agsmsly":{POS:ADJ, "Case":"Loc", "Definite":"Def", "Degree":"Sup", "Gender":"Masc", "Number":"Sing"},
    "Agsmsny":{POS:ADJ, "Case":"Nom", "Definite":"Def", "Degree":"Sup", "Gender":"Masc", "Number":"Sing"},
    "Agsnpay":{POS:ADJ, "Case":"Acc", "Definite":"Def", "Degree":"Sup", "Gender":"Neut", "Number":"Plur"},
    "Agsnpgy":{POS:ADJ, "Case":"Gen", "Definite":"Def", "Degree":"Sup", "Gender":"Neut", "Number":"Plur"},
    "Agsnpny":{POS:ADJ, "Case":"Nom", "Definite":"Def", "Degree":"Sup", "Gender":"Neut", "Number":"Plur"},
    "Agsnsgy":{POS:ADJ, "Case":"Gen", "Definite":"Def", "Degree":"Sup", "Gender":"Neut", "Number":"Sing"},
    "Agsnsiy":{POS:ADJ, "Case":"Ins", "Definite":"Def", "Degree":"Sup", "Gender":"Neut", "Number":"Sing"},
    "Agsnsny":{POS:ADJ, "Case":"Nom", "Definite":"Def", "Degree":"Sup", "Gender":"Neut", "Number":"Sing"},
    "Appfpay":{POS:ADJ, "Case":"Acc", "Definite":"Def", "Degree":"Pos", "Gender":"Fem", "Number":"Plur", "VerbForm":"Part", "Voice":"Pass"},
    "Appfpdy":{POS:ADJ, "Case":"Dat", "Definite":"Def", "Degree":"Pos", "Gender":"Fem", "Number":"Plur", "VerbForm":"Part", "Voice":"Pass"},
    "Appfpgy":{POS:ADJ, "Case":"Gen", "Definite":"Def", "Degree":"Pos", "Gender":"Fem", "Number":"Plur", "VerbForm":"Part", "Voice":"Pass"},
    "Appfpiy":{POS:ADJ, "Case":"Ins", "Definite":"Def", "Degree":"Pos", "Gender":"Fem", "Number":"Plur", "VerbForm":"Part", "Voice":"Pass"},
    "Appfply":{POS:ADJ, "Case":"Loc", "Definite":"Def", "Degree":"Pos", "Gender":"Fem", "Number":"Plur", "VerbForm":"Part", "Voice":"Pass"},
    "Appfpny":{POS:ADJ, "Case":"Nom", "Definite":"Def", "Degree":"Pos", "Gender":"Fem", "Number":"Plur", "VerbForm":"Part", "Voice":"Pass"},
    "Appfsay":{POS:ADJ, "Case":"Acc", "Definite":"Def", "Degree":"Pos", "Gender":"Fem", "Number":"Sing", "VerbForm":"Part", "Voice":"Pass"},
    "Appfsgy":{POS:ADJ, "Case":"Gen", "Definite":"Def", "Degree":"Pos", "Gender":"Fem", "Number":"Sing", "VerbForm":"Part", "Voice":"Pass"},
    "Appfsiy":{POS:ADJ, "Case":"Ins", "Definite":"Def", "Degree":"Pos", "Gender":"Fem", "Number":"Sing", "VerbForm":"Part", "Voice":"Pass"},
    "Appfsly":{POS:ADJ, "Case":"Loc", "Definite":"Def", "Degree":"Pos", "Gender":"Fem", "Number":"Sing", "VerbForm":"Part", "Voice":"Pass"},
    "Appfsny":{POS:ADJ, "Case":"Nom", "Definite":"Def", "Degree":"Pos", "Gender":"Fem", "Number":"Sing", "VerbForm":"Part", "Voice":"Pass"},
    "Appmpay":{POS:ADJ, "Case":"Acc", "Definite":"Def", "Degree":"Pos", "Gender":"Masc", "Number":"Plur", "VerbForm":"Part", "Voice":"Pass"},
    "Appmpgy":{POS:ADJ, "Case":"Gen", "Definite":"Def", "Degree":"Pos", "Gender":"Masc", "Number":"Plur", "VerbForm":"Part", "Voice":"Pass"},
    "Appmpiy":{POS:ADJ, "Case":"Ins", "Definite":"Def", "Degree":"Pos", "Gender":"Masc", "Number":"Plur", "VerbForm":"Part", "Voice":"Pass"},
    "Appmply":{POS:ADJ, "Case":"Loc", "Definite":"Def", "Degree":"Pos", "Gender":"Masc", "Number":"Plur", "VerbForm":"Part", "Voice":"Pass"},
    "Appmpny":{POS:ADJ, "Case":"Nom", "Definite":"Def", "Degree":"Pos", "Gender":"Masc", "Number":"Plur", "VerbForm":"Part", "Voice":"Pass"},
    "Appmsann":{POS:ADJ, "Animacy":"Inan", "Case":"Acc", "Definite":"Ind", "Degree":"Pos", "Gender":"Masc", "Number":"Sing", "VerbForm":"Part", "Voice":"Pass"},
    "Appmsayn":{POS:ADJ, "Animacy":"Inan", "Case":"Acc", "Definite":"Def", "Degree":"Pos", "Gender":"Masc", "Number":"Sing", "VerbForm":"Part", "Voice":"Pass"},
    "Appmsayy":{POS:ADJ, "Animacy":"Anim", "Case":"Acc", "Definite":"Def", "Degree":"Pos", "Gender":"Masc", "Number":"Sing", "VerbForm":"Part", "Voice":"Pass"},
    "Appmsdy":{POS:ADJ, "Case":"Dat", "Definite":"Def", "Degree":"Pos", "Gender":"Masc", "Number":"Sing", "VerbForm":"Part", "Voice":"Pass"},
    "Appmsgy":{POS:ADJ, "Case":"Gen", "Definite":"Def", "Degree":"Pos", "Gender":"Masc", "Number":"Sing", "VerbForm":"Part", "Voice":"Pass"},
    "Appmsiy":{POS:ADJ, "Case":"Ins", "Definite":"Def", "Degree":"Pos", "Gender":"Masc", "Number":"Sing", "VerbForm":"Part", "Voice":"Pass"},
    "Appmsly":{POS:ADJ, "Case":"Loc", "Definite":"Def", "Degree":"Pos", "Gender":"Masc", "Number":"Sing", "VerbForm":"Part", "Voice":"Pass"},
    "Appmsnn":{POS:ADJ, "Case":"Nom", "Definite":"Ind", "Degree":"Pos", "Gender":"Masc", "Number":"Sing", "VerbForm":"Part", "Voice":"Pass"},
    "Appmsny":{POS:ADJ, "Case":"Nom", "Definite":"Def", "Degree":"Pos", "Gender":"Masc", "Number":"Sing", "VerbForm":"Part", "Voice":"Pass"},
    "Appnpay":{POS:ADJ, "Case":"Acc", "Definite":"Def", "Degree":"Pos", "Gender":"Neut", "Number":"Plur", "VerbForm":"Part", "Voice":"Pass"},
    "Appnpgy":{POS:ADJ, "Case":"Gen", "Definite":"Def", "Degree":"Pos", "Gender":"Neut", "Number":"Plur", "VerbForm":"Part", "Voice":"Pass"},
    "Appnpiy":{POS:ADJ, "Case":"Ins", "Definite":"Def", "Degree":"Pos", "Gender":"Neut", "Number":"Plur", "VerbForm":"Part", "Voice":"Pass"},
    "Appnpny":{POS:ADJ, "Case":"Nom", "Definite":"Def", "Degree":"Pos", "Gender":"Neut", "Number":"Plur", "VerbForm":"Part", "Voice":"Pass"},
    "Appnsay":{POS:ADJ, "Case":"Acc", "Definite":"Def", "Degree":"Pos", "Gender":"Neut", "Number":"Sing", "VerbForm":"Part", "Voice":"Pass"},
    "Appnsgy":{POS:ADJ, "Case":"Gen", "Definite":"Def", "Degree":"Pos", "Gender":"Neut", "Number":"Sing", "VerbForm":"Part", "Voice":"Pass"},
    "Appnsiy":{POS:ADJ, "Case":"Ins", "Definite":"Def", "Degree":"Pos", "Gender":"Neut", "Number":"Sing", "VerbForm":"Part", "Voice":"Pass"},
    "Appnsly":{POS:ADJ, "Case":"Loc", "Definite":"Def", "Degree":"Pos", "Gender":"Neut", "Number":"Sing", "VerbForm":"Part", "Voice":"Pass"},
    "Appnsny":{POS:ADJ, "Case":"Nom", "Definite":"Def", "Degree":"Pos", "Gender":"Neut", "Number":"Sing", "VerbForm":"Part", "Voice":"Pass"},
    "Aspfpay":{POS:ADJ, "Case":"Acc", "Definite":"Def", "Degree":"Pos", "Gender":"Fem", "Number":"Plur", "Poss":"Yes"},
    "Aspfpgy":{POS:ADJ, "Case":"Gen", "Definite":"Def", "Degree":"Pos", "Gender":"Fem", "Number":"Plur", "Poss":"Yes"},
    "Aspfply":{POS:ADJ, "Case":"Loc", "Definite":"Def", "Degree":"Pos", "Gender":"Fem", "Number":"Plur", "Poss":"Yes"},
    "Aspfpny":{POS:ADJ, "Case":"Nom", "Definite":"Def", "Degree":"Pos", "Gender":"Fem", "Number":"Plur", "Poss":"Yes"},
    "Aspfsay":{POS:ADJ, "Case":"Acc", "Definite":"Def", "Degree":"Pos", "Gender":"Fem", "Number":"Sing", "Poss":"Yes"},
    "Aspfsdy":{POS:ADJ, "Case":"Dat", "Definite":"Def", "Degree":"Pos", "Gender":"Fem", "Number":"Sing", "Poss":"Yes"},
    "Aspfsgy":{POS:ADJ, "Case":"Gen", "Definite":"Def", "Degree":"Pos", "Gender":"Fem", "Number":"Sing", "Poss":"Yes"},
    "Aspfsiy":{POS:ADJ, "Case":"Ins", "Definite":"Def", "Degree":"Pos", "Gender":"Fem", "Number":"Sing", "Poss":"Yes"},
    "Aspfsly":{POS:ADJ, "Case":"Loc", "Definite":"Def", "Degree":"Pos", "Gender":"Fem", "Number":"Sing", "Poss":"Yes"},
    "Aspfsny":{POS:ADJ, "Case":"Nom", "Definite":"Def", "Degree":"Pos", "Gender":"Fem", "Number":"Sing", "Poss":"Yes"},
    "Aspmpay":{POS:ADJ, "Case":"Acc", "Definite":"Def", "Degree":"Pos", "Gender":"Masc", "Number":"Plur", "Poss":"Yes"},
    "Aspmpgy":{POS:ADJ, "Case":"Gen", "Definite":"Def", "Degree":"Pos", "Gender":"Masc", "Number":"Plur", "Poss":"Yes"},
    "Aspmpny":{POS:ADJ, "Case":"Nom", "Definite":"Def", "Degree":"Pos", "Gender":"Masc", "Number":"Plur", "Poss":"Yes"},
    "Aspmsann":{POS:ADJ, "Animacy":"Inan", "Case":"Acc", "Definite":"Ind", "Degree":"Pos", "Gender":"Masc", "Number":"Sing", "Poss":"Yes"},
    "Aspmsayy":{POS:ADJ, "Animacy":"Anim", "Case":"Acc", "Definite":"Def", "Degree":"Pos", "Gender":"Masc", "Number":"Sing", "Poss":"Yes"},
    "Aspmsdy":{POS:ADJ, "Case":"Dat", "Definite":"Def", "Degree":"Pos", "Gender":"Masc", "Number":"Sing", "Poss":"Yes"},
    "Aspmsgy":{POS:ADJ, "Case":"Gen", "Definite":"Def", "Degree":"Pos", "Gender":"Masc", "Number":"Sing", "Poss":"Yes"},
    "Aspmsiy":{POS:ADJ, "Case":"Ins", "Definite":"Def", "Degree":"Pos", "Gender":"Masc", "Number":"Sing", "Poss":"Yes"},
    "Aspmsly":{POS:ADJ, "Case":"Loc", "Definite":"Def", "Degree":"Pos", "Gender":"Masc", "Number":"Sing", "Poss":"Yes"},
    "Aspmsnn":{POS:ADJ, "Case":"Nom", "Definite":"Ind", "Degree":"Pos", "Gender":"Masc", "Number":"Sing", "Poss":"Yes"},
    "Aspnpay":{POS:ADJ, "Case":"Acc", "Definite":"Def", "Degree":"Pos", "Gender":"Neut", "Number":"Plur", "Poss":"Yes"},
    "Aspnsay":{POS:ADJ, "Case":"Acc", "Definite":"Def", "Degree":"Pos", "Gender":"Neut", "Number":"Sing", "Poss":"Yes"},
    "Aspnsgy":{POS:ADJ, "Case":"Gen", "Definite":"Def", "Degree":"Pos", "Gender":"Neut", "Number":"Sing", "Poss":"Yes"},
    "Aspnsly":{POS:ADJ, "Case":"Loc", "Definite":"Def", "Degree":"Pos", "Gender":"Neut", "Number":"Sing", "Poss":"Yes"},
    "Aspnsny":{POS:ADJ, "Case":"Nom", "Definite":"Def", "Degree":"Pos", "Gender":"Neut", "Number":"Sing", "Poss":"Yes"},
    "Cc":{POS:CCONJ},
    "Cs":{POS:SCONJ},
    "I":{POS:INTJ},
    "Mdc":{POS:NUM, "NumType":"Card"},
    "Mdm":{POS:NUM, "NumType":"Mult"},
    "Mdo":{POS:ADV, "Degree":"Pos"},
    "Mds":{POS:NUM, "NumType":"Mult"},
    "Mlc":{POS:NUM, "NumType":"Card"},
    "Mlc--a":{POS:NUM, "Case":"Acc", "Number":"Plur", "NumType":"Card"},
    "Mlc--i":{POS:NUM, "Case":"Ins", "Number":"Plur", "NumType":"Card"},
    "Mlcf-a":{POS:NUM, "Case":"Acc", "Gender":"Fem", "Number":"Plur", "NumType":"Card"},
    "Mlcf-g":{POS:NUM, "Case":"Gen", "Gender":"Fem", "Number":"Plur", "NumType":"Card"},
    "Mlcf-n":{POS:NUM, "Case":"Nom", "Gender":"Fem", "Number":"Plur", "NumType":"Card"},
    "Mlcfpa":{POS:NUM, "Case":"Acc", "Gender":"Fem", "Number":"Plur", "NumType":"Card"},
    "Mlcfpg":{POS:NUM, "Case":"Gen", "Gender":"Fem", "Number":"Plur", "NumType":"Card"},
    "Mlcfsa":{POS:NUM, "Case":"Acc", "Gender":"Fem", "Number":"Sing", "NumType":"Card"},
    "Mlcfsd":{POS:NUM, "Case":"Dat", "Gender":"Fem", "Number":"Sing", "NumType":"Card"},
    "Mlcfsg":{POS:NUM, "Case":"Gen", "Gender":"Fem", "Number":"Sing", "NumType":"Card"},
    "Mlcfsi":{POS:NUM, "Case":"Ins", "Gender":"Fem", "Number":"Sing", "NumType":"Card"},
    "Mlcfsl":{POS:NUM, "Case":"Loc", "Gender":"Fem", "Number":"Sing", "NumType":"Card"},
    "Mlcfsn":{POS:NUM, "Case":"Nom", "Gender":"Fem", "Number":"Sing", "NumType":"Card"},
    "Mlcm-a":{POS:NUM, "Case":"Acc", "Gender":"Masc", "Number":"Plur", "NumType":"Card"},
    "Mlcm-n":{POS:NUM, "Case":"Nom", "Gender":"Masc", "Number":"Plur", "NumType":"Card"},
    "Mlcmpn":{POS:NUM, "Case":"Nom", "Gender":"Masc", "Number":"Plur", "NumType":"Card"},
    "Mlcmsan":{POS:NUM, "Animacy":"Inan", "Case":"Acc", "Gender":"Masc", "Number":"Sing", "NumType":"Card"},
    "Mlcmsay":{POS:NUM, "Animacy":"Anim", "Case":"Acc", "Gender":"Masc", "Number":"Sing", "NumType":"Card"},
    "Mlcmsd":{POS:NUM, "Case":"Dat", "Gender":"Masc", "Number":"Sing", "NumType":"Card"},
    "Mlcmsg":{POS:NUM, "Case":"Gen", "Gender":"Masc", "Number":"Sing", "NumType":"Card"},
    "Mlcmsi":{POS:NUM, "Case":"Ins", "Gender":"Masc", "Number":"Sing", "NumType":"Card"},
    "Mlcmsl":{POS:NUM, "Case":"Loc", "Gender":"Masc", "Number":"Sing", "NumType":"Card"},
    "Mlcmsn":{POS:NUM, "Case":"Nom", "Gender":"Masc", "Number":"Sing", "NumType":"Card"},
    "Mlcn-n":{POS:NUM, "Case":"Nom", "Gender":"Neut", "Number":"Plur", "NumType":"Card"},
    "Mlcnsa":{POS:NUM, "Case":"Acc", "Gender":"Neut", "Number":"Sing", "NumType":"Card"},
    "Mlcnsl":{POS:NUM, "Case":"Loc", "Gender":"Neut", "Number":"Sing", "NumType":"Card"},
    "Mlcnsn":{POS:NUM, "Case":"Nom", "Gender":"Neut", "Number":"Sing", "NumType":"Card"},
    "Mlofpa":{POS:ADJ, "Case":"Acc", "Degree":"Pos", "Gender":"Fem", "Number":"Plur"},
    "Mlofpd":{POS:NUM, "Case":"Dat", "Degree":"Pos", "Gender":"Fem", "Number":"Plur"},
    "Mlofpg":{POS:NUM, "Case":"Gen", "Degree":"Pos", "Gender":"Fem", "Number":"Plur"},
    "Mlofpi":{POS:NUM, "Case":"Ins", "Degree":"Pos", "Gender":"Fem", "Number":"Plur"},
    "Mlofpl":{POS:NUM, "Case":"Loc", "Degree":"Pos", "Gender":"Fem", "Number":"Plur"},
    "Mlofpn":{POS:ADJ, "Case":"Nom", "Degree":"Pos", "Gender":"Fem", "Number":"Plur"},
    "Mlofsa":{POS:NUM, "Case":"Acc", "Degree":"Pos", "Gender":"Fem", "Number":"Sing"},
    "Mlofsd":{POS:ADJ, "Case":"Dat", "Degree":"Pos", "Gender":"Fem", "Number":"Sing"},
    "Mlofsg":{POS:ADJ, "Case":"Gen", "Degree":"Pos", "Gender":"Fem", "Number":"Sing"},
    "Mlofsi":{POS:NUM, "Case":"Ins", "Degree":"Pos", "Gender":"Fem", "Number":"Sing"},
    "Mlofsl":{POS:NUM, "Case":"Loc", "Degree":"Pos", "Gender":"Fem", "Number":"Sing"},
    "Mlofsn":{POS:ADJ, "Case":"Nom", "Degree":"Pos", "Gender":"Fem", "Number":"Sing"},
    "Mlompa":{POS:ADJ, "Case":"Acc", "Degree":"Pos", "Gender":"Masc", "Number":"Plur"},
    "Mlompd":{POS:ADJ, "Case":"Dat", "Degree":"Pos", "Gender":"Masc", "Number":"Plur"},
    "Mlompg":{POS:ADJ, "Case":"Gen", "Degree":"Pos", "Gender":"Masc", "Number":"Plur"},
    "Mlompi":{POS:NUM, "Case":"Ins", "Degree":"Pos", "Gender":"Masc", "Number":"Plur"},
    "Mlompl":{POS:ADJ, "Case":"Loc", "Degree":"Pos", "Gender":"Masc", "Number":"Plur"},
    "Mlompn":{POS:ADJ, "Case":"Nom", "Degree":"Pos", "Gender":"Masc", "Number":"Plur"},
    "Mlomsan":{POS:NUM, "Animacy":"Inan", "Case":"Acc", "Degree":"Pos", "Gender":"Masc", "Number":"Sing"},
    "Mlomsay":{POS:NUM, "Animacy":"Anim", "Case":"Acc", "Degree":"Pos", "Gender":"Masc", "Number":"Sing"},
    "Mlomsd":{POS:ADJ, "Case":"Dat", "Degree":"Pos", "Gender":"Masc", "Number":"Sing"},
    "Mlomsg":{POS:NUM, "Case":"Gen", "Degree":"Pos", "Gender":"Masc", "Number":"Sing"},
    "Mlomsi":{POS:NUM, "Case":"Ins", "Degree":"Pos", "Gender":"Masc", "Number":"Sing"},
    "Mlomsl":{POS:NUM, "Case":"Loc", "Degree":"Pos", "Gender":"Masc", "Number":"Sing"},
    "Mlomsn":{POS:ADJ, "Case":"Nom", "Degree":"Pos", "Gender":"Masc", "Number":"Sing"},
    "Mlonpa":{POS:ADJ, "Case":"Acc", "Degree":"Pos", "Gender":"Neut", "Number":"Plur"},
    "Mlonpg":{POS:ADJ, "Case":"Gen", "Degree":"Pos", "Gender":"Neut", "Number":"Plur"},
    "Mlonpl":{POS:ADJ, "Case":"Loc", "Degree":"Pos", "Gender":"Neut", "Number":"Plur"},
    "Mlonsa":{POS:ADJ, "Case":"Acc", "Degree":"Pos", "Gender":"Neut", "Number":"Sing"},
    "Mlonsg":{POS:NUM, "Case":"Gen", "Degree":"Pos", "Gender":"Neut", "Number":"Sing"},
    "Mlonsi":{POS:NUM, "Case":"Ins", "Degree":"Pos", "Gender":"Neut", "Number":"Sing"},
    "Mlonsl":{POS:NUM, "Case":"Loc", "Degree":"Pos", "Gender":"Neut", "Number":"Sing"},
    "Mlonsn":{POS:NUM, "Case":"Nom", "Degree":"Pos", "Gender":"Neut", "Number":"Sing"},
    "Mls":{POS:NUM, "NumType":"Mult"},
    "Mlsf-a":{POS:NUM, "Case":"Acc", "Gender":"Fem", "NumType":"Mult"},
    "Mlsf-g":{POS:NUM, "Case":"Gen", "Gender":"Fem", "NumType":"Mult"},
    "Mlsf-i":{POS:NUM, "Case":"Ins", "Gender":"Fem", "NumType":"Mult"},
    "Mlsf-l":{POS:NUM, "Case":"Loc", "Gender":"Fem", "NumType":"Mult"},
    "Mlsf-n":{POS:NUM, "Case":"Nom", "Gender":"Fem", "NumType":"Mult"},
    "Mlsm-a":{POS:NUM, "Case":"Acc", "Gender":"Masc", "NumType":"Mult"},
    "Mlsm-g":{POS:NUM, "Case":"Gen", "Gender":"Masc", "NumType":"Mult"},
    "Mlsm-n":{POS:NUM, "Case":"Nom", "Gender":"Masc", "NumType":"Mult"},
    "Mrc":{POS:NUM, "NumType":"Card"},
    "Mro":{POS:ADJ, "NumType":"Ord"},
    "Ncfpa":{POS:NOUN, "Case":"Acc", "Gender":"Fem", "Number":"Plur"},
    "Ncfpd":{POS:NOUN, "Case":"Dat", "Gender":"Fem", "Number":"Plur"},
    "Ncfpg":{POS:NOUN, "Case":"Gen", "Gender":"Fem", "Number":"Plur"},
    "Ncfpi":{POS:NOUN, "Case":"Ins", "Gender":"Fem", "Number":"Plur"},
    "Ncfpl":{POS:NOUN, "Case":"Loc", "Gender":"Fem", "Number":"Plur"},
    "Ncfpn":{POS:NOUN, "Case":"Nom", "Gender":"Fem", "Number":"Plur"},
    "Ncfsa":{POS:NOUN, "Case":"Acc", "Gender":"Fem", "Number":"Sing"},
    "Ncfsd":{POS:NOUN, "Case":"Dat", "Gender":"Fem", "Number":"Sing"},
    "Ncfsg":{POS:NOUN, "Case":"Gen", "Gender":"Fem", "Number":"Sing"},
    "Ncfsi":{POS:NOUN, "Case":"Ins", "Gender":"Fem", "Number":"Sing"},
    "Ncfsl":{POS:NOUN, "Case":"Loc", "Gender":"Fem", "Number":"Sing"},
    "Ncfsn":{POS:NOUN, "Case":"Nom", "Gender":"Fem", "Number":"Sing"},
    "Ncmpa":{POS:NOUN, "Case":"Acc", "Gender":"Masc", "Number":"Plur"},
    "Ncmpd":{POS:NOUN, "Case":"Dat", "Gender":"Masc", "Number":"Plur"},
    "Ncmpg":{POS:NOUN, "Case":"Gen", "Gender":"Masc", "Number":"Plur"},
    "Ncmpi":{POS:NOUN, "Case":"Ins", "Gender":"Masc", "Number":"Plur"},
    "Ncmpl":{POS:NOUN, "Case":"Loc", "Gender":"Masc", "Number":"Plur"},
    "Ncmpn":{POS:NOUN, "Case":"Nom", "Gender":"Masc", "Number":"Plur"},
    "Ncmsan":{POS:NOUN, "Animacy":"Inan", "Case":"Acc", "Gender":"Masc", "Number":"Sing"},
    "Ncmsay":{POS:NOUN, "Animacy":"Anim", "Case":"Acc", "Gender":"Masc", "Number":"Sing"},
    "Ncmsd":{POS:NOUN, "Case":"Dat", "Gender":"Masc", "Number":"Sing"},
    "Ncmsg":{POS:NOUN, "Case":"Gen", "Gender":"Masc", "Number":"Sing"},
    "Ncmsi":{POS:NOUN, "Case":"Ins", "Gender":"Masc", "Number":"Sing"},
    "Ncmsl":{POS:NOUN, "Case":"Loc", "Gender":"Masc", "Number":"Sing"},
    "Ncmsn":{POS:NOUN, "Case":"Nom", "Gender":"Masc", "Number":"Sing"},
    "Ncmsv":{POS:NOUN, "Case":"Voc", "Gender":"Masc", "Number":"Sing"},
    "Ncnpa":{POS:NOUN, "Case":"Acc", "Gender":"Neut", "Number":"Plur"},
    "Ncnpd":{POS:NOUN, "Case":"Dat", "Gender":"Neut", "Number":"Plur"},
    "Ncnpg":{POS:NOUN, "Case":"Gen", "Gender":"Neut", "Number":"Plur"},
    "Ncnpi":{POS:NOUN, "Case":"Ins", "Gender":"Neut", "Number":"Plur"},
    "Ncnpl":{POS:NOUN, "Case":"Loc", "Gender":"Neut", "Number":"Plur"},
    "Ncnpn":{POS:NOUN, "Case":"Nom", "Gender":"Neut", "Number":"Plur"},
    "Ncnsa":{POS:NOUN, "Case":"Acc", "Gender":"Neut", "Number":"Sing"},
    "Ncnsd":{POS:NOUN, "Case":"Dat", "Gender":"Neut", "Number":"Sing"},
    "Ncnsg":{POS:NOUN, "Case":"Gen", "Gender":"Neut", "Number":"Sing"},
    "Ncnsi":{POS:NOUN, "Case":"Ins", "Gender":"Neut", "Number":"Sing"},
    "Ncnsl":{POS:NOUN, "Case":"Loc", "Gender":"Neut", "Number":"Sing"},
    "Ncnsn":{POS:NOUN, "Case":"Nom", "Gender":"Neut", "Number":"Sing"},
    "Npfpd":{POS:PROPN, "Case":"Dat", "Gender":"Fem", "Number":"Plur"},
    "Npfpg":{POS:PROPN, "Case":"Gen", "Gender":"Fem", "Number":"Plur"},
    "Npfpn":{POS:PROPN, "Case":"Nom", "Gender":"Fem", "Number":"Plur"},
    "Npfsa":{POS:PROPN, "Case":"Acc", "Gender":"Fem", "Number":"Sing"},
    "Npfsd":{POS:PROPN, "Case":"Dat", "Gender":"Fem", "Number":"Sing"},
    "Npfsg":{POS:PROPN, "Case":"Gen", "Gender":"Fem", "Number":"Sing"},
    "Npfsi":{POS:PROPN, "Case":"Ins", "Gender":"Fem", "Number":"Sing"},
    "Npfsl":{POS:PROPN, "Case":"Loc", "Gender":"Fem", "Number":"Sing"},
    "Npfsn":{POS:PROPN, "Case":"Nom", "Gender":"Fem", "Number":"Sing"},
    "Npmpa":{POS:PROPN, "Case":"Acc", "Gender":"Masc", "Number":"Plur"},
    "Npmpd":{POS:PROPN, "Case":"Dat", "Gender":"Masc", "Number":"Plur"},
    "Npmpg":{POS:PROPN, "Case":"Gen", "Gender":"Masc", "Number":"Plur"},
    "Npmpi":{POS:PROPN, "Case":"Ins", "Gender":"Masc", "Number":"Plur"},
    "Npmpn":{POS:PROPN, "Case":"Nom", "Gender":"Masc", "Number":"Plur"},
    "Npmsan":{POS:PROPN, "Animacy":"Inan", "Case":"Acc", "Gender":"Masc", "Number":"Sing"},
    "Npmsay":{POS:PROPN, "Animacy":"Anim", "Case":"Acc", "Gender":"Masc", "Number":"Sing"},
    "Npmsd":{POS:PROPN, "Case":"Dat", "Gender":"Masc", "Number":"Sing"},
    "Npmsg":{POS:PROPN, "Case":"Gen", "Gender":"Masc", "Number":"Sing"},
    "Npmsi":{POS:PROPN, "Case":"Ins", "Gender":"Masc", "Number":"Sing"},
    "Npmsl":{POS:PROPN, "Case":"Loc", "Gender":"Masc", "Number":"Sing"},
    "Npmsn":{POS:PROPN, "Case":"Nom", "Gender":"Masc", "Number":"Sing"},
    "Npnpn":{POS:PROPN, "Case":"Nom", "Gender":"Neut", "Number":"Plur"},
    "Npnsa":{POS:PROPN, "Case":"Acc", "Gender":"Neut", "Number":"Sing"},
    "Npnsd":{POS:PROPN, "Case":"Dat", "Gender":"Neut", "Number":"Sing"},
    "Npnsg":{POS:PROPN, "Case":"Gen", "Gender":"Neut", "Number":"Sing"},
    "Npnsi":{POS:PROPN, "Case":"Ins", "Gender":"Neut", "Number":"Sing"},
    "Npnsl":{POS:PROPN, "Case":"Loc", "Gender":"Neut", "Number":"Sing"},
    "Npnsn":{POS:PROPN, "Case":"Nom", "Gender":"Neut", "Number":"Sing"},
    "Pd-fpa":{POS:DET, "Case":"Acc", "Gender":"Fem", "Number":"Plur", "PronType":"Dem"},
    "Pd-fpd":{POS:DET, "Case":"Dat", "Gender":"Fem", "Number":"Plur", "PronType":"Dem"},
    "Pd-fpg":{POS:DET, "Case":"Gen", "Gender":"Fem", "Number":"Plur", "PronType":"Dem"},
    "Pd-fpi":{POS:DET, "Case":"Ins", "Gender":"Fem", "Number":"Plur", "PronType":"Dem"},
    "Pd-fpl":{POS:DET, "Case":"Loc", "Gender":"Fem", "Number":"Plur", "PronType":"Dem"},
    "Pd-fpn":{POS:DET, "Case":"Nom", "Gender":"Fem", "Number":"Plur", "PronType":"Dem"},
    "Pd-fsa":{POS:DET, "Case":"Acc", "Gender":"Fem", "Number":"Sing", "PronType":"Dem"},
    "Pd-fsd":{POS:DET, "Case":"Dat", "Gender":"Fem", "Number":"Sing", "PronType":"Dem"},
    "Pd-fsg":{POS:DET, "Case":"Gen", "Gender":"Fem", "Number":"Sing", "PronType":"Dem"},
    "Pd-fsi":{POS:DET, "Case":"Ins", "Gender":"Fem", "Number":"Sing", "PronType":"Dem"},
    "Pd-fsl":{POS:DET, "Case":"Loc", "Gender":"Fem", "Number":"Sing", "PronType":"Dem"},
    "Pd-fsn":{POS:DET, "Case":"Nom", "Gender":"Fem", "Number":"Sing", "PronType":"Dem"},
    "Pd-mpa":{POS:DET, "Case":"Acc", "Gender":"Masc", "Number":"Plur", "PronType":"Dem"},
    "Pd-mpd":{POS:DET, "Case":"Dat", "Gender":"Masc", "Number":"Plur", "PronType":"Dem"},
    "Pd-mpg":{POS:DET, "Case":"Gen", "Gender":"Masc", "Number":"Plur", "PronType":"Dem"},
    "Pd-mpl":{POS:DET, "Case":"Loc", "Gender":"Masc", "Number":"Plur", "PronType":"Dem"},
    "Pd-mpn":{POS:DET, "Case":"Nom", "Gender":"Masc", "Number":"Plur", "PronType":"Dem"},
    "Pd-msan":{POS:DET, "Animacy":"Inan", "Case":"Acc", "Gender":"Masc", "Number":"Sing", "PronType":"Dem"},
    "Pd-msay":{POS:DET, "Animacy":"Anim", "Case":"Acc", "Gender":"Masc", "Number":"Sing", "PronType":"Dem"},
    "Pd-msd":{POS:DET, "Case":"Dat", "Gender":"Masc", "Number":"Sing", "PronType":"Dem"},
    "Pd-msg":{POS:DET, "Case":"Gen", "Gender":"Masc", "Number":"Sing", "PronType":"Dem"},
    "Pd-msi":{POS:DET, "Case":"Ins", "Gender":"Masc", "Number":"Sing", "PronType":"Dem"},
    "Pd-msl":{POS:DET, "Case":"Loc", "Gender":"Masc", "Number":"Sing", "PronType":"Dem"},
    "Pd-msn":{POS:DET, "Case":"Nom", "Gender":"Masc", "Number":"Sing", "PronType":"Dem"},
    "Pd-npa":{POS:DET, "Case":"Acc", "Gender":"Neut", "Number":"Plur", "PronType":"Dem"},
    "Pd-npd":{POS:DET, "Case":"Dat", "Gender":"Neut", "Number":"Plur", "PronType":"Dem"},
    "Pd-npg":{POS:DET, "Case":"Gen", "Gender":"Neut", "Number":"Plur", "PronType":"Dem"},
    "Pd-npl":{POS:DET, "Case":"Loc", "Gender":"Neut", "Number":"Plur", "PronType":"Dem"},
    "Pd-npn":{POS:DET, "Case":"Nom", "Gender":"Neut", "Number":"Plur", "PronType":"Dem"},
    "Pd-nsa":{POS:DET, "Case":"Acc", "Gender":"Neut", "Number":"Sing", "PronType":"Dem"},
    "Pd-nsd":{POS:DET, "Case":"Dat", "Gender":"Neut", "Number":"Sing", "PronType":"Dem"},
    "Pd-nsg":{POS:DET, "Case":"Gen", "Gender":"Neut", "Number":"Sing", "PronType":"Dem"},
    "Pd-nsi":{POS:DET, "Case":"Ins", "Gender":"Neut", "Number":"Sing", "PronType":"Dem"},
    "Pd-nsl":{POS:DET, "Case":"Loc", "Gender":"Neut", "Number":"Sing", "PronType":"Dem"},
    "Pd-nsn":{POS:DET, "Case":"Nom", "Gender":"Neut", "Number":"Sing", "PronType":"Dem"},
    "Pi--sn":{POS:PRON, "Case":"Nom", "Number":"Sing", "PronType":"Ind"},
    "Pi-fpa":{POS:DET, "Case":"Acc", "Gender":"Fem", "Number":"Plur", "PronType":"Ind"},
    "Pi-fpd":{POS:DET, "Case":"Dat", "Gender":"Fem", "Number":"Plur", "PronType":"Int,Rel"},
    "Pi-fpg":{POS:DET, "Case":"Gen", "Gender":"Fem", "Number":"Plur", "PronType":"Int,Rel"},
    "Pi-fpi":{POS:DET, "Case":"Ins", "Gender":"Fem", "Number":"Plur", "PronType":"Ind"},
    "Pi-fpl":{POS:DET, "Case":"Loc", "Gender":"Fem", "Number":"Plur", "PronType":"Ind"},
    "Pi-fpn":{POS:DET, "Case":"Nom", "Gender":"Fem", "Number":"Plur", "PronType":"Ind"},
    "Pi-fsa":{POS:DET, "Case":"Acc", "Gender":"Fem", "Number":"Sing", "Poss":"Yes", "PronType":"Int,Rel"},
    "Pi-fsd":{POS:DET, "Case":"Dat", "Gender":"Fem", "Number":"Sing", "PronType":"Int,Rel"},
    "Pi-fsg":{POS:DET, "Case":"Gen", "Gender":"Fem", "Number":"Sing", "Poss":"Yes", "PronType":"Int,Rel"},
    "Pi-fsi":{POS:DET, "Case":"Ins", "Gender":"Fem", "Number":"Sing", "Poss":"Yes", "PronType":"Ind"},
    "Pi-fsl":{POS:DET, "Case":"Loc", "Gender":"Fem", "Number":"Sing", "PronType":"Ind"},
    "Pi-fsn":{POS:DET, "Case":"Nom", "Gender":"Fem", "Number":"Sing", "Poss":"Yes", "PronType":"Int,Rel"},
    "Pi-mpa":{POS:DET, "Case":"Acc", "Gender":"Masc", "Number":"Plur", "PronType":"Ind"},
    "Pi-mpd":{POS:DET, "Case":"Dat", "Gender":"Masc", "Number":"Plur", "PronType":"Ind"},
    "Pi-mpg":{POS:DET, "Case":"Gen", "Gender":"Masc", "Number":"Plur", "PronType":"Ind"},
    "Pi-mpi":{POS:DET, "Case":"Ins", "Gender":"Masc", "Number":"Plur", "PronType":"Ind"},
    "Pi-mpl":{POS:DET, "Case":"Loc", "Gender":"Masc", "Number":"Plur", "PronType":"Ind"},
    "Pi-mpn":{POS:DET, "Case":"Nom", "Gender":"Masc", "Number":"Plur", "Poss":"Yes", "PronType":"Int,Rel"},
    "Pi-msan":{POS:DET, "Animacy":"Inan", "Case":"Acc", "Gender":"Masc", "Number":"Sing", "Poss":"Yes", "PronType":"Int,Rel"},
    "Pi-msay":{POS:DET, "Animacy":"Anim", "Case":"Acc", "Gender":"Masc", "Number":"Sing", "PronType":"Ind"},
    "Pi-msd":{POS:DET, "Case":"Dat", "Gender":"Masc", "Number":"Sing", "PronType":"Ind"},
    "Pi-msg":{POS:DET, "Case":"Gen", "Gender":"Masc", "Number":"Sing", "Poss":"Yes", "PronType":"Ind"},
    "Pi-msi":{POS:DET, "Case":"Ins", "Gender":"Masc", "Number":"Sing", "PronType":"Int,Rel"},
    "Pi-msl":{POS:DET, "Case":"Loc", "Gender":"Masc", "Number":"Sing", "Poss":"Yes", "PronType":"Tot"},
    "Pi-msn":{POS:DET, "Case":"Nom", "Gender":"Masc", "Number":"Sing", "Poss":"Yes", "PronType":"Int,Rel"},
    "Pi-npa":{POS:DET, "Case":"Acc", "Gender":"Neut", "Number":"Plur", "PronType":"Ind"},
    "Pi-npd":{POS:DET, "Case":"Dat", "Gender":"Neut", "Number":"Plur", "PronType":"Tot"},
    "Pi-npg":{POS:DET, "Case":"Gen", "Gender":"Neut", "Number":"Plur", "PronType":"Ind"},
    "Pi-npi":{POS:DET, "Case":"Ins", "Gender":"Neut", "Number":"Plur", "PronType":"Int,Rel"},
    "Pi-npl":{POS:DET, "Case":"Loc", "Gender":"Neut", "Number":"Plur", "PronType":"Int,Rel"},
    "Pi-npn":{POS:DET, "Case":"Nom", "Gender":"Neut", "Number":"Plur", "PronType":"Ind"},
    "Pi-nsa":{POS:DET, "Case":"Acc", "Gender":"Neut", "Number":"Sing", "PronType":"Ind"},
    "Pi-nsg":{POS:DET, "Case":"Gen", "Gender":"Neut", "Number":"Sing", "Poss":"Yes", "PronType":"Ind"},
    "Pi-nsi":{POS:DET, "Case":"Ins", "Gender":"Neut", "Number":"Sing", "PronType":"Ind"},
    "Pi-nsl":{POS:DET, "Case":"Loc", "Gender":"Neut", "Number":"Sing", "Poss":"Yes", "PronType":"Int,Rel"},
    "Pi-nsn":{POS:DET, "Case":"Nom", "Gender":"Neut", "Number":"Sing", "Poss":"Yes", "PronType":"Ind"},
    "Pi3m-a":{POS:DET, "Case":"Acc", "Gender":"Masc", "PronType":"Ind"},
    "Pi3m-d":{POS:PRON, "Case":"Dat", "Gender":"Masc", "PronType":"Int,Rel"},
    "Pi3m-g":{POS:PRON, "Case":"Gen", "Gender":"Masc", "PronType":"Ind"},
    "Pi3m-l":{POS:PRON, "Case":"Loc", "Gender":"Masc", "PronType":"Int,Rel"},
    "Pi3m-n":{POS:DET, "Case":"Nom", "Gender":"Masc", "PronType":"Ind"},
    "Pi3n-a":{POS:PRON, "Case":"Acc", "Gender":"Neut", "PronType":"Ind"},
    "Pi3n-g":{POS:PRON, "Case":"Gen", "Gender":"Neut", "PronType":"Int,Rel"},
    "Pi3n-i":{POS:PRON, "Case":"Ins", "Gender":"Neut", "PronType":"Int,Rel"},
    "Pi3n-l":{POS:PRON, "Case":"Loc", "Gender":"Neut", "PronType":"Ind"},
    "Pi3n-n":{POS:PRON, "Case":"Nom", "Gender":"Neut", "PronType":"Ind"},
    "Pp1-pa":{POS:PRON, "Case":"Acc", "Number":"Plur", "Person":"1", "PronType":"Prs"},
    "Pp1-pd":{POS:PRON, "Case":"Dat", "Number":"Plur", "Person":"1", "PronType":"Prs"},
    "Pp1-pg":{POS:PRON, "Case":"Gen", "Number":"Plur", "Person":"1", "PronType":"Prs"},
    "Pp1-pi":{POS:PRON, "Case":"Ins", "Number":"Plur", "Person":"1", "PronType":"Prs"},
    "Pp1-pl":{POS:PRON, "Case":"Loc", "Number":"Plur", "Person":"1", "PronType":"Prs"},
    "Pp1-pn":{POS:PRON, "Case":"Nom", "Number":"Plur", "Person":"1", "PronType":"Prs"},
    "Pp1-sa":{POS:PRON, "Case":"Acc", "Number":"Sing", "Person":"1", "PronType":"Prs"},
    "Pp1-sd":{POS:PRON, "Case":"Dat", "Number":"Sing", "Person":"1", "PronType":"Prs"},
    "Pp1-sn":{POS:PRON, "Case":"Nom", "Number":"Sing", "Person":"1", "PronType":"Prs"},
    "Pp2-pa":{POS:PRON, "Case":"Acc", "Number":"Plur", "Person":"2", "PronType":"Prs"},
    "Pp2-pd":{POS:PRON, "Case":"Dat", "Number":"Plur", "Person":"2", "PronType":"Prs"},
    "Pp2-pl":{POS:PRON, "Case":"Loc", "Number":"Plur", "Person":"2", "PronType":"Prs"},
    "Pp2-pn":{POS:PRON, "Case":"Nom", "Number":"Plur", "Person":"2", "PronType":"Prs"},
    "Pp3-pa":{POS:PRON, "Case":"Acc", "Number":"Plur", "Person":"3", "PronType":"Prs"},
    "Pp3-pd":{POS:PRON, "Case":"Dat", "Number":"Plur", "Person":"3", "PronType":"Prs"},
    "Pp3-pg":{POS:PRON, "Case":"Gen", "Number":"Plur", "Person":"3", "PronType":"Prs"},
    "Pp3-pi":{POS:PRON, "Case":"Ins", "Number":"Plur", "Person":"3", "PronType":"Prs"},
    "Pp3-pl":{POS:PRON, "Case":"Loc", "Number":"Plur", "Person":"3", "PronType":"Prs"},
    "Pp3fpn":{POS:PRON, "Case":"Nom", "Gender":"Fem", "Number":"Plur", "Person":"3", "PronType":"Prs"},
    "Pp3fsa":{POS:PRON, "Case":"Acc", "Gender":"Fem", "Number":"Sing", "Person":"3", "PronType":"Prs"},
    "Pp3fsd":{POS:PRON, "Case":"Dat", "Gender":"Fem", "Number":"Sing", "Person":"3", "PronType":"Prs"},
    "Pp3fsg":{POS:PRON, "Case":"Gen", "Gender":"Fem", "Number":"Sing", "Person":"3", "PronType":"Prs"},
    "Pp3fsi":{POS:PRON, "Case":"Ins", "Gender":"Fem", "Number":"Sing", "Person":"3", "PronType":"Prs"},
    "Pp3fsl":{POS:PRON, "Case":"Loc", "Gender":"Fem", "Number":"Sing", "Person":"3", "PronType":"Prs"},
    "Pp3fsn":{POS:PRON, "Case":"Nom", "Gender":"Fem", "Number":"Sing", "Person":"3", "PronType":"Prs"},
    "Pp3mpn":{POS:PRON, "Case":"Nom", "Gender":"Masc", "Number":"Plur", "Person":"3", "PronType":"Prs"},
    "Pp3msa":{POS:PRON, "Case":"Acc", "Gender":"Masc", "Number":"Sing", "Person":"3", "PronType":"Prs"},
    "Pp3msd":{POS:PRON, "Case":"Dat", "Gender":"Masc", "Number":"Sing", "Person":"3", "PronType":"Prs"},
    "Pp3msg":{POS:PRON, "Case":"Gen", "Gender":"Masc", "Number":"Sing", "Person":"3", "PronType":"Prs"},
    "Pp3msi":{POS:PRON, "Case":"Ins", "Gender":"Masc", "Number":"Sing", "Person":"3", "PronType":"Prs"},
    "Pp3msl":{POS:PRON, "Case":"Loc", "Gender":"Masc", "Number":"Sing", "Person":"3", "PronType":"Prs"},
    "Pp3msn":{POS:PRON, "Case":"Nom", "Gender":"Masc", "Number":"Sing", "Person":"3", "PronType":"Prs"},
    "Pp3npn":{POS:PRON, "Case":"Nom", "Gender":"Neut", "Number":"Plur", "Person":"3", "PronType":"Prs"},
    "Pp3nsa":{POS:PRON, "Case":"Acc", "Gender":"Neut", "Number":"Sing", "Person":"3", "PronType":"Prs"},
    "Pp3nsn":{POS:PRON, "Case":"Nom", "Gender":"Neut", "Number":"Sing", "Person":"3", "PronType":"Prs"},
    "Pq-fpa":{POS:DET, "Case":"Acc", "Gender":"Fem", "Number":"Plur", "PronType":"Int,Rel"},
    "Pq-fsl":{POS:DET, "Case":"Loc", "Gender":"Fem", "Number":"Sing", "PronType":"Int,Rel"},
    "Pq-fsn":{POS:DET, "Case":"Nom", "Gender":"Fem", "Number":"Sing", "PronType":"Int,Rel"},
    "Pq-mpn":{POS:DET, "Case":"Nom", "Gender":"Masc", "Number":"Plur", "PronType":"Int,Rel"},
    "Pq-msn":{POS:DET, "Case":"Nom", "Gender":"Masc", "Number":"Sing", "PronType":"Int,Rel"},
    "Pq-nsn":{POS:DET, "Case":"Nom", "Gender":"Neut", "Number":"Sing", "PronType":"Int,Rel"},
    "Pq3n-n":{POS:PRON, "Case":"Nom", "Gender":"Neut", "PronType":"Int,Rel"},
    "Ps1fpa":{POS:DET, "Case":"Acc", "Gender":"Fem", "Number":"Plur", "Number[psor]":"Plur", "Person":"1", "Poss":"Yes", "PronType":"Prs"},
    "Ps1fpd":{POS:DET, "Case":"Dat", "Gender":"Fem", "Number":"Plur", "Number[psor]":"Plur", "Person":"1", "Poss":"Yes", "PronType":"Prs"},
    "Ps1fpg":{POS:DET, "Case":"Gen", "Gender":"Fem", "Number":"Plur", "Number[psor]":"Plur", "Person":"1", "Poss":"Yes", "PronType":"Prs"},
    "Ps1fpn":{POS:DET, "Case":"Nom", "Gender":"Fem", "Number":"Plur", "Number[psor]":"Plur", "Person":"1", "Poss":"Yes", "PronType":"Prs"},
    "Ps1fsa":{POS:DET, "Case":"Acc", "Gender":"Fem", "Number":"Sing", "Number[psor]":"Plur", "Person":"1", "Poss":"Yes", "PronType":"Prs"},
    "Ps1fsd":{POS:DET, "Case":"Dat", "Gender":"Fem", "Number":"Sing", "Number[psor]":"Plur", "Person":"1", "Poss":"Yes", "PronType":"Prs"},
    "Ps1fsg":{POS:DET, "Case":"Gen", "Gender":"Fem", "Number":"Sing", "Number[psor]":"Plur", "Person":"1", "Poss":"Yes", "PronType":"Prs"},
    "Ps1fsl":{POS:DET, "Case":"Loc", "Gender":"Fem", "Number":"Sing", "Number[psor]":"Plur", "Person":"1", "Poss":"Yes", "PronType":"Prs"},
    "Ps1fsn":{POS:DET, "Case":"Nom", "Gender":"Fem", "Number":"Sing", "Number[psor]":"Plur", "Person":"1", "Poss":"Yes", "PronType":"Prs"},
    "Ps1mpa":{POS:DET, "Case":"Acc", "Gender":"Masc", "Number":"Plur", "Number[psor]":"Plur", "Person":"1", "Poss":"Yes", "PronType":"Prs"},
    "Ps1mpd":{POS:DET, "Case":"Dat", "Gender":"Masc", "Number":"Plur", "Number[psor]":"Plur", "Person":"1", "Poss":"Yes", "PronType":"Prs"},
    "Ps1mpg":{POS:DET, "Case":"Gen", "Gender":"Masc", "Number":"Plur", "Number[psor]":"Plur", "Person":"1", "Poss":"Yes", "PronType":"Prs"},
    "Ps1mpl":{POS:DET, "Case":"Loc", "Gender":"Masc", "Number":"Plur", "Number[psor]":"Plur", "Person":"1", "Poss":"Yes", "PronType":"Prs"},
    "Ps1mpn":{POS:DET, "Case":"Nom", "Gender":"Masc", "Number":"Plur", "Number[psor]":"Plur", "Person":"1", "Poss":"Yes", "PronType":"Prs"},
    "Ps1msan":{POS:DET, "Animacy":"Inan", "Case":"Acc", "Gender":"Masc", "Number":"Sing", "Number[psor]":"Plur", "Person":"1", "Poss":"Yes", "PronType":"Prs"},
    "Ps1msd":{POS:DET, "Case":"Dat", "Gender":"Masc", "Number":"Sing", "Number[psor]":"Plur", "Person":"1", "Poss":"Yes", "PronType":"Prs"},
    "Ps1msg":{POS:DET, "Case":"Gen", "Gender":"Masc", "Number":"Sing", "Number[psor]":"Plur", "Person":"1", "Poss":"Yes", "PronType":"Prs"},
    "Ps1msl":{POS:DET, "Case":"Loc", "Gender":"Masc", "Number":"Sing", "Number[psor]":"Plur", "Person":"1", "Poss":"Yes", "PronType":"Prs"},
    "Ps1msn":{POS:DET, "Case":"Nom", "Gender":"Masc", "Number":"Sing", "Number[psor]":"Plur", "Person":"1", "Poss":"Yes", "PronType":"Prs"},
    "Ps1nsa":{POS:DET, "Case":"Acc", "Gender":"Neut", "Number":"Sing", "Number[psor]":"Plur", "Person":"1", "Poss":"Yes", "PronType":"Prs"},
    "Ps1nsg":{POS:DET, "Case":"Gen", "Gender":"Neut", "Number":"Sing", "Number[psor]":"Plur", "Person":"1", "Poss":"Yes", "PronType":"Prs"},
    "Ps1nsl":{POS:DET, "Case":"Loc", "Gender":"Neut", "Number":"Sing", "Number[psor]":"Plur", "Person":"1", "Poss":"Yes", "PronType":"Prs"},
    "Ps1nsn":{POS:DET, "Case":"Nom", "Gender":"Neut", "Number":"Sing", "Number[psor]":"Plur", "Person":"1", "Poss":"Yes", "PronType":"Prs"},
    "Ps2fpl":{POS:DET, "Case":"Loc", "Gender":"Fem", "Number":"Plur", "Number[psor]":"Sing", "Person":"2", "Poss":"Yes", "PronType":"Prs"},
    "Ps2fpn":{POS:DET, "Case":"Nom", "Gender":"Fem", "Number":"Plur", "Number[psor]":"Plur", "Person":"2", "Poss":"Yes", "PronType":"Prs"},
    "Ps2fsg":{POS:DET, "Case":"Gen", "Gender":"Fem", "Number":"Sing", "Number[psor]":"Plur", "Person":"2", "Poss":"Yes", "PronType":"Prs"},
    "Ps2fsn":{POS:DET, "Case":"Nom", "Gender":"Fem", "Number":"Sing", "Number[psor]":"Plur", "Person":"2", "Poss":"Yes", "PronType":"Prs"},
    "Ps2msan":{POS:DET, "Animacy":"Inan", "Case":"Acc", "Gender":"Masc", "Number":"Sing", "Number[psor]":"Plur", "Person":"2", "Poss":"Yes", "PronType":"Prs"},
    "Ps2nsl":{POS:DET, "Case":"Loc", "Gender":"Neut", "Number":"Sing", "Number[psor]":"Plur", "Person":"2", "Poss":"Yes", "PronType":"Prs"},
    "Ps2nsn":{POS:DET, "Case":"Nom", "Gender":"Neut", "Number":"Sing", "Number[psor]":"Plur", "Person":"2", "Poss":"Yes", "PronType":"Prs"},
    "Ps3fpa":{POS:DET, "Case":"Acc", "Gender":"Fem", "Number":"Plur", "Number[psor]":"Plur", "Person":"3", "Poss":"Yes", "PronType":"Prs"},
    "Ps3fpg":{POS:DET, "Case":"Gen", "Gender":"Fem", "Gender[psor]":"Fem", "Number":"Plur", "Number[psor]":"Sing", "Person":"3", "Poss":"Yes", "PronType":"Prs"},
    "Ps3fpl":{POS:DET, "Case":"Loc", "Gender":"Fem", "Gender[psor]":"Fem", "Number":"Plur", "Number[psor]":"Sing", "Person":"3", "Poss":"Yes", "PronType":"Prs"},
    "Ps3fpn":{POS:DET, "Case":"Nom", "Gender":"Fem", "Gender[psor]":"Fem", "Number":"Plur", "Number[psor]":"Sing", "Person":"3", "Poss":"Yes", "PronType":"Prs"},
    "Ps3fsa":{POS:DET, "Case":"Acc", "Gender":"Fem", "Gender[psor]":"Fem", "Number":"Sing", "Number[psor]":"Sing", "Person":"3", "Poss":"Yes", "PronType":"Prs"},
    "Ps3fsd":{POS:DET, "Case":"Dat", "Gender":"Fem", "Gender[psor]":"Masc,Neut", "Number":"Sing", "Number[psor]":"Sing", "Person":"3", "Poss":"Yes", "PronType":"Prs"},
    "Ps3fsg":{POS:DET, "Case":"Gen", "Gender":"Fem", "Gender[psor]":"Fem", "Number":"Sing", "Number[psor]":"Sing", "Person":"3", "Poss":"Yes", "PronType":"Prs"},
    "Ps3fsi":{POS:DET, "Case":"Ins", "Gender":"Fem", "Gender[psor]":"Fem", "Number":"Sing", "Number[psor]":"Sing", "Person":"3", "Poss":"Yes", "PronType":"Prs"},
    "Ps3fsl":{POS:DET, "Case":"Loc", "Gender":"Fem", "Gender[psor]":"Fem", "Number":"Sing", "Number[psor]":"Sing", "Person":"3", "Poss":"Yes", "PronType":"Prs"},
    "Ps3fsn":{POS:DET, "Case":"Nom", "Gender":"Fem", "Gender[psor]":"Fem", "Number":"Sing", "Number[psor]":"Sing", "Person":"3", "Poss":"Yes", "PronType":"Prs"},
    "Ps3mpa":{POS:DET, "Case":"Acc", "Gender":"Masc", "Gender[psor]":"Fem", "Number":"Plur", "Number[psor]":"Sing", "Person":"3", "Poss":"Yes", "PronType":"Prs"},
    "Ps3mpd":{POS:DET, "Case":"Dat", "Gender":"Masc", "Gender[psor]":"Fem", "Number":"Plur", "Number[psor]":"Sing", "Person":"3", "Poss":"Yes", "PronType":"Prs"},
    "Ps3mpg":{POS:DET, "Case":"Gen", "Gender":"Masc", "Gender[psor]":"Masc,Neut", "Number":"Plur", "Number[psor]":"Sing", "Person":"3", "Poss":"Yes", "PronType":"Prs"},
    "Ps3mpl":{POS:DET, "Case":"Loc", "Gender":"Masc", "Number":"Plur", "Number[psor]":"Plur", "Person":"3", "Poss":"Yes", "PronType":"Prs"},
    "Ps3mpn":{POS:DET, "Case":"Nom", "Gender":"Masc", "Gender[psor]":"Fem", "Number":"Plur", "Number[psor]":"Sing", "Person":"3", "Poss":"Yes", "PronType":"Prs"},
    "Ps3msan":{POS:DET, "Animacy":"Inan", "Case":"Acc", "Gender":"Masc", "Gender[psor]":"Fem", "Number":"Sing", "Number[psor]":"Sing", "Person":"3", "Poss":"Yes", "PronType":"Prs"},
    "Ps3msay":{POS:DET, "Animacy":"Anim", "Case":"Acc", "Gender":"Masc", "Gender[psor]":"Masc,Neut", "Number":"Sing", "Number[psor]":"Sing", "Person":"3", "Poss":"Yes", "PronType":"Prs"},
    "Ps3msd":{POS:DET, "Case":"Dat", "Gender":"Masc", "Gender[psor]":"Fem", "Number":"Sing", "Number[psor]":"Sing", "Person":"3", "Poss":"Yes", "PronType":"Prs"},
    "Ps3msg":{POS:DET, "Case":"Gen", "Gender":"Masc", "Gender[psor]":"Fem", "Number":"Sing", "Number[psor]":"Sing", "Person":"3", "Poss":"Yes", "PronType":"Prs"},
    "Ps3msi":{POS:DET, "Case":"Ins", "Gender":"Masc", "Gender[psor]":"Masc,Neut", "Number":"Sing", "Number[psor]":"Sing", "Person":"3", "Poss":"Yes", "PronType":"Prs"},
    "Ps3msl":{POS:DET, "Case":"Loc", "Gender":"Masc", "Gender[psor]":"Masc,Neut", "Number":"Sing", "Number[psor]":"Sing", "Person":"3", "Poss":"Yes", "PronType":"Prs"},
    "Ps3msn":{POS:DET, "Case":"Nom", "Gender":"Masc", "Gender[psor]":"Fem", "Number":"Sing", "Number[psor]":"Sing", "Person":"3", "Poss":"Yes", "PronType":"Prs"},
    "Ps3npa":{POS:DET, "Case":"Acc", "Gender":"Neut", "Gender[psor]":"Fem", "Number":"Plur", "Number[psor]":"Sing", "Person":"3", "Poss":"Yes", "PronType":"Prs"},
    "Ps3npg":{POS:DET, "Case":"Gen", "Gender":"Neut", "Gender[psor]":"Masc,Neut", "Number":"Plur", "Number[psor]":"Sing", "Person":"3", "Poss":"Yes", "PronType":"Prs"},
    "Ps3npl":{POS:DET, "Case":"Loc", "Gender":"Neut", "Gender[psor]":"Masc,Neut", "Number":"Plur", "Number[psor]":"Sing", "Person":"3", "Poss":"Yes", "PronType":"Prs"},
    "Ps3nsa":{POS:DET, "Case":"Acc", "Gender":"Neut", "Gender[psor]":"Fem", "Number":"Sing", "Number[psor]":"Sing", "Person":"3", "Poss":"Yes", "PronType":"Prs"},
    "Ps3nsg":{POS:DET, "Case":"Gen", "Gender":"Neut", "Gender[psor]":"Fem", "Number":"Sing", "Number[psor]":"Sing", "Person":"3", "Poss":"Yes", "PronType":"Prs"},
    "Ps3nsl":{POS:DET, "Case":"Loc", "Gender":"Neut", "Gender[psor]":"Fem", "Number":"Sing", "Number[psor]":"Sing", "Person":"3", "Poss":"Yes", "PronType":"Prs"},
    "Ps3nsn":{POS:DET, "Case":"Nom", "Gender":"Neut", "Gender[psor]":"Fem", "Number":"Sing", "Number[psor]":"Sing", "Person":"3", "Poss":"Yes", "PronType":"Prs"},
    "Px--sa":{POS:PRON, "Case":"Acc", "PronType":"Prs", "Reflex":"Yes"},
    "Px--sd":{POS:PRON, "Case":"Dat", "PronType":"Prs", "Reflex":"Yes"},
    "Px--sg":{POS:PRON, "Case":"Gen", "PronType":"Prs", "Reflex":"Yes"},
    "Px--si":{POS:PRON, "Case":"Ins", "PronType":"Prs", "Reflex":"Yes"},
    "Px--sl":{POS:PRON, "Case":"Loc", "PronType":"Prs", "Reflex":"Yes"},
    "Px-fpa":{POS:DET, "Case":"Acc", "Gender":"Fem", "Number":"Plur", "Poss":"Yes", "PronType":"Prs", "Reflex":"Yes"},
    "Px-fpg":{POS:DET, "Case":"Gen", "Gender":"Fem", "Number":"Plur", "Poss":"Yes", "PronType":"Prs", "Reflex":"Yes"},
    "Px-fpi":{POS:DET, "Case":"Ins", "Gender":"Fem", "Number":"Plur", "Poss":"Yes", "PronType":"Prs", "Reflex":"Yes"},
    "Px-fpl":{POS:DET, "Case":"Loc", "Gender":"Fem", "Number":"Plur", "Poss":"Yes", "PronType":"Prs", "Reflex":"Yes"},
    "Px-fsa":{POS:DET, "Case":"Acc", "Gender":"Fem", "Number":"Sing", "Poss":"Yes", "PronType":"Prs", "Reflex":"Yes"},
    "Px-fsd":{POS:DET, "Case":"Dat", "Gender":"Fem", "Number":"Sing", "Poss":"Yes", "PronType":"Prs", "Reflex":"Yes"},
    "Px-fsg":{POS:DET, "Case":"Gen", "Gender":"Fem", "Number":"Sing", "Poss":"Yes", "PronType":"Prs", "Reflex":"Yes"},
    "Px-fsi":{POS:DET, "Case":"Ins", "Gender":"Fem", "Number":"Sing", "Poss":"Yes", "PronType":"Prs", "Reflex":"Yes"},
    "Px-fsl":{POS:DET, "Case":"Loc", "Gender":"Fem", "Number":"Sing", "Poss":"Yes", "PronType":"Prs", "Reflex":"Yes"},
    "Px-mpa":{POS:DET, "Case":"Acc", "Gender":"Masc", "Number":"Plur", "Poss":"Yes", "PronType":"Prs", "Reflex":"Yes"},
    "Px-mpd":{POS:DET, "Case":"Dat", "Gender":"Masc", "Number":"Plur", "Poss":"Yes", "PronType":"Prs", "Reflex":"Yes"},
    "Px-mpg":{POS:DET, "Case":"Gen", "Gender":"Masc", "Number":"Plur", "Poss":"Yes", "PronType":"Prs", "Reflex":"Yes"},
    "Px-mpi":{POS:DET, "Case":"Ins", "Gender":"Masc", "Number":"Plur", "Poss":"Yes", "PronType":"Prs", "Reflex":"Yes"},
    "Px-mpl":{POS:DET, "Case":"Loc", "Gender":"Masc", "Number":"Plur", "Poss":"Yes", "PronType":"Prs", "Reflex":"Yes"},
    "Px-msan":{POS:DET, "Animacy":"Inan", "Case":"Acc", "Gender":"Masc", "Number":"Sing", "Poss":"Yes", "PronType":"Prs", "Reflex":"Yes"},
    "Px-msay":{POS:DET, "Animacy":"Anim", "Case":"Acc", "Gender":"Masc", "Number":"Sing", "Poss":"Yes", "PronType":"Prs", "Reflex":"Yes"},
    "Px-msd":{POS:DET, "Case":"Dat", "Gender":"Masc", "Number":"Sing", "Poss":"Yes", "PronType":"Prs", "Reflex":"Yes"},
    "Px-msg":{POS:DET, "Case":"Gen", "Gender":"Masc", "Number":"Sing", "Poss":"Yes", "PronType":"Prs", "Reflex":"Yes"},
    "Px-msi":{POS:DET, "Case":"Ins", "Gender":"Masc", "Number":"Sing", "Poss":"Yes", "PronType":"Prs", "Reflex":"Yes"},
    "Px-msl":{POS:DET, "Case":"Loc", "Gender":"Masc", "Number":"Sing", "Poss":"Yes", "PronType":"Prs", "Reflex":"Yes"},
    "Px-npa":{POS:DET, "Case":"Acc", "Gender":"Neut", "Number":"Plur", "Poss":"Yes", "PronType":"Prs", "Reflex":"Yes"},
    "Px-npg":{POS:DET, "Case":"Gen", "Gender":"Neut", "Number":"Plur", "Poss":"Yes", "PronType":"Prs", "Reflex":"Yes"},
    "Px-npl":{POS:DET, "Case":"Loc", "Gender":"Neut", "Number":"Plur", "Poss":"Yes", "PronType":"Prs", "Reflex":"Yes"},
    "Px-nsa":{POS:DET, "Case":"Acc", "Gender":"Neut", "Number":"Sing", "Poss":"Yes", "PronType":"Prs", "Reflex":"Yes"},
    "Px-nsg":{POS:DET, "Case":"Gen", "Gender":"Neut", "Number":"Sing", "Poss":"Yes", "PronType":"Prs", "Reflex":"Yes"},
    "Qo":{POS:PART},
    "Qq":{POS:PART},
    "Qz":{POS:PART, "Polarity":"Neg"},
    "Rgc":{POS:ADV, "Degree":"Cmp"},
    "Rgp":{POS:ADV, "Degree":"Pos"},
    "Rgs":{POS:ADV, "Degree":"Sup"},
    "Rr":{POS:ADV, "Tense":"Past", "VerbForm":"Conv"},
    "Sa":{POS:ADP, "Case":"Acc"},
    "Sd":{POS:ADP, "Case":"Dat"},
    "Sg":{POS:ADP, "Case":"Gen"},
    "Si":{POS:ADP, "Case":"Ins"},
    "Sl":{POS:ADP, "Case":"Loc"},
    "Vaa1p":{POS:AUX, "Mood":"Cnd", "Number":"Plur", "Person":"1", "Tense":"Past", "VerbForm":"Fin"},
    "Vaa1s":{POS:AUX, "Mood":"Cnd", "Number":"Sing", "Person":"1", "Tense":"Past", "VerbForm":"Fin"},
    "Vaa3p":{POS:AUX, "Mood":"Cnd", "Number":"Plur", "Person":"3", "Tense":"Past", "VerbForm":"Fin"},
    "Vaa3s":{POS:AUX, "Mood":"Cnd", "Number":"Sing", "Person":"3", "Tense":"Past", "VerbForm":"Fin"},
    "Vaf3p":{POS:AUX, "Mood":"Ind", "Number":"Plur", "Person":"3", "Tense":"Fut", "VerbForm":"Fin"},
    "Vaf3s":{POS:AUX, "Mood":"Ind", "Number":"Sing", "Person":"3", "Tense":"Fut", "VerbForm":"Fin"},
    "Van":{POS:AUX, "VerbForm":"Inf"},
    "Vap-pf":{POS:AUX, "Gender":"Fem", "Number":"Plur", "Tense":"Past", "VerbForm":"Part", "Voice":"Act"},
    "Vap-pm":{POS:AUX, "Gender":"Masc", "Number":"Plur", "Tense":"Past", "VerbForm":"Part", "Voice":"Act"},
    "Vap-pn":{POS:AUX, "Gender":"Neut", "Number":"Plur", "Tense":"Past", "VerbForm":"Part", "Voice":"Act"},
    "Vap-sf":{POS:AUX, "Gender":"Fem", "Number":"Sing", "Tense":"Past", "VerbForm":"Part", "Voice":"Act"},
    "Vap-sm":{POS:AUX, "Gender":"Masc", "Number":"Sing", "Tense":"Past", "VerbForm":"Part", "Voice":"Act"},
    "Vap-sn":{POS:AUX, "Gender":"Neut", "Number":"Sing", "Tense":"Past", "VerbForm":"Part", "Voice":"Act"},
    "Var1p":{POS:AUX, "Mood":"Ind", "Number":"Plur", "Person":"1", "Polarity":"Neg", "Tense":"Pres", "VerbForm":"Fin"},
    "Var1s":{POS:AUX, "Mood":"Ind", "Number":"Sing", "Person":"1", "Polarity":"Neg", "Tense":"Pres", "VerbForm":"Fin"},
    "Var2p":{POS:AUX, "Mood":"Ind", "Number":"Plur", "Person":"2", "Tense":"Pres", "VerbForm":"Fin"},
    "Var3p":{POS:AUX, "Mood":"Ind", "Number":"Plur", "Person":"3", "Polarity":"Neg", "Tense":"Pres", "VerbForm":"Fin"},
    "Var3s":{POS:AUX, "Mood":"Ind", "Number":"Sing", "Person":"3", "Polarity":"Neg", "Tense":"Pres", "VerbForm":"Fin"},
    "Vma3s":{POS:VERB, "Mood":"Ind", "Number":"Sing", "Person":"3", "Tense":"Past", "VerbForm":"Fin"},
    "Vmf1p":{POS:VERB, "Mood":"Ind", "Number":"Plur", "Person":"1", "Tense":"Fut", "VerbForm":"Fin"},
    "Vmf1s":{POS:VERB, "Mood":"Ind", "Number":"Sing", "Person":"1", "Tense":"Fut", "VerbForm":"Fin"},
    "Vmf2p":{POS:VERB, "Mood":"Ind", "Number":"Plur", "Person":"2", "Tense":"Fut", "VerbForm":"Fin"},
    "Vmf3p":{POS:VERB, "Mood":"Ind", "Number":"Plur", "Person":"3", "Tense":"Fut", "VerbForm":"Fin"},
    "Vmf3s":{POS:VERB, "Mood":"Ind", "Number":"Sing", "Person":"3", "Tense":"Fut", "VerbForm":"Fin"},
    "Vmm1p":{POS:VERB, "Mood":"Imp", "Number":"Plur", "Person":"1", "VerbForm":"Fin"},
    "Vmm2p":{POS:VERB, "Mood":"Imp", "Number":"Plur", "Person":"2", "VerbForm":"Fin"},
    "Vmm2s":{POS:VERB, "Mood":"Imp", "Number":"Sing", "Person":"2", "VerbForm":"Fin"},
    "Vmn":{POS:VERB, "VerbForm":"Inf"},
    "Vmp-pf":{POS:VERB, "Gender":"Fem", "Number":"Plur", "Tense":"Past", "VerbForm":"Part", "Voice":"Act"},
    "Vmp-pm":{POS:VERB, "Gender":"Masc", "Number":"Plur", "Tense":"Past", "VerbForm":"Part", "Voice":"Act"},
    "Vmp-pn":{POS:VERB, "Gender":"Neut", "Number":"Plur", "Tense":"Past", "VerbForm":"Part", "Voice":"Act"},
    "Vmp-sf":{POS:VERB, "Gender":"Fem", "Number":"Sing", "Tense":"Past", "VerbForm":"Part", "Voice":"Act"},
    "Vmp-sm":{POS:VERB, "Gender":"Masc", "Number":"Sing", "Tense":"Past", "VerbForm":"Part", "Voice":"Act"},
    "Vmp-sn":{POS:VERB, "Gender":"Neut", "Number":"Sing", "Tense":"Past", "VerbForm":"Part", "Voice":"Act"},
    "Vmr1p":{POS:VERB, "Mood":"Ind", "Number":"Plur", "Person":"1", "Tense":"Pres", "VerbForm":"Fin"},
    "Vmr1s":{POS:VERB, "Mood":"Ind", "Number":"Sing", "Person":"1", "Tense":"Pres", "VerbForm":"Fin"},
    "Vmr2p":{POS:VERB, "Mood":"Ind", "Number":"Plur", "Person":"2", "Tense":"Pres", "VerbForm":"Fin"},
    "Vmr3p":{POS:VERB, "Mood":"Ind", "Number":"Plur", "Person":"3", "Tense":"Pres", "VerbForm":"Fin"},
    "Vmr3s":{POS:VERB, "Mood":"Ind", "Number":"Sing", "Person":"3", "Tense":"Pres", "VerbForm":"Fin"},
    "X":{POS:X},
    "Xf":{POS:X},
    "Y":{POS:ADJ},
    "Z":{POS:PUNCT}
}
