# encoding: utf8
from __future__ import unicode_literals

from spacy.symbols import ORTH, NORM, LEMMA

# splittting
# just testing

_exc = {
    "нпр.": [
        {ORTH: "н", NORM: "на"},
        {ORTH: "пр.", NORM: "пример"}
    ],
    "итд.": [
        {ORTH: "и"},
        {ORTH: "т", NORM: "тако"},
        {ORTH: "д.", NORM: "даље"}
    ]
}

# grouping
# hyphenated declinables in oblique cases; if normalizable + NORM

for exc_data in [
	{ORTH: "ААОМ-а", LEMMA: "ААОМ"},
	{ORTH: "ААОМ-ом", LEMMA: "ААОМ"},
	{ORTH: "ААОМ-у", LEMMA: "ААОМ"},
	{ORTH: "ААС-а", LEMMA: "ААС"},
	{ORTH: "ААС-ом", LEMMA: "ААС"},
	{ORTH: "ААС-у", LEMMA: "ААС"},
	{ORTH: "АБАФ-а", LEMMA: "АБАФ"},
	{ORTH: "АБАФ-ом", LEMMA: "АБАФ"},
	{ORTH: "АБАФ-у", LEMMA: "АБАФ"},
	{ORTH: "АБПК-а", LEMMA: "АБПК"},
	{ORTH: "АБПК-ом", LEMMA: "АБПК"},
	{ORTH: "АБПК-у", LEMMA: "АБПК"},
	{ORTH: "АБС-а", LEMMA: "АБС"},
	{ORTH: "АБС-а", LEMMA: "АБС"},
	{ORTH: "АБС-ом", LEMMA: "АБС"},
	{ORTH: "АБС-ом", LEMMA: "АБС"},
	{ORTH: "АБС-у", LEMMA: "АБС"},
	{ORTH: "АБС-у", LEMMA: "АБС"},
	{ORTH: "АБЦ-ја", LEMMA: "АБЦ"},
	{ORTH: "АБЦ-јем", LEMMA: "АБЦ"},
	{ORTH: "АБЦ-ју", LEMMA: "АБЦ"},
	{ORTH: "АВНОЈ-а", LEMMA: "АВНОЈ"},
	{ORTH: "АВНОЈ-ем", LEMMA: "АВНОЈ"},
	{ORTH: "АВНОЈ-у", LEMMA: "АВНОЈ"},
	{ORTH: "АДАС-а", LEMMA: "АДАС"},
	{ORTH: "АДАС-ом", LEMMA: "АДАС"},
	{ORTH: "АДАС-у", LEMMA: "АДАС"},
	{ORTH: "АДП-а", LEMMA: "АДП"},
	{ORTH: "АДП-ом", LEMMA: "АДП"},
	{ORTH: "АДП-у", LEMMA: "АДП"},
	{ORTH: "АДС-а", LEMMA: "АДС"},
	{ORTH: "АДС-ом", LEMMA: "АДС"},
	{ORTH: "АДС-у", LEMMA: "АДС"},
	{ORTH: "АЕК-а", LEMMA: "АЕК"},
	{ORTH: "АЕК-ом", LEMMA: "АЕК"},
	{ORTH: "АЕК-у", LEMMA: "АЕК"},
	{ORTH: "АЕРС-а", LEMMA: "АЕРС"},
	{ORTH: "АЕРС-ом", LEMMA: "АЕРС"},
	{ORTH: "АЕРС-у", LEMMA: "АЕРС"},
	{ORTH: "АЖС-а", LEMMA: "АЖС"},
	{ORTH: "АЖС-ом", LEMMA: "АЖС"},
	{ORTH: "АЖС-у", LEMMA: "АЖС"},
	{ORTH: "АЗУС-а", LEMMA: "АЗУС"},
	{ORTH: "АЗУС-ом", LEMMA: "АЗУС"},
	{ORTH: "АЗУС-у", LEMMA: "АЗУС"},
	{ORTH: "АИНС-а", LEMMA: "АИНС"},
	{ORTH: "АИНС-ом", LEMMA: "АИНС"},
	{ORTH: "АИНС-у", LEMMA: "АИНС"},
	{ORTH: "АИФ-а", LEMMA: "АИФ"},
	{ORTH: "АИФ-ова", LEMMA: "АИФ"},
	{ORTH: "АИФ-ове", LEMMA: "АИФ"},
	{ORTH: "АИФ-ови", LEMMA: "АИФ"},
	{ORTH: "АИФ-овима", LEMMA: "АИФ"},
	{ORTH: "АИФ-ом", LEMMA: "АИФ"},
	{ORTH: "АИФ-у", LEMMA: "АИФ"},
	{ORTH: "Ај-Би-Ем", LEMMA: "Ај-Би-Ем", NORM:"ИБМ"},
	{ORTH: "Ај-Би-Ема", LEMMA: "Ај-Би-Ем", NORM:"ИБМ-а"},
	{ORTH: "Ај-Би-Емом", LEMMA: "Ај-Би-Ем", NORM:"ИБМ-ом"},
	{ORTH: "Ај-Би-Ему", LEMMA: "Ај-Би-Ем", NORM:"ИБМ-у"},
	{ORTH: "ај-ти", LEMMA: "ај-ти", NORM:"ИТ"},
	{ORTH: "ај-тија", LEMMA: "ај-ти", NORM:"ИТ-ја"},
	{ORTH: "ај-тијем", LEMMA: "ај-ти", NORM:"ИТ-јем"},
	{ORTH: "ај-тију", LEMMA: "ај-ти", NORM:"ИТ-ју"},
	{ORTH: "АКС-а", LEMMA: "АКС"},
	{ORTH: "АКС-ом", LEMMA: "АКС"},
	{ORTH: "АКС-у", LEMMA: "АКС"},
	{ORTH: "АКУД-а", LEMMA: "АКУД"},
	{ORTH: "АКУД-ом", LEMMA: "АКУД"},
	{ORTH: "АКУД-у", LEMMA: "АКУД"},
	{ORTH: "АЛЕР-а", LEMMA: "АЛЕР"},
	{ORTH: "АЛЕР-ом", LEMMA: "АЛЕР"},
	{ORTH: "АЛЕР-у", LEMMA: "АЛЕР"},
	{ORTH: "АЛИМС-а", LEMMA: "АЛИМС"},
	{ORTH: "АЛИМС-ом", LEMMA: "АЛИМС"},
	{ORTH: "АЛИМС-у", LEMMA: "АЛИМС"},
	{ORTH: "АМП-а", LEMMA: "АМП"},
	{ORTH: "АМП-ом", LEMMA: "АМП"},
	{ORTH: "АМП-у", LEMMA: "АМП"},
	{ORTH: "АМРЕС-а", LEMMA: "АМРЕС"},
	{ORTH: "АМРЕС-ом", LEMMA: "АМРЕС"},
	{ORTH: "АМРЕС-у", LEMMA: "АМРЕС"},
	{ORTH: "АМС-а", LEMMA: "АМС"},
	{ORTH: "АМС-ом", LEMMA: "АМС"},
	{ORTH: "АМС-у", LEMMA: "АМС"},
	{ORTH: "АМСС-а", LEMMA: "АМСС"},
	{ORTH: "АМСС-ом", LEMMA: "АМСС"},
	{ORTH: "АМСС-у", LEMMA: "АМСС"},
	{ORTH: "АНА-е", LEMMA: "АНА"},
	{ORTH: "АНА-и", LEMMA: "АНА"},
	{ORTH: "АНА-ом", LEMMA: "АНА"},
	{ORTH: "АНА-у", LEMMA: "АНА"},
	{ORTH: "АНБ-а", LEMMA: "АНБ"},
	{ORTH: "АНБ-ом", LEMMA: "АНБ"},
	{ORTH: "АНБ-у", LEMMA: "АНБ"},
	{ORTH: "АНЕМ-а", LEMMA: "АНЕМ"},
	{ORTH: "АНЕМ-ом", LEMMA: "АНЕМ"},
	{ORTH: "АНЕМ-у", LEMMA: "АНЕМ"},
	{ORTH: "АНСА-е", LEMMA: "АНСА"},
	{ORTH: "АНСА-и", LEMMA: "АНСА"},
	{ORTH: "АНСА-ом", LEMMA: "АНСА"},
	{ORTH: "АНСА-у", LEMMA: "АНСА"},
	{ORTH: "АНУРС-а", LEMMA: "АНУРС"},
	{ORTH: "АНУРС-ом", LEMMA: "АНУРС"},
	{ORTH: "АНУРС-у", LEMMA: "АНУРС"},
	{ORTH: "АОД-а", LEMMA: "АОД"},
	{ORTH: "АОД-ом", LEMMA: "АОД"},
	{ORTH: "АОД-у", LEMMA: "АОД"},
	{ORTH: "АОФИ-ја", LEMMA: "АОФИ"},
	{ORTH: "АОФИ-јем", LEMMA: "АОФИ"},
	{ORTH: "АОФИ-ју", LEMMA: "АОФИ"},
	{ORTH: "АП-а", LEMMA: "АП"},
	{ORTH: "АП-а", LEMMA: "АП"},
	{ORTH: "АП-ом", LEMMA: "АП"},
	{ORTH: "АП-ом", LEMMA: "АП"},
	{ORTH: "АП-у", LEMMA: "АП"},
	{ORTH: "АП-у", LEMMA: "АП"},
	{ORTH: "АПАС-а", LEMMA: "АПАС"},
	{ORTH: "АПАС-ом", LEMMA: "АПАС"},
	{ORTH: "АПАС-у", LEMMA: "АПАС"},
	{ORTH: "АПД-а", LEMMA: "АПД"},
	{ORTH: "АПД-ом", LEMMA: "АПД"},
	{ORTH: "АПД-у", LEMMA: "АПД"},
	{ORTH: "АПИФ-а", LEMMA: "АПИФ"},
	{ORTH: "АПИФ-ом", LEMMA: "АПИФ"},
	{ORTH: "АПИФ-у", LEMMA: "АПИФ"},
	{ORTH: "АПР-а", LEMMA: "АПР"},
	{ORTH: "АПР-ом", LEMMA: "АПР"},
	{ORTH: "АПР-у", LEMMA: "АПР"},
	{ORTH: "АПУ-а", LEMMA: "АПУ"},
	{ORTH: "АПУ-ом", LEMMA: "АПУ"},
	{ORTH: "АПУ-у", LEMMA: "АПУ"},
	{ORTH: "АРС-а", LEMMA: "АРС"},
	{ORTH: "АРС-ом", LEMMA: "АРС"},
	{ORTH: "АРС-у", LEMMA: "АРС"},
	{ORTH: "АСАК-а", LEMMA: "АСАК"},
	{ORTH: "АСАК-ом", LEMMA: "АСАК"},
	{ORTH: "АСАК-у", LEMMA: "АСАК"},
	{ORTH: "АСБ-а", LEMMA: "АСБ"},
	{ORTH: "АСБ-ом", LEMMA: "АСБ"},
	{ORTH: "АСБ-у", LEMMA: "АСБ"},
	{ORTH: "АСЕАН-а", LEMMA: "АСЕАН"},
	{ORTH: "АСЕАН-ом", LEMMA: "АСЕАН"},
	{ORTH: "АСЕАН-у", LEMMA: "АСЕАН"},
	{ORTH: "АСНОМ-а", LEMMA: "АСНОМ"},
	{ORTH: "АСНОМ-ом", LEMMA: "АСНОМ"},
	{ORTH: "АСНОМ-у", LEMMA: "АСНОМ"},
	{ORTH: "АСНОС-а", LEMMA: "АСНОС"},
	{ORTH: "АСНОС-ом", LEMMA: "АСНОС"},
	{ORTH: "АСНОС-у", LEMMA: "АСНОС"},
	{ORTH: "АСНС-а", LEMMA: "АСНС"},
	{ORTH: "АСНС-ом", LEMMA: "АСНС"},
	{ORTH: "АСНС-у", LEMMA: "АСНС"},
	{ORTH: "АСС-а", LEMMA: "АСС"},
	{ORTH: "АСС-ом", LEMMA: "АСС"},
	{ORTH: "АСС-у", LEMMA: "АСС"},
	{ORTH: "АСЦС-а", LEMMA: "АСЦС"},
	{ORTH: "АСЦС-ом", LEMMA: "АСЦС"},
	{ORTH: "АСЦС-у", LEMMA: "АСЦС"},
	{ORTH: "АТД-а", LEMMA: "АТД"},
	{ORTH: "АТД-ом", LEMMA: "АТД"},
	{ORTH: "АТД-у", LEMMA: "АТД"},
	{ORTH: "АТП-а", LEMMA: "АТП"},
	{ORTH: "АТП-а", LEMMA: "АТП"},
	{ORTH: "АТП-а", LEMMA: "АТП"},
	{ORTH: "АТП-ом", LEMMA: "АТП"},
	{ORTH: "АТП-ом", LEMMA: "АТП"},
	{ORTH: "АТП-ом", LEMMA: "АТП"},
	{ORTH: "АТП-у", LEMMA: "АТП"},
	{ORTH: "АТП-у", LEMMA: "АТП"},
	{ORTH: "АТП-у", LEMMA: "АТП"},
	{ORTH: "АТС-а", LEMMA: "АТС"},
	{ORTH: "АТС-ом", LEMMA: "АТС"},
	{ORTH: "АТС-у", LEMMA: "АТС"},
	{ORTH: "АУЛ-а", LEMMA: "АУЛ"},
	{ORTH: "АУЛ-ом", LEMMA: "АУЛ"},
	{ORTH: "АУЛ-у", LEMMA: "АУЛ"},
	{ORTH: "АфД-а", LEMMA: "АфД"},
	{ORTH: "АфД-ом", LEMMA: "АфД"},
	{ORTH: "АфД-у", LEMMA: "АфД"},
	{ORTH: "АФЖ-а", LEMMA: "АФЖ"},
	{ORTH: "АФЖ-ом", LEMMA: "АФЖ"},
	{ORTH: "АФЖ-у", LEMMA: "АФЖ"},
	{ORTH: "АФП-а", LEMMA: "АФП"},
	{ORTH: "АФП-ом", LEMMA: "АФП"},
	{ORTH: "АФП-у", LEMMA: "АФП"},
	{ORTH: "БАН-а", LEMMA: "БАН"},
	{ORTH: "БАН-ом", LEMMA: "БАН"},
	{ORTH: "БАН-у", LEMMA: "БАН"},
	{ORTH: "БАС-а", LEMMA: "БАС"},
	{ORTH: "БАС-ом", LEMMA: "БАС"},
	{ORTH: "БАС-у", LEMMA: "БАС"},
	{ORTH: "ББЦ-ја", LEMMA: "ББЦ"},
	{ORTH: "ББЦ-јем", LEMMA: "ББЦ"},
	{ORTH: "ББЦ-ју", LEMMA: "ББЦ"},
	{ORTH: "БГБ-а", LEMMA: "БГБ"},
	{ORTH: "БГБ-ом", LEMMA: "БГБ"},
	{ORTH: "БГБ-у", LEMMA: "БГБ"},
	{ORTH: "Бгд-а", LEMMA: "Бгд"},
	{ORTH: "Бгд-ом", LEMMA: "Бгд"},
	{ORTH: "Бгд-у", LEMMA: "Бгд"},
	{ORTH: "БГС-а", LEMMA: "БГС"},
	{ORTH: "БГС-ом", LEMMA: "БГС"},
	{ORTH: "БГС-у", LEMMA: "БГС"},
	{ORTH: "БДВ-а", LEMMA: "БДВ"},
	{ORTH: "БДВ-ом", LEMMA: "БДВ"},
	{ORTH: "БДВ-у", LEMMA: "БДВ"},
	{ORTH: "БДЗ-а", LEMMA: "БДЗ"},
	{ORTH: "БДЗ-ом", LEMMA: "БДЗ"},
	{ORTH: "БДЗ-у", LEMMA: "БДЗ"},
	{ORTH: "БДП-а", LEMMA: "БДП"},
	{ORTH: "БДП-а", LEMMA: "БДП"},
	{ORTH: "БДП-ом", LEMMA: "БДП"},
	{ORTH: "БДП-ом", LEMMA: "БДП"},
	{ORTH: "БДП-у", LEMMA: "БДП"},
	{ORTH: "БДП-у", LEMMA: "БДП"},
	{ORTH: "БДС-а", LEMMA: "БДС"},
	{ORTH: "БДС-ом", LEMMA: "БДС"},
	{ORTH: "БДС-у", LEMMA: "БДС"},
	{ORTH: "БДСС-а", LEMMA: "БДСС"},
	{ORTH: "БДСС-ом", LEMMA: "БДСС"},
	{ORTH: "БДСС-у", LEMMA: "БДСС"},
	{ORTH: "БЕЛЕФ-а", LEMMA: "БЕЛЕФ"},
	{ORTH: "БЕЛЕФ-ом", LEMMA: "БЕЛЕФ"},
	{ORTH: "БЕЛЕФ-у", LEMMA: "БЕЛЕФ"},
	{ORTH: "БЕМУС-а", LEMMA: "БЕМУС"},
	{ORTH: "БЕМУС-ом", LEMMA: "БЕМУС"},
	{ORTH: "БЕМУС-у", LEMMA: "БЕМУС"},
	{ORTH: "БЗР-а", LEMMA: "БЗР"},
	{ORTH: "БЗР-ом", LEMMA: "БЗР"},
	{ORTH: "БЗР-у", LEMMA: "БЗР"},
	{ORTH: "Би-Би-Си", LEMMA: "Би-Би-Си", NORM:"ББЦ"},
	{ORTH: "Би-Би-Сија", LEMMA: "Би-Би-Си", NORM:"ББЦ-ја"},
	{ORTH: "Би-Би-Сијем", LEMMA: "Би-Би-Си", NORM:"ББЦ-јем"},
	{ORTH: "Би-Би-Сију", LEMMA: "Би-Би-Си", NORM:"ББЦ-ју"},
	{ORTH: "БИА-е", LEMMA: "БИА"},
	{ORTH: "БИА-и", LEMMA: "БИА"},
	{ORTH: "БИА-ом", LEMMA: "БИА"},
	{ORTH: "БИА-у", LEMMA: "БИА"},
	{ORTH: "БИГЗ-а", LEMMA: "БИГЗ"},
	{ORTH: "БИГЗ-ом", LEMMA: "БИГЗ"},
	{ORTH: "БИГЗ-у", LEMMA: "БИГЗ"},
	{ORTH: "БИП-а", LEMMA: "БИП"},
	{ORTH: "БИП-ом", LEMMA: "БИП"},
	{ORTH: "БИП-у", LEMMA: "БИП"},
	{ORTH: "БИРН-а", LEMMA: "БИРН"},
	{ORTH: "БИРН-ом", LEMMA: "БИРН"},
	{ORTH: "БИРН-у", LEMMA: "БИРН"},
	{ORTH: "БИС-а", LEMMA: "БИС"},
	{ORTH: "БИС-а", LEMMA: "БИС"},
	{ORTH: "БИС-ом", LEMMA: "БИС"},
	{ORTH: "БИС-ом", LEMMA: "БИС"},
	{ORTH: "БИС-у", LEMMA: "БИС"},
	{ORTH: "БИС-у", LEMMA: "БИС"},
	{ORTH: "БИСИС-а", LEMMA: "БИСИС"},
	{ORTH: "БИСИС-ом", LEMMA: "БИСИС"},
	{ORTH: "БИСИС-у", LEMMA: "БИСИС"},
	{ORTH: "БИТЕФ-а", LEMMA: "БИТЕФ"},
	{ORTH: "БИТЕФ-ом", LEMMA: "БИТЕФ"},
	{ORTH: "БИТЕФ-у", LEMMA: "БИТЕФ"},
	{ORTH: "БМП-а", LEMMA: "БМП"},
	{ORTH: "БМП-ом", LEMMA: "БМП"},
	{ORTH: "БМП-у", LEMMA: "БМП"},
	{ORTH: "БМС-а", LEMMA: "БМС"},
	{ORTH: "БМС-ом", LEMMA: "БМС"},
	{ORTH: "БМС-у", LEMMA: "БМС"},
	{ORTH: "БНД-а", LEMMA: "БНД"},
	{ORTH: "БНД-ом", LEMMA: "БНД"},
	{ORTH: "БНД-у", LEMMA: "БНД"},
	{ORTH: "БНП-а", LEMMA: "БНП"},
	{ORTH: "БНП-ом", LEMMA: "БНП"},
	{ORTH: "БНП-у", LEMMA: "БНП"},
	{ORTH: "БНС-а", LEMMA: "БНС"},
	{ORTH: "БНС-ом", LEMMA: "БНС"},
	{ORTH: "БНС-у", LEMMA: "БНС"},
	{ORTH: "БОШ-а", LEMMA: "БОШ"},
	{ORTH: "БОШ-ом", LEMMA: "БОШ"},
	{ORTH: "БОШ-у", LEMMA: "БОШ"},
	{ORTH: "БРИК-а", LEMMA: "БРИК"},
	{ORTH: "БРИК-ом", LEMMA: "БРИК"},
	{ORTH: "БРИК-у", LEMMA: "БРИК"},
	{ORTH: "БРИКС-а", LEMMA: "БРИКС"},
	{ORTH: "БРИКС-ом", LEMMA: "БРИКС"},
	{ORTH: "БРИКС-у", LEMMA: "БРИКС"},
	{ORTH: "БРИЦ-а", LEMMA: "БРИЦ"},
	{ORTH: "БРИЦ-ом", LEMMA: "БРИЦ"},
	{ORTH: "БРИЦ-у", LEMMA: "БРИЦ"},
	{ORTH: "БРИЦС-а", LEMMA: "БРИЦС"},
	{ORTH: "БРИЦС-ом", LEMMA: "БРИЦС"},
	{ORTH: "БРИЦС-у", LEMMA: "БРИЦС"},
	{ORTH: "БСК-а", LEMMA: "БСК"},
	{ORTH: "БСК-а", LEMMA: "БСК"},
	{ORTH: "БСК-ом", LEMMA: "БСК"},
	{ORTH: "БСК-ом", LEMMA: "БСК"},
	{ORTH: "БСК-у", LEMMA: "БСК"},
	{ORTH: "БСК-у", LEMMA: "БСК"},
	{ORTH: "БСС-а", LEMMA: "БСС"},
	{ORTH: "БСС-а", LEMMA: "БСС"},
	{ORTH: "БСС-ом", LEMMA: "БСС"},
	{ORTH: "БСС-ом", LEMMA: "БСС"},
	{ORTH: "БСС-у", LEMMA: "БСС"},
	{ORTH: "БСС-у", LEMMA: "БСС"},
	{ORTH: "БЦБП-а", LEMMA: "БЦБП"},
	{ORTH: "БЦБП-ом", LEMMA: "БЦБП"},
	{ORTH: "БЦБП-у", LEMMA: "БЦБП"},
	{ORTH: "ВБС-а", LEMMA: "ВБС"},
	{ORTH: "ВБС-ом", LEMMA: "ВБС"},
	{ORTH: "ВБС-у", LEMMA: "ВБС"},
	{ORTH: "ви-џеј", LEMMA: "ви-џеј", NORM:"ВЈ"},
	{ORTH: "ви-џеја", LEMMA: "ви-џеј", NORM:"ВЈ-а"},
	{ORTH: "ви-џејева", LEMMA: "ви-џеј", NORM:"ВЈ-ева"},
	{ORTH: "ви-џејеве", LEMMA: "ви-џеј", NORM:"ВЈ-еве"},
	{ORTH: "ви-џејеви", LEMMA: "ви-џеј", NORM:"ВЈ-еви"},
	{ORTH: "ви-џејевима", LEMMA: "ви-џеј", NORM:"ВЈ-евима"},
	{ORTH: "ви-џејем", LEMMA: "ви-џеј", NORM:"ВЈ-ем"},
	{ORTH: "ви-џеју", LEMMA: "ви-џеј", NORM:"ВЈ-у"},
	{ORTH: "ВИС-а", LEMMA: "ВИС"},
	{ORTH: "ВИС-а", LEMMA: "ВИС"},
	{ORTH: "ВИС-ова", LEMMA: "ВИС"},
	{ORTH: "ВИС-ове", LEMMA: "ВИС"},
	{ORTH: "ВИС-ови", LEMMA: "ВИС"},
	{ORTH: "ВИС-овима", LEMMA: "ВИС"},
	{ORTH: "ВИС-ом", LEMMA: "ВИС"},
	{ORTH: "ВИС-ом", LEMMA: "ВИС"},
	{ORTH: "ВИС-у", LEMMA: "ВИС"},
	{ORTH: "ВИС-у", LEMMA: "ВИС"},
	{ORTH: "ВЈ-а", LEMMA: "ВЈ"},
	{ORTH: "ВЈ-ева", LEMMA: "ВЈ"},
	{ORTH: "ВЈ-еве", LEMMA: "ВЈ"},
	{ORTH: "ВЈ-еви", LEMMA: "ВЈ"},
	{ORTH: "ВЈ-евима", LEMMA: "ВЈ"},
	{ORTH: "ВЈ-ем", LEMMA: "ВЈ"},
	{ORTH: "ВЈ-у", LEMMA: "ВЈ"},
	{ORTH: "ВКС-а", LEMMA: "ВКС"},
	{ORTH: "ВКС-а", LEMMA: "ВКС"},
	{ORTH: "ВКС-ом", LEMMA: "ВКС"},
	{ORTH: "ВКС-ом", LEMMA: "ВКС"},
	{ORTH: "ВКС-у", LEMMA: "ВКС"},
	{ORTH: "ВКС-у", LEMMA: "ВКС"},
	{ORTH: "ВНС-а", LEMMA: "ВНС"},
	{ORTH: "ВНС-ом", LEMMA: "ВНС"},
	{ORTH: "ВНС-у", LEMMA: "ВНС"},
	{ORTH: "ВП-а", LEMMA: "ВП"},
	{ORTH: "ВП-ом", LEMMA: "ВП"},
	{ORTH: "ВП-у", LEMMA: "ВП"},
	{ORTH: "ВРС-а", LEMMA: "ВРС"},
	{ORTH: "ВРС-ом", LEMMA: "ВРС"},
	{ORTH: "ВРС-у", LEMMA: "ВРС"},
	{ORTH: "ВСС-а", LEMMA: "ВСС"},
	{ORTH: "ВСС-а", LEMMA: "ВСС"},
	{ORTH: "ВСС-а", LEMMA: "ВСС"},
	{ORTH: "ВСС-а", LEMMA: "ВСС"},
	{ORTH: "ВСС-ом", LEMMA: "ВСС"},
	{ORTH: "ВСС-ом", LEMMA: "ВСС"},
	{ORTH: "ВСС-ом", LEMMA: "ВСС"},
	{ORTH: "ВСС-ом", LEMMA: "ВСС"},
	{ORTH: "ВСС-у", LEMMA: "ВСС"},
	{ORTH: "ВСС-у", LEMMA: "ВСС"},
	{ORTH: "ВСС-у", LEMMA: "ВСС"},
	{ORTH: "ВСС-у", LEMMA: "ВСС"},
	{ORTH: "ВШУП-а", LEMMA: "ВШУП"},
	{ORTH: "ВШУП-ом", LEMMA: "ВШУП"},
	{ORTH: "ВШУП-у", LEMMA: "ВШУП"},
	{ORTH: "ГАЈП-а", LEMMA: "ГАЈП"},
	{ORTH: "ГАЈП-ом", LEMMA: "ГАЈП"},
	{ORTH: "ГАЈП-у", LEMMA: "ГАЈП"},
	{ORTH: "ГАК-а", LEMMA: "ГАК"},
	{ORTH: "ГАК-ова", LEMMA: "ГАК"},
	{ORTH: "ГАК-ове", LEMMA: "ГАК"},
	{ORTH: "ГАК-ови", LEMMA: "ГАК"},
	{ORTH: "ГАК-овима", LEMMA: "ГАК"},
	{ORTH: "ГАК-ом", LEMMA: "ГАК"},
	{ORTH: "ГАК-у", LEMMA: "ГАК"},
	{ORTH: "ГАФ-а", LEMMA: "ГАФ"},
	{ORTH: "ГАФ-ом", LEMMA: "ГАФ"},
	{ORTH: "ГАФ-у", LEMMA: "ГАФ"},
	{ORTH: "ГДС-а", LEMMA: "ГДС"},
	{ORTH: "ГДС-а", LEMMA: "ГДС"},
	{ORTH: "ГДС-ом", LEMMA: "ГДС"},
	{ORTH: "ГДС-ом", LEMMA: "ГДС"},
	{ORTH: "ГДС-у", LEMMA: "ГДС"},
	{ORTH: "ГДС-у", LEMMA: "ГДС"},
	{ORTH: "ГДФ-а", LEMMA: "ГДФ"},
	{ORTH: "ГДФ-ом", LEMMA: "ГДФ"},
	{ORTH: "ГДФ-у", LEMMA: "ГДФ"},
	{ORTH: "ге-ес-ем", LEMMA: "ге-ес-ем", NORM:"ГСМ"},
	{ORTH: "ге-ес-ема", LEMMA: "ге-ес-ем", NORM:"ГСМ-а"},
	{ORTH: "ге-ес-емом", LEMMA: "ге-ес-ем", NORM:"ГСМ-ом"},
	{ORTH: "ге-ес-ему", LEMMA: "ге-ес-ем", NORM:"ГСМ-у"},
	{ORTH: "ГЕФ-а", LEMMA: "ГЕФ"},
	{ORTH: "ГЕФ-ом", LEMMA: "ГЕФ"},
	{ORTH: "ГЕФ-у", LEMMA: "ГЕФ"},
	{ORTH: "ГЗЗЈЗ-а", LEMMA: "ГЗЗЈЗ"},
	{ORTH: "ГЗЗЈЗ-ом", LEMMA: "ГЗЗЈЗ"},
	{ORTH: "ГЗЗЈЗ-у", LEMMA: "ГЗЗЈЗ"},
	{ORTH: "ГИГ-а", LEMMA: "ГИГ"},
	{ORTH: "ГИГ-ом", LEMMA: "ГИГ"},
	{ORTH: "ГИГ-у", LEMMA: "ГИГ"},
	{ORTH: "ГИК-а", LEMMA: "ГИК"},
	{ORTH: "ГИК-ом", LEMMA: "ГИК"},
	{ORTH: "ГИК-у", LEMMA: "ГИК"},
	{ORTH: "ГИС-а", LEMMA: "ГИС"},
	{ORTH: "ГИС-ом", LEMMA: "ГИС"},
	{ORTH: "ГИС-у", LEMMA: "ГИС"},
	{ORTH: "ГМО-а", LEMMA: "ГМО"},
	{ORTH: "ГМО-ом", LEMMA: "ГМО"},
	{ORTH: "ГМО-у", LEMMA: "ГМО"},
	{ORTH: "ГНО-а", LEMMA: "ГНО"},
	{ORTH: "ГНО-ом", LEMMA: "ГНО"},
	{ORTH: "ГНО-у", LEMMA: "ГНО"},
	{ORTH: "ГНОО-а", LEMMA: "ГНОО"},
	{ORTH: "ГНОО-ом", LEMMA: "ГНОО"},
	{ORTH: "ГНОО-у", LEMMA: "ГНОО"},
	{ORTH: "ГП-а", LEMMA: "ГП"},
	{ORTH: "ГП-ом", LEMMA: "ГП"},
	{ORTH: "ГП-у", LEMMA: "ГП"},
	{ORTH: "ГРЕКО-а", LEMMA: "ГРЕКО"},
	{ORTH: "ГРЕКО-ом", LEMMA: "ГРЕКО"},
	{ORTH: "ГРЕКО-у", LEMMA: "ГРЕКО"},
	{ORTH: "ГРЕЦО-а", LEMMA: "ГРЕЦО"},
	{ORTH: "ГРЕЦО-ом", LEMMA: "ГРЕЦО"},
	{ORTH: "ГРЕЦО-у", LEMMA: "ГРЕЦО"},
	{ORTH: "ГРФ-а", LEMMA: "ГРФ"},
	{ORTH: "ГРФ-ом", LEMMA: "ГРФ"},
	{ORTH: "ГРФ-у", LEMMA: "ГРФ"},
	{ORTH: "ГСБ-а", LEMMA: "ГСБ"},
	{ORTH: "ГСБ-а", LEMMA: "ГСБ"},
	{ORTH: "ГСБ-а", LEMMA: "ГСБ"},
	{ORTH: "ГСБ-ом", LEMMA: "ГСБ"},
	{ORTH: "ГСБ-ом", LEMMA: "ГСБ"},
	{ORTH: "ГСБ-ом", LEMMA: "ГСБ"},
	{ORTH: "ГСБ-у", LEMMA: "ГСБ"},
	{ORTH: "ГСБ-у", LEMMA: "ГСБ"},
	{ORTH: "ГСБ-у", LEMMA: "ГСБ"},
	{ORTH: "ГСМ-а", LEMMA: "ГСМ"},
	{ORTH: "ГСМ-ом", LEMMA: "ГСМ"},
	{ORTH: "ГСМ-у", LEMMA: "ГСМ"},
	{ORTH: "ГСП-а", LEMMA: "ГСП"},
	{ORTH: "ГСП-ом", LEMMA: "ГСП"},
	{ORTH: "ГСП-у", LEMMA: "ГСП"},
	{ORTH: "ГСС-а", LEMMA: "ГСС"},
	{ORTH: "ГСС-а", LEMMA: "ГСС"},
	{ORTH: "ГСС-ом", LEMMA: "ГСС"},
	{ORTH: "ГСС-ом", LEMMA: "ГСС"},
	{ORTH: "ГСС-у", LEMMA: "ГСС"},
	{ORTH: "ГСС-у", LEMMA: "ГСС"},
	{ORTH: "ГУЛАГ-а", LEMMA: "ГУЛАГ"},
	{ORTH: "ГУЛАГ-ом", LEMMA: "ГУЛАГ"},
	{ORTH: "ГУЛАГ-у", LEMMA: "ГУЛАГ"},
	{ORTH: "ГУП-а", LEMMA: "ГУП"},
	{ORTH: "ГУП-ова", LEMMA: "ГУП"},
	{ORTH: "ГУП-ове", LEMMA: "ГУП"},
	{ORTH: "ГУП-ови", LEMMA: "ГУП"},
	{ORTH: "ГУП-овима", LEMMA: "ГУП"},
	{ORTH: "ГУП-ом", LEMMA: "ГУП"},
	{ORTH: "ГУП-у", LEMMA: "ГУП"},
	{ORTH: "ГЦСР-а", LEMMA: "ГЦСР"},
	{ORTH: "ГЦСР-ом", LEMMA: "ГЦСР"},
	{ORTH: "ГЦСР-у", LEMMA: "ГЦСР"},
	{ORTH: "ГШ-а", LEMMA: "ГШ"},
	{ORTH: "ГШ-ом", LEMMA: "ГШ"},
	{ORTH: "ГШ-у", LEMMA: "ГШ"},
	{ORTH: "ДАБ-а", LEMMA: "ДАБ"},
	{ORTH: "ДАБ-ом", LEMMA: "ДАБ"},
	{ORTH: "ДАБ-у", LEMMA: "ДАБ"},
	{ORTH: "ДАЕС-а", LEMMA: "ДАЕС"},
	{ORTH: "ДАЕС-ом", LEMMA: "ДАЕС"},
	{ORTH: "ДАЕС-у", LEMMA: "ДАЕС"},
	{ORTH: "ДАИС-а", LEMMA: "ДАИС"},
	{ORTH: "ДАИС-ом", LEMMA: "ДАИС"},
	{ORTH: "ДАИС-у", LEMMA: "ДАИС"},
	{ORTH: "ДАРВ-а", LEMMA: "ДАРВ"},
	{ORTH: "ДАРВ-ом", LEMMA: "ДАРВ"},
	{ORTH: "ДАРВ-у", LEMMA: "ДАРВ"},
	{ORTH: "ДБ-а", LEMMA: "ДБ"},
	{ORTH: "ДБ-ом", LEMMA: "ДБ"},
	{ORTH: "ДБ-у", LEMMA: "ДБ"},
	{ORTH: "ДВ-а", LEMMA: "ДВ"},
	{ORTH: "ДВ-ом", LEMMA: "ДВ"},
	{ORTH: "ДВ-у", LEMMA: "ДВ"},
	{ORTH: "ДВД-а", LEMMA: "ДВД"},
	{ORTH: "ДВД-а", LEMMA: "ДВД"},
	{ORTH: "ДВД-е", LEMMA: "ДВД"},
	{ORTH: "ДВД-и", LEMMA: "ДВД"},
	{ORTH: "ДВД-има", LEMMA: "ДВД"},
	{ORTH: "ДВД-ја", LEMMA: "ДВД"},
	{ORTH: "ДВД-ја", LEMMA: "ДВД"},
	{ORTH: "ДВД-је", LEMMA: "ДВД"},
	{ORTH: "ДВД-јем", LEMMA: "ДВД"},
	{ORTH: "ДВД-ји", LEMMA: "ДВД"},
	{ORTH: "ДВД-јима", LEMMA: "ДВД"},
	{ORTH: "ДВД-ју", LEMMA: "ДВД"},
	{ORTH: "ДВД-ом", LEMMA: "ДВД"},
	{ORTH: "ДВД-у", LEMMA: "ДВД"},
	{ORTH: "ДВТ-а", LEMMA: "ДВТ"},
	{ORTH: "ДВТ-ом", LEMMA: "ДВТ"},
	{ORTH: "ДВТ-у", LEMMA: "ДВТ"},
	{ORTH: "ДГЕИТС-а", LEMMA: "ДГЕИТС"},
	{ORTH: "ДГЕИТС-ом", LEMMA: "ДГЕИТС"},
	{ORTH: "ДГЕИТС-у", LEMMA: "ДГЕИТС"},
	{ORTH: "ДДТ-ја", LEMMA: "ДДТ"},
	{ORTH: "ДДТ-јем", LEMMA: "ДДТ"},
	{ORTH: "ДДТ-ју", LEMMA: "ДДТ"},
	{ORTH: "де-ве-де", LEMMA: "де-ве-де", NORM:"ДВД"},
	{ORTH: "де-ве-деа", LEMMA: "де-ве-де", NORM:"ДВД-а"},
	{ORTH: "де-ве-деа", LEMMA: "де-ве-де", NORM:"ДВД-а"},
	{ORTH: "де-ве-дее", LEMMA: "де-ве-де", NORM:"ДВД-е"},
	{ORTH: "де-ве-деи", LEMMA: "де-ве-де", NORM:"ДВД-е"},
	{ORTH: "де-ве-деима", LEMMA: "де-ве-де", NORM:"ДВД-има"},
	{ORTH: "де-ве-деом", LEMMA: "де-ве-де", NORM:"ДВД-ом"},
	{ORTH: "де-ве-деу", LEMMA: "де-ве-де", NORM:"ДВД-ом"},
	{ORTH: "ДЕПОС-а", LEMMA: "ДЕПОС"},
	{ORTH: "ДЕПОС-ом", LEMMA: "ДЕПОС"},
	{ORTH: "ДЕПОС-у", LEMMA: "ДЕПОС"},
	{ORTH: "ДЗВМ-а", LEMMA: "ДЗВМ"},
	{ORTH: "ДЗВМ-ом", LEMMA: "ДЗВМ"},
	{ORTH: "ДЗВМ-у", LEMMA: "ДЗВМ"},
	{ORTH: "ДЗХ-а", LEMMA: "ДЗХ"},
	{ORTH: "ДЗХ-ом", LEMMA: "ДЗХ"},
	{ORTH: "ДЗХ-у", LEMMA: "ДЗХ"},
	{ORTH: "ди-ви-ди", LEMMA: "ди-ви-ди", NORM:"ДВД"},
	{ORTH: "ди-ви-дија", LEMMA: "ди-ви-ди", NORM:"ДВД-ја"},
	{ORTH: "ди-ви-дија", LEMMA: "ди-ви-ди", NORM:"ДВД-ја"},
	{ORTH: "ди-ви-дије", LEMMA: "ди-ви-ди", NORM:"ДВД-је"},
	{ORTH: "ди-ви-дијем", LEMMA: "ди-ви-ди", NORM:"ДВД-јем"},
	{ORTH: "ди-ви-дији", LEMMA: "ди-ви-ди", NORM:"ДВД-ји"},
	{ORTH: "ди-ви-дијима", LEMMA: "ди-ви-ди", NORM:"ДВД-јима"},
	{ORTH: "ди-ви-дију", LEMMA: "ди-ви-ди", NORM:"ДВД-ју"},
	{ORTH: "ди-ди-ти", LEMMA: "ди-ди-ти", NORM:"ДДТ"},
	{ORTH: "ди-ди-тија", LEMMA: "ди-ди-ти", NORM:"ДДТ-ја"},
	{ORTH: "ди-ди-тијем", LEMMA: "ди-ди-ти", NORM:"ДДТ-јем"},
	{ORTH: "ди-ди-тију", LEMMA: "ди-ди-ти", NORM:"ДДТ-ју"},
	{ORTH: "ди-џеј", LEMMA: "ди-џеј", NORM:"ДЈ"},
	{ORTH: "ди-џеја", LEMMA: "ди-џеј", NORM:"ДЈ-а"},
	{ORTH: "ди-џејева", LEMMA: "ди-џеј", NORM:"ДЈ-ева"},
	{ORTH: "ди-џејеве", LEMMA: "ди-џеј", NORM:"ДЈ-еве"},
	{ORTH: "ди-џејеви", LEMMA: "ди-џеј", NORM:"ДЈ-еви"},
	{ORTH: "ди-џејевима", LEMMA: "ди-џеј", NORM:"ДЈ-евима"},
	{ORTH: "ди-џејем", LEMMA: "ди-џеј", NORM:"ДЈ-ем"},
	{ORTH: "ди-џеју", LEMMA: "ди-џеј", NORM:"ДЈ-у"},
	{ORTH: "ДИВ-а", LEMMA: "ДИВ"},
	{ORTH: "ДИВ-ом", LEMMA: "ДИВ"},
	{ORTH: "ДИВ-у", LEMMA: "ДИВ"},
	{ORTH: "ДИДС-а", LEMMA: "ДИДС"},
	{ORTH: "ДИДС-ом", LEMMA: "ДИДС"},
	{ORTH: "ДИДС-у", LEMMA: "ДИДС"},
	{ORTH: "ДИН-а", LEMMA: "ДИН"},
	{ORTH: "ДИН-ом", LEMMA: "ДИН"},
	{ORTH: "ДИН-у", LEMMA: "ДИН"},
	{ORTH: "ДИПОС-а", LEMMA: "ДИПОС"},
	{ORTH: "ДИПОС-ом", LEMMA: "ДИПОС"},
	{ORTH: "ДИПОС-у", LEMMA: "ДИПОС"},
	{ORTH: "ДИФ-а", LEMMA: "ДИФ"},
	{ORTH: "ДИФ-ом", LEMMA: "ДИФ"},
	{ORTH: "ДИФ-у", LEMMA: "ДИФ"},
	{ORTH: "ДЈ-а", LEMMA: "ДЈ"},
	{ORTH: "ДЈ-ева", LEMMA: "ДЈ"},
	{ORTH: "ДЈ-еве", LEMMA: "ДЈ"},
	{ORTH: "ДЈ-еви", LEMMA: "ДЈ"},
	{ORTH: "ДЈ-евима", LEMMA: "ДЈ"},
	{ORTH: "ДЈ-ем", LEMMA: "ДЈ"},
	{ORTH: "ДЈ-у", LEMMA: "ДЈ"},
	{ORTH: "ДЈБ-а", LEMMA: "ДЈБ"},
	{ORTH: "ДЈБ-ом", LEMMA: "ДЈБ"},
	{ORTH: "ДЈБ-у", LEMMA: "ДЈБ"},
	{ORTH: "ДКБ-а", LEMMA: "ДКБ"},
	{ORTH: "ДКБ-ом", LEMMA: "ДКБ"},
	{ORTH: "ДКБ-у", LEMMA: "ДКБ"},
	{ORTH: "ДКВ-а", LEMMA: "ДКВ"},
	{ORTH: "ДКВ-ом", LEMMA: "ДКВ"},
	{ORTH: "ДКВ-у", LEMMA: "ДКВ"},
	{ORTH: "ДКМ-а", LEMMA: "ДКМ"},
	{ORTH: "ДКМ-ом", LEMMA: "ДКМ"},
	{ORTH: "ДКМ-у", LEMMA: "ДКМ"},
	{ORTH: "ДКП-а", LEMMA: "ДКП"},
	{ORTH: "ДКП-а", LEMMA: "ДКП"},
	{ORTH: "ДКП-ом", LEMMA: "ДКП"},
	{ORTH: "ДКП-ом", LEMMA: "ДКП"},
	{ORTH: "ДКП-у", LEMMA: "ДКП"},
	{ORTH: "ДКП-у", LEMMA: "ДКП"},
	{ORTH: "ДКС-а", LEMMA: "ДКС"},
	{ORTH: "ДКС-ом", LEMMA: "ДКС"},
	{ORTH: "ДКС-у", LEMMA: "ДКС"},
	{ORTH: "ДКЦ-а", LEMMA: "ДКЦ"},
	{ORTH: "ДКЦ-ом", LEMMA: "ДКЦ"},
	{ORTH: "ДКЦ-у", LEMMA: "ДКЦ"},
	{ORTH: "ДКЦБ-а", LEMMA: "ДКЦБ"},
	{ORTH: "ДКЦБ-ом", LEMMA: "ДКЦБ"},
	{ORTH: "ДКЦБ-у", LEMMA: "ДКЦБ"},
	{ORTH: "ДМДМ-а", LEMMA: "ДМДМ"},
	{ORTH: "ДМДМ-ом", LEMMA: "ДМДМ"},
	{ORTH: "ДМДМ-у", LEMMA: "ДМДМ"},
	{ORTH: "ДМС-а", LEMMA: "ДМС"},
	{ORTH: "ДМС-ом", LEMMA: "ДМС"},
	{ORTH: "ДМС-у", LEMMA: "ДМС"},
	{ORTH: "ДОС-а", LEMMA: "ДОС"},
	{ORTH: "ДОС-ом", LEMMA: "ДОС"},
	{ORTH: "ДОС-у", LEMMA: "ДОС"},
	{ORTH: "ДП-а", LEMMA: "ДП"},
	{ORTH: "ДП-ом", LEMMA: "ДП"},
	{ORTH: "ДП-у", LEMMA: "ДП"},
	{ORTH: "ДПА-а", LEMMA: "ДПА"},
	{ORTH: "ДПА-ом", LEMMA: "ДПА"},
	{ORTH: "ДПА-у", LEMMA: "ДПА"},
	{ORTH: "ДПБ-а", LEMMA: "ДПБ"},
	{ORTH: "ДПБ-ом", LEMMA: "ДПБ"},
	{ORTH: "ДПБ-у", LEMMA: "ДПБ"},
	{ORTH: "ДПМ-а", LEMMA: "ДПМ"},
	{ORTH: "ДПМ-ом", LEMMA: "ДПМ"},
	{ORTH: "ДПМ-у", LEMMA: "ДПМ"},
	{ORTH: "ДПН-а", LEMMA: "ДПН"},
	{ORTH: "ДПН-ом", LEMMA: "ДПН"},
	{ORTH: "ДПН-у", LEMMA: "ДПН"},
	{ORTH: "ДПС-а", LEMMA: "ДПС"},
	{ORTH: "ДПС-а", LEMMA: "ДПС"},
	{ORTH: "ДПС-а", LEMMA: "ДПС"},
	{ORTH: "ДПС-ом", LEMMA: "ДПС"},
	{ORTH: "ДПС-ом", LEMMA: "ДПС"},
	{ORTH: "ДПС-ом", LEMMA: "ДПС"},
	{ORTH: "ДПС-у", LEMMA: "ДПС"},
	{ORTH: "ДПС-у", LEMMA: "ДПС"},
	{ORTH: "ДПС-у", LEMMA: "ДПС"},
	{ORTH: "ДПФ-а", LEMMA: "ДПФ"},
	{ORTH: "ДПФ-ом", LEMMA: "ДПФ"},
	{ORTH: "ДПФ-у", LEMMA: "ДПФ"},
	{ORTH: "ДРИ-ја", LEMMA: "ДРИ"},
	{ORTH: "ДРИ-јем", LEMMA: "ДРИ"},
	{ORTH: "ДРИ-ју", LEMMA: "ДРИ"},
	{ORTH: "ДС-а", LEMMA: "ДС"},
	{ORTH: "ДС-ом", LEMMA: "ДС"},
	{ORTH: "ДС-у", LEMMA: "ДС"},
	{ORTH: "ДСБ-а", LEMMA: "ДСБ"},
	{ORTH: "ДСБ-ом", LEMMA: "ДСБ"},
	{ORTH: "ДСБ-у", LEMMA: "ДСБ"},
	{ORTH: "ДСВМ-а", LEMMA: "ДСВМ"},
	{ORTH: "ДСВМ-ом", LEMMA: "ДСВМ"},
	{ORTH: "ДСВМ-у", LEMMA: "ДСВМ"},
	{ORTH: "ДСИП-а", LEMMA: "ДСИП"},
	{ORTH: "ДСИП-ом", LEMMA: "ДСИП"},
	{ORTH: "ДСИП-у", LEMMA: "ДСИП"},
	{ORTH: "ДСКМ-а", LEMMA: "ДСКМ"},
	{ORTH: "ДСКМ-ом", LEMMA: "ДСКМ"},
	{ORTH: "ДСКМ-у", LEMMA: "ДСКМ"},
	{ORTH: "ДСС-а", LEMMA: "ДСС"},
	{ORTH: "ДСС-а", LEMMA: "ДСС"},
	{ORTH: "ДСС-ом", LEMMA: "ДСС"},
	{ORTH: "ДСС-ом", LEMMA: "ДСС"},
	{ORTH: "ДСС-у", LEMMA: "ДСС"},
	{ORTH: "ДСС-у", LEMMA: "ДСС"},
	{ORTH: "ДСХВ-а", LEMMA: "ДСХВ"},
	{ORTH: "ДСХВ-ом", LEMMA: "ДСХВ"},
	{ORTH: "ДСХВ-у", LEMMA: "ДСХВ"},
	{ORTH: "ДТД-а", LEMMA: "ДТД"},
	{ORTH: "ДТД-ом", LEMMA: "ДТД"},
	{ORTH: "ДТД-у", LEMMA: "ДТД"},
	{ORTH: "ДУБ-а", LEMMA: "ДУБ"},
	{ORTH: "ДУБ-ом", LEMMA: "ДУБ"},
	{ORTH: "ДУБ-у", LEMMA: "ДУБ"},
	{ORTH: "ДУД-а", LEMMA: "ДУД"},
	{ORTH: "ДУД-ом", LEMMA: "ДУД"},
	{ORTH: "ДУД-у", LEMMA: "ДУД"},
	{ORTH: "ДУНП-а", LEMMA: "ДУНП"},
	{ORTH: "ДУНП-ом", LEMMA: "ДУНП"},
	{ORTH: "ДУНП-у", LEMMA: "ДУНП"},
	{ORTH: "ДУП-а", LEMMA: "ДУП"},
	{ORTH: "ДУП-ова", LEMMA: "ДУП"},
	{ORTH: "ДУП-ове", LEMMA: "ДУП"},
	{ORTH: "ДУП-ови", LEMMA: "ДУП"},
	{ORTH: "ДУП-овима", LEMMA: "ДУП"},
	{ORTH: "ДУП-ом", LEMMA: "ДУП"},
	{ORTH: "ДУП-у", LEMMA: "ДУП"},
	{ORTH: "ДУР-а", LEMMA: "ДУР"},
	{ORTH: "ДУР-ом", LEMMA: "ДУР"},
	{ORTH: "ДУР-у", LEMMA: "ДУР"},
	{ORTH: "ДФС-а", LEMMA: "ДФС"},
	{ORTH: "ДФС-ом", LEMMA: "ДФС"},
	{ORTH: "ДФС-у", LEMMA: "ДФС"},
	{ORTH: "ДХСС-а", LEMMA: "ДХСС"},
	{ORTH: "ДХСС-ом", LEMMA: "ДХСС"},
	{ORTH: "ДХСС-у", LEMMA: "ДХСС"},
	{ORTH: "ДЦ-а", LEMMA: "ДЦ"},
	{ORTH: "ДЦ-ом", LEMMA: "ДЦ"},
	{ORTH: "ДЦ-у", LEMMA: "ДЦ"},
	{ORTH: "ДЦВ-а", LEMMA: "ДЦВ"},
	{ORTH: "ДЦВ-ом", LEMMA: "ДЦВ"},
	{ORTH: "ДЦВ-у", LEMMA: "ДЦВ"},
	{ORTH: "ДШБС-а", LEMMA: "ДШБС"},
	{ORTH: "ДШБС-ом", LEMMA: "ДШБС"},
	{ORTH: "ДШБС-у", LEMMA: "ДШБС"},
	{ORTH: "ЕАР-а", LEMMA: "ЕАР"},
	{ORTH: "ЕАР-ом", LEMMA: "ЕАР"},
	{ORTH: "ЕАР-у", LEMMA: "ЕАР"},
	{ORTH: "ЕАСО-а", LEMMA: "ЕАСО"},
	{ORTH: "ЕАСО-ом", LEMMA: "ЕАСО"},
	{ORTH: "ЕАСО-у", LEMMA: "ЕАСО"},
	{ORTH: "ЕБОП-а", LEMMA: "ЕБОП"},
	{ORTH: "ЕБОП-ом", LEMMA: "ЕБОП"},
	{ORTH: "ЕБОП-у", LEMMA: "ЕБОП"},
	{ORTH: "ЕБРД-а", LEMMA: "ЕБРД"},
	{ORTH: "ЕБРД-ом", LEMMA: "ЕБРД"},
	{ORTH: "ЕБРД-у", LEMMA: "ЕБРД"},
	{ORTH: "ЕБУ-а", LEMMA: "ЕБУ"},
	{ORTH: "ЕБУ-ом", LEMMA: "ЕБУ"},
	{ORTH: "ЕБУ-у", LEMMA: "ЕБУ"},
	{ORTH: "ЕВРОПОЛ-а", LEMMA: "ЕВРОПОЛ"},
	{ORTH: "ЕВРОПОЛ-ом", LEMMA: "ЕВРОПОЛ"},
	{ORTH: "ЕВРОПОЛ-у", LEMMA: "ЕВРОПОЛ"},
	{ORTH: "ЕВС-а", LEMMA: "ЕВС"},
	{ORTH: "ЕВС-ом", LEMMA: "ЕВС"},
	{ORTH: "ЕВС-у", LEMMA: "ЕВС"},
	{ORTH: "ЕДБ-а", LEMMA: "ЕДБ"},
	{ORTH: "ЕДБ-ом", LEMMA: "ЕДБ"},
	{ORTH: "ЕДБ-у", LEMMA: "ЕДБ"},
	{ORTH: "ЕЕАС-а", LEMMA: "ЕЕАС"},
	{ORTH: "ЕЕАС-ом", LEMMA: "ЕЕАС"},
	{ORTH: "ЕЕАС-у", LEMMA: "ЕЕАС"},
	{ORTH: "ЕЕЗ-а", LEMMA: "ЕЕЗ"},
	{ORTH: "ЕЕЗ-ом", LEMMA: "ЕЕЗ"},
	{ORTH: "ЕЕЗ-у", LEMMA: "ЕЕЗ"},
	{ORTH: "ЕЕП-а", LEMMA: "ЕЕП"},
	{ORTH: "ЕЕП-ом", LEMMA: "ЕЕП"},
	{ORTH: "ЕЕП-у", LEMMA: "ЕЕП"},
	{ORTH: "ЕЕС-а", LEMMA: "ЕЕС"},
	{ORTH: "ЕЕС-ом", LEMMA: "ЕЕС"},
	{ORTH: "ЕЕС-у", LEMMA: "ЕЕС"},
	{ORTH: "ЕИБ-а", LEMMA: "ЕИБ"},
	{ORTH: "ЕИБ-ом", LEMMA: "ЕИБ"},
	{ORTH: "ЕИБ-у", LEMMA: "ЕИБ"},
	{ORTH: "ЕИПА-е", LEMMA: "ЕИПА"},
	{ORTH: "ЕИПА-и", LEMMA: "ЕИПА"},
	{ORTH: "ЕИПА-ом", LEMMA: "ЕИПА"},
	{ORTH: "ЕИПА-у", LEMMA: "ЕИПА"},
	{ORTH: "ЕИФ-а", LEMMA: "ЕИФ"},
	{ORTH: "ЕИФ-ом", LEMMA: "ЕИФ"},
	{ORTH: "ЕИФ-у", LEMMA: "ЕИФ"},
	{ORTH: "Еј-Би-Си", LEMMA: "Еј-Би-Си", NORM:"АБЦ"},
	{ORTH: "Еј-Би-Сија", LEMMA: "Еј-Би-Си", NORM:"АБЦ-ја"},
	{ORTH: "Еј-Би-Сијем", LEMMA: "Еј-Би-Си", NORM:"АБЦ-јем"},
	{ORTH: "Еј-Би-Сију", LEMMA: "Еј-Би-Си", NORM:"АБЦ-ју"},
	{ORTH: "ЕЈТН-а", LEMMA: "ЕЈТН"},
	{ORTH: "ЕЈТН-ом", LEMMA: "ЕЈТН"},
	{ORTH: "ЕЈТН-у", LEMMA: "ЕЈТН"},
	{ORTH: "ЕКВ-а", LEMMA: "ЕКВ"},
	{ORTH: "ЕКВ-ом", LEMMA: "ЕКВ"},
	{ORTH: "ЕКВ-у", LEMMA: "ЕКВ"},
	{ORTH: "ЕКГ-а", LEMMA: "ЕКГ"},
	{ORTH: "ЕКГ-а", LEMMA: "ЕКГ"},
	{ORTH: "ЕКГ-ом", LEMMA: "ЕКГ"},
	{ORTH: "ЕКГ-ом", LEMMA: "ЕКГ"},
	{ORTH: "ЕКГ-у", LEMMA: "ЕКГ"},
	{ORTH: "ЕКГ-у", LEMMA: "ЕКГ"},
	{ORTH: "ЕКОСОЦ-а", LEMMA: "ЕКОСОЦ"},
	{ORTH: "ЕКОСОЦ-ом", LEMMA: "ЕКОСОЦ"},
	{ORTH: "ЕКОСОЦ-у", LEMMA: "ЕКОСОЦ"},
	{ORTH: "ЕКОФ-а", LEMMA: "ЕКОФ"},
	{ORTH: "ЕКОФ-ом", LEMMA: "ЕКОФ"},
	{ORTH: "ЕКОФ-у", LEMMA: "ЕКОФ"},
	{ORTH: "ЕЛСА-е", LEMMA: "ЕЛСА"},
	{ORTH: "ЕЛСА-и", LEMMA: "ЕЛСА"},
	{ORTH: "ЕЛСА-ом", LEMMA: "ЕЛСА"},
	{ORTH: "ЕЛСА-у", LEMMA: "ЕЛСА"},
	{ORTH: "ЕМС-а", LEMMA: "ЕМС"},
	{ORTH: "ЕМС-а", LEMMA: "ЕМС"},
	{ORTH: "ЕМС-ом", LEMMA: "ЕМС"},
	{ORTH: "ЕМС-ом", LEMMA: "ЕМС"},
	{ORTH: "ЕМС-у", LEMMA: "ЕМС"},
	{ORTH: "ЕМС-у", LEMMA: "ЕМС"},
	{ORTH: "ЕНИСА-е", LEMMA: "ЕНИСА"},
	{ORTH: "ЕНИСА-и", LEMMA: "ЕНИСА"},
	{ORTH: "ЕНИСА-ом", LEMMA: "ЕНИСА"},
	{ORTH: "ЕНИСА-у", LEMMA: "ЕНИСА"},
	{ORTH: "ЕОК-а", LEMMA: "ЕОК"},
	{ORTH: "ЕОК-ом", LEMMA: "ЕОК"},
	{ORTH: "ЕОК-у", LEMMA: "ЕОК"},
	{ORTH: "ЕП-а", LEMMA: "ЕП"},
	{ORTH: "ЕП-ом", LEMMA: "ЕП"},
	{ORTH: "ЕП-у", LEMMA: "ЕП"},
	{ORTH: "ЕПП-а", LEMMA: "ЕПП"},
	{ORTH: "ЕПП-ом", LEMMA: "ЕПП"},
	{ORTH: "ЕПП-у", LEMMA: "ЕПП"},
	{ORTH: "ЕПС-а", LEMMA: "ЕПС"},
	{ORTH: "ЕПС-ом", LEMMA: "ЕПС"},
	{ORTH: "ЕПС-у", LEMMA: "ЕПС"},
	{ORTH: "ЕСА-е", LEMMA: "ЕСА"},
	{ORTH: "ЕСА-и", LEMMA: "ЕСА"},
	{ORTH: "ЕСА-ом", LEMMA: "ЕСА"},
	{ORTH: "ЕСА-у", LEMMA: "ЕСА"},
	{ORTH: "ЕСДП-а", LEMMA: "ЕСДП"},
	{ORTH: "ЕСДП-ом", LEMMA: "ЕСДП"},
	{ORTH: "ЕСДП-у", LEMMA: "ЕСДП"},
	{ORTH: "ЕСЉП-а", LEMMA: "ЕСЉП"},
	{ORTH: "ЕСЉП-ом", LEMMA: "ЕСЉП"},
	{ORTH: "ЕСЉП-у", LEMMA: "ЕСЉП"},
	{ORTH: "ЕСМ-а", LEMMA: "ЕСМ"},
	{ORTH: "ЕСМ-ом", LEMMA: "ЕСМ"},
	{ORTH: "ЕСМ-у", LEMMA: "ЕСМ"},
	{ORTH: "ЕСП-а", LEMMA: "ЕСП"},
	{ORTH: "ЕСП-а", LEMMA: "ЕСП"},
	{ORTH: "ЕСП-ом", LEMMA: "ЕСП"},
	{ORTH: "ЕСП-ом", LEMMA: "ЕСП"},
	{ORTH: "ЕСП-у", LEMMA: "ЕСП"},
	{ORTH: "ЕСП-у", LEMMA: "ЕСП"},
	{ORTH: "ЕСПБ-а", LEMMA: "ЕСПБ"},
	{ORTH: "ЕСПБ-ом", LEMMA: "ЕСПБ"},
	{ORTH: "ЕСПБ-у", LEMMA: "ЕСПБ"},
	{ORTH: "ЕСЦ-а", LEMMA: "ЕСЦ"},
	{ORTH: "ЕСЦ-ом", LEMMA: "ЕСЦ"},
	{ORTH: "ЕСЦ-у", LEMMA: "ЕСЦ"},
	{ORTH: "ЕТ-а", LEMMA: "ЕТ"},
	{ORTH: "ЕТ-ом", LEMMA: "ЕТ"},
	{ORTH: "ЕТ-у", LEMMA: "ЕТ"},
	{ORTH: "ЕТА-е", LEMMA: "ЕТА"},
	{ORTH: "ЕТА-и", LEMMA: "ЕТА"},
	{ORTH: "ЕТА-ом", LEMMA: "ЕТА"},
	{ORTH: "ЕТА-у", LEMMA: "ЕТА"},
	{ORTH: "ЕТФ-а", LEMMA: "ЕТФ"},
	{ORTH: "ЕТФ-а", LEMMA: "ЕТФ"},
	{ORTH: "ЕТФ-ом", LEMMA: "ЕТФ"},
	{ORTH: "ЕТФ-ом", LEMMA: "ЕТФ"},
	{ORTH: "ЕТФ-у", LEMMA: "ЕТФ"},
	{ORTH: "ЕТФ-у", LEMMA: "ЕТФ"},
	{ORTH: "ЕТШ-а", LEMMA: "ЕТШ"},
	{ORTH: "ЕТШ-а", LEMMA: "ЕТШ"},
	{ORTH: "ЕТШ-ом", LEMMA: "ЕТШ"},
	{ORTH: "ЕТШ-ом", LEMMA: "ЕТШ"},
	{ORTH: "ЕТШ-у", LEMMA: "ЕТШ"},
	{ORTH: "ЕТШ-у", LEMMA: "ЕТШ"},
	{ORTH: "ЕУМЕТСАТ-а", LEMMA: "ЕУМЕТСАТ"},
	{ORTH: "ЕУМЕТСАТ-ом", LEMMA: "ЕУМЕТСАТ"},
	{ORTH: "ЕУМЕТСАТ-у", LEMMA: "ЕУМЕТСАТ"},
	{ORTH: "ЕУРАМЕТ-а", LEMMA: "ЕУРАМЕТ"},
	{ORTH: "ЕУРАМЕТ-ом", LEMMA: "ЕУРАМЕТ"},
	{ORTH: "ЕУРАМЕТ-у", LEMMA: "ЕУРАМЕТ"},
	{ORTH: "ЕУРАТОМ-а", LEMMA: "ЕУРАТОМ"},
	{ORTH: "ЕУРАТОМ-ом", LEMMA: "ЕУРАТОМ"},
	{ORTH: "ЕУРАТОМ-у", LEMMA: "ЕУРАТОМ"},
	{ORTH: "ЕУРОКОНТРОЛ-а", LEMMA: "ЕУРОКОНТРОЛ"},
	{ORTH: "ЕУРОКОНТРОЛ-ом", LEMMA: "ЕУРОКОНТРОЛ"},
	{ORTH: "ЕУРОКОНТРОЛ-у", LEMMA: "ЕУРОКОНТРОЛ"},
	{ORTH: "ЕУРОСАИ-ја", LEMMA: "ЕУРОСАИ"},
	{ORTH: "ЕУРОСАИ-јем", LEMMA: "ЕУРОСАИ"},
	{ORTH: "ЕУРОСАИ-ју", LEMMA: "ЕУРОСАИ"},
	{ORTH: "ЕУРОЦОНТРОЛ-а", LEMMA: "ЕУРОЦОНТРОЛ"},
	{ORTH: "ЕУРОЦОНТРОЛ-ом", LEMMA: "ЕУРОЦОНТРОЛ"},
	{ORTH: "ЕУРОЦОНТРОЛ-у", LEMMA: "ЕУРОЦОНТРОЛ"},
	{ORTH: "ЕФА-е", LEMMA: "ЕФА"},
	{ORTH: "ЕФА-е", LEMMA: "ЕФА"},
	{ORTH: "ЕФА-е", LEMMA: "ЕФА"},
	{ORTH: "ЕФА-и", LEMMA: "ЕФА"},
	{ORTH: "ЕФА-и", LEMMA: "ЕФА"},
	{ORTH: "ЕФА-и", LEMMA: "ЕФА"},
	{ORTH: "ЕФА-ом", LEMMA: "ЕФА"},
	{ORTH: "ЕФА-ом", LEMMA: "ЕФА"},
	{ORTH: "ЕФА-ом", LEMMA: "ЕФА"},
	{ORTH: "ЕФА-у", LEMMA: "ЕФА"},
	{ORTH: "ЕФА-у", LEMMA: "ЕФА"},
	{ORTH: "ЕФА-у", LEMMA: "ЕФА"},
	{ORTH: "ЕФИ-ја", LEMMA: "ЕФИ"},
	{ORTH: "ЕФИ-јем", LEMMA: "ЕФИ"},
	{ORTH: "ЕФИ-ју", LEMMA: "ЕФИ"},
	{ORTH: "ЕФСА-е", LEMMA: "ЕФСА"},
	{ORTH: "ЕФСА-и", LEMMA: "ЕФСА"},
	{ORTH: "ЕФСА-ом", LEMMA: "ЕФСА"},
	{ORTH: "ЕФСА-у", LEMMA: "ЕФСА"},
	{ORTH: "ЕФСФ-а", LEMMA: "ЕФСФ"},
	{ORTH: "ЕФСФ-ом", LEMMA: "ЕФСФ"},
	{ORTH: "ЕФСФ-у", LEMMA: "ЕФСФ"},
	{ORTH: "ЕФТА-е", LEMMA: "ЕФТА"},
	{ORTH: "ЕФТА-и", LEMMA: "ЕФТА"},
	{ORTH: "ЕФТА-ом", LEMMA: "ЕФТА"},
	{ORTH: "ЕФТА-у", LEMMA: "ЕФТА"},
	{ORTH: "ЕХФ-а", LEMMA: "ЕХФ"},
	{ORTH: "ЕХФ-ом", LEMMA: "ЕХФ"},
	{ORTH: "ЕХФ-у", LEMMA: "ЕХФ"},
	{ORTH: "ЕЦБ-а", LEMMA: "ЕЦБ"},
	{ORTH: "ЕЦБ-ом", LEMMA: "ЕЦБ"},
	{ORTH: "ЕЦБ-у", LEMMA: "ЕЦБ"},
	{ORTH: "ЕЦДЦ-а", LEMMA: "ЕЦДЦ"},
	{ORTH: "ЕЦДЦ-ом", LEMMA: "ЕЦДЦ"},
	{ORTH: "ЕЦДЦ-у", LEMMA: "ЕЦДЦ"},
	{ORTH: "ЕЦЈ-а", LEMMA: "ЕЦЈ"},
	{ORTH: "ЕЦЈ-ом", LEMMA: "ЕЦЈ"},
	{ORTH: "ЕЦЈ-у", LEMMA: "ЕЦЈ"},
	{ORTH: "ЕЦОСОЦ-а", LEMMA: "ЕЦОСОЦ"},
	{ORTH: "ЕЦОСОЦ-ом", LEMMA: "ЕЦОСОЦ"},
	{ORTH: "ЕЦОСОЦ-у", LEMMA: "ЕЦОСОЦ"},
	{ORTH: "ЕЦПД-а", LEMMA: "ЕЦПД"},
	{ORTH: "ЕЦПД-ом", LEMMA: "ЕЦПД"},
	{ORTH: "ЕЦПД-у", LEMMA: "ЕЦПД"},
	{ORTH: "ЕЦХР-а", LEMMA: "ЕЦХР"},
	{ORTH: "ЕЦХР-ом", LEMMA: "ЕЦХР"},
	{ORTH: "ЕЦХР-у", LEMMA: "ЕЦХР"},
	{ORTH: "ЖОЦ-а", LEMMA: "ЖОЦ"},
	{ORTH: "ЖОЦ-ом", LEMMA: "ЖОЦ"},
	{ORTH: "ЖОЦ-у", LEMMA: "ЖОЦ"},
	{ORTH: "ЖТП-а", LEMMA: "ЖТП"},
	{ORTH: "ЖТП-ом", LEMMA: "ЖТП"},
	{ORTH: "ЖТП-у", LEMMA: "ЖТП"},
	{ORTH: "ЗАПРОКУЛ-а", LEMMA: "ЗАПРОКУЛ"},
	{ORTH: "ЗАПРОКУЛ-ом", LEMMA: "ЗАПРОКУЛ"},
	{ORTH: "ЗАПРОКУЛ-у", LEMMA: "ЗАПРОКУЛ"},
	{ORTH: "ЗБОП-а", LEMMA: "ЗБОП"},
	{ORTH: "ЗБОП-ом", LEMMA: "ЗБОП"},
	{ORTH: "ЗБОП-у", LEMMA: "ЗБОП"},
	{ORTH: "ЗБС-а", LEMMA: "ЗБС"},
	{ORTH: "ЗБС-ом", LEMMA: "ЗБС"},
	{ORTH: "ЗБС-у", LEMMA: "ЗБС"},
	{ORTH: "ЗВКОВ-а", LEMMA: "ЗВКОВ"},
	{ORTH: "ЗВКОВ-ом", LEMMA: "ЗВКОВ"},
	{ORTH: "ЗВКОВ-у", LEMMA: "ЗВКОВ"},
	{ORTH: "ЗВО-а", LEMMA: "ЗВО"},
	{ORTH: "ЗВО-ом", LEMMA: "ЗВО"},
	{ORTH: "ЗВО-у", LEMMA: "ЗВО"},
	{ORTH: "ЗВП-а", LEMMA: "ЗВП"},
	{ORTH: "ЗВП-ом", LEMMA: "ЗВП"},
	{ORTH: "ЗВП-у", LEMMA: "ЗВП"},
	{ORTH: "ЗДС-а", LEMMA: "ЗДС"},
	{ORTH: "ЗДС-ом", LEMMA: "ЗДС"},
	{ORTH: "ЗДС-у", LEMMA: "ЗДС"},
	{ORTH: "ЗДУ-а", LEMMA: "ЗДУ"},
	{ORTH: "ЗДУ-ом", LEMMA: "ЗДУ"},
	{ORTH: "ЗДУ-у", LEMMA: "ЗДУ"},
	{ORTH: "ЗДФ-а", LEMMA: "ЗДФ"},
	{ORTH: "ЗДФ-ом", LEMMA: "ЗДФ"},
	{ORTH: "ЗДФ-у", LEMMA: "ЗДФ"},
	{ORTH: "ЗЕП-а", LEMMA: "ЗЕП"},
	{ORTH: "ЗЕП-ом", LEMMA: "ЗЕП"},
	{ORTH: "ЗЕП-у", LEMMA: "ЗЕП"},
	{ORTH: "ЗЕС-а", LEMMA: "ЗЕС"},
	{ORTH: "ЗЕС-а", LEMMA: "ЗЕС"},
	{ORTH: "ЗЕС-ом", LEMMA: "ЗЕС"},
	{ORTH: "ЗЕС-ом", LEMMA: "ЗЕС"},
	{ORTH: "ЗЕС-у", LEMMA: "ЗЕС"},
	{ORTH: "ЗЕС-у", LEMMA: "ЗЕС"},
	{ORTH: "ЗЗЈЗ-а", LEMMA: "ЗЗЈЗ"},
	{ORTH: "ЗЗЈЗ-ом", LEMMA: "ЗЗЈЗ"},
	{ORTH: "ЗЗЈЗ-у", LEMMA: "ЗЗЈЗ"},
	{ORTH: "ЗЗПЛ-а", LEMMA: "ЗЗПЛ"},
	{ORTH: "ЗЗПЛ-ом", LEMMA: "ЗЗПЛ"},
	{ORTH: "ЗЗПЛ-у", LEMMA: "ЗЗПЛ"},
	{ORTH: "ЗЗС-а", LEMMA: "ЗЗС"},
	{ORTH: "ЗЗС-ом", LEMMA: "ЗЗС"},
	{ORTH: "ЗЗС-у", LEMMA: "ЗЗС"},
	{ORTH: "ЗЗШ-а", LEMMA: "ЗЗШ"},
	{ORTH: "ЗЗШ-ом", LEMMA: "ЗЗШ"},
	{ORTH: "ЗЗШ-у", LEMMA: "ЗЗШ"},
	{ORTH: "ЗИКС-а", LEMMA: "ЗИКС"},
	{ORTH: "ЗИКС-ом", LEMMA: "ЗИКС"},
	{ORTH: "ЗИКС-у", LEMMA: "ЗИКС"},
	{ORTH: "ЗИН-а", LEMMA: "ЗИН"},
	{ORTH: "ЗИН-ом", LEMMA: "ЗИН"},
	{ORTH: "ЗИН-у", LEMMA: "ЗИН"},
	{ORTH: "ЗИС-а", LEMMA: "ЗИС"},
	{ORTH: "ЗИС-ом", LEMMA: "ЗИС"},
	{ORTH: "ЗИС-у", LEMMA: "ЗИС"},
	{ORTH: "ЗИФ-а", LEMMA: "ЗИФ"},
	{ORTH: "ЗИФ-ова", LEMMA: "ЗИФ"},
	{ORTH: "ЗИФ-ове", LEMMA: "ЗИФ"},
	{ORTH: "ЗИФ-ови", LEMMA: "ЗИФ"},
	{ORTH: "ЗИФ-овима", LEMMA: "ЗИФ"},
	{ORTH: "ЗИФ-ом", LEMMA: "ЗИФ"},
	{ORTH: "ЗИФ-у", LEMMA: "ЗИФ"},
	{ORTH: "ЗЈЗ-а", LEMMA: "ЗЈЗ"},
	{ORTH: "ЗЈЗ-ом", LEMMA: "ЗЈЗ"},
	{ORTH: "ЗЈЗ-у", LEMMA: "ЗЈЗ"},
	{ORTH: "ЗЈН-а", LEMMA: "ЗЈН"},
	{ORTH: "ЗЈН-ом", LEMMA: "ЗЈН"},
	{ORTH: "ЗЈН-у", LEMMA: "ЗЈН"},
	{ORTH: "ЗКП-а", LEMMA: "ЗКП"},
	{ORTH: "ЗКП-ом", LEMMA: "ЗКП"},
	{ORTH: "ЗКП-у", LEMMA: "ЗКП"},
	{ORTH: "ЗНД-а", LEMMA: "ЗНД"},
	{ORTH: "ЗНД-ом", LEMMA: "ЗНД"},
	{ORTH: "ЗНД-у", LEMMA: "ЗНД"},
	{ORTH: "ЗОБС-а", LEMMA: "ЗОБС"},
	{ORTH: "ЗОБС-ом", LEMMA: "ЗОБС"},
	{ORTH: "ЗОБС-у", LEMMA: "ЗОБС"},
	{ORTH: "ЗоИН-а", LEMMA: "ЗоИН"},
	{ORTH: "ЗОИН-а", LEMMA: "ЗОИН"},
	{ORTH: "ЗоИН-ом", LEMMA: "ЗоИН"},
	{ORTH: "ЗОИН-ом", LEMMA: "ЗОИН"},
	{ORTH: "ЗоИН-у", LEMMA: "ЗоИН"},
	{ORTH: "ЗОИН-у", LEMMA: "ЗОИН"},
	{ORTH: "ЗОО-а", LEMMA: "ЗОО"},
	{ORTH: "ЗОО-ом", LEMMA: "ЗОО"},
	{ORTH: "ЗОО-у", LEMMA: "ЗОО"},
	{ORTH: "ЗОП-а", LEMMA: "ЗОП"},
	{ORTH: "ЗОП-а", LEMMA: "ЗОП"},
	{ORTH: "ЗОП-а", LEMMA: "ЗОП"},
	{ORTH: "ЗОП-ом", LEMMA: "ЗОП"},
	{ORTH: "ЗОП-ом", LEMMA: "ЗОП"},
	{ORTH: "ЗОП-ом", LEMMA: "ЗОП"},
	{ORTH: "ЗОП-у", LEMMA: "ЗОП"},
	{ORTH: "ЗОП-у", LEMMA: "ЗОП"},
	{ORTH: "ЗОП-у", LEMMA: "ЗОП"},
	{ORTH: "ЗОСОВ-а", LEMMA: "ЗОСОВ"},
	{ORTH: "ЗОСОВ-ом", LEMMA: "ЗОСОВ"},
	{ORTH: "ЗОСОВ-у", LEMMA: "ЗОСОВ"},
	{ORTH: "ЗПП-а", LEMMA: "ЗПП"},
	{ORTH: "ЗПП-а", LEMMA: "ЗПП"},
	{ORTH: "ЗПП-ом", LEMMA: "ЗПП"},
	{ORTH: "ЗПП-ом", LEMMA: "ЗПП"},
	{ORTH: "ЗПП-у", LEMMA: "ЗПП"},
	{ORTH: "ЗПП-у", LEMMA: "ЗПП"},
	{ORTH: "ЗПУ-а", LEMMA: "ЗПУ"},
	{ORTH: "ЗПУ-ом", LEMMA: "ЗПУ"},
	{ORTH: "ЗПУ-у", LEMMA: "ЗПУ"},
	{ORTH: "ЗС-а", LEMMA: "ЗС"},
	{ORTH: "ЗС-а", LEMMA: "ЗС"},
	{ORTH: "ЗС-ом", LEMMA: "ЗС"},
	{ORTH: "ЗС-ом", LEMMA: "ЗС"},
	{ORTH: "ЗС-у", LEMMA: "ЗС"},
	{ORTH: "ЗС-у", LEMMA: "ЗС"},
	{ORTH: "ЗСБП-а", LEMMA: "ЗСБП"},
	{ORTH: "ЗСБП-ом", LEMMA: "ЗСБП"},
	{ORTH: "ЗСБП-у", LEMMA: "ЗСБП"},
	{ORTH: "ЗУДС-а", LEMMA: "ЗУДС"},
	{ORTH: "ЗУДС-ом", LEMMA: "ЗУДС"},
	{ORTH: "ЗУДС-у", LEMMA: "ЗУДС"},
	{ORTH: "ЗУНС-а", LEMMA: "ЗУНС"},
	{ORTH: "ЗУНС-ом", LEMMA: "ЗУНС"},
	{ORTH: "ЗУНС-у", LEMMA: "ЗУНС"},
	{ORTH: "ЗУОВ-а", LEMMA: "ЗУОВ"},
	{ORTH: "ЗУОВ-ом", LEMMA: "ЗУОВ"},
	{ORTH: "ЗУОВ-у", LEMMA: "ЗУОВ"},
	{ORTH: "ЗУР-а", LEMMA: "ЗУР"},
	{ORTH: "ЗУР-ом", LEMMA: "ЗУР"},
	{ORTH: "ЗУР-у", LEMMA: "ЗУР"},
	{ORTH: "ЗУС-а", LEMMA: "ЗУС"},
	{ORTH: "ЗУС-ом", LEMMA: "ЗУС"},
	{ORTH: "ЗУС-у", LEMMA: "ЗУС"},
	{ORTH: "ЗФППД-а", LEMMA: "ЗФППД"},
	{ORTH: "ЗФППД-ом", LEMMA: "ЗФППД"},
	{ORTH: "ЗФППД-у", LEMMA: "ЗФППД"},
	{ORTH: "ИАБ-а", LEMMA: "ИАБ"},
	{ORTH: "ИАБ-ом", LEMMA: "ИАБ"},
	{ORTH: "ИАБ-у", LEMMA: "ИАБ"},
	{ORTH: "ИАУС-а", LEMMA: "ИАУС"},
	{ORTH: "ИАУС-ом", LEMMA: "ИАУС"},
	{ORTH: "ИАУС-у", LEMMA: "ИАУС"},
	{ORTH: "ИБ-а", LEMMA: "ИБ"},
	{ORTH: "ИБ-ом", LEMMA: "ИБ"},
	{ORTH: "ИБ-у", LEMMA: "ИБ"},
	{ORTH: "ИБИСС-а", LEMMA: "ИБИСС"},
	{ORTH: "ИБИСС-ом", LEMMA: "ИБИСС"},
	{ORTH: "ИБИСС-у", LEMMA: "ИБИСС"},
	{ORTH: "ИБМ-а", LEMMA: "ИБМ"},
	{ORTH: "ИБМ-ом", LEMMA: "ИБМ"},
	{ORTH: "ИБМ-у", LEMMA: "ИБМ"},
	{ORTH: "ИД-а", LEMMA: "ИД"},
	{ORTH: "ИД-ом", LEMMA: "ИД"},
	{ORTH: "ИД-у", LEMMA: "ИД"},
	{ORTH: "ИДН-а", LEMMA: "ИДН"},
	{ORTH: "ИДН-ом", LEMMA: "ИДН"},
	{ORTH: "ИДН-у", LEMMA: "ИДН"},
	{ORTH: "ИДП-а", LEMMA: "ИДП"},
	{ORTH: "ИДП-ом", LEMMA: "ИДП"},
	{ORTH: "ИДП-у", LEMMA: "ИДП"},
	{ORTH: "ИДР-а", LEMMA: "ИДР"},
	{ORTH: "ИДР-ом", LEMMA: "ИДР"},
	{ORTH: "ИДР-у", LEMMA: "ИДР"},
	{ORTH: "ИЕП-а", LEMMA: "ИЕП"},
	{ORTH: "ИЕП-а", LEMMA: "ИЕП"},
	{ORTH: "ИЕП-а", LEMMA: "ИЕП"},
	{ORTH: "ИЕП-а", LEMMA: "ИЕП"},
	{ORTH: "ИЕП-ом", LEMMA: "ИЕП"},
	{ORTH: "ИЕП-ом", LEMMA: "ИЕП"},
	{ORTH: "ИЕП-ом", LEMMA: "ИЕП"},
	{ORTH: "ИЕП-ом", LEMMA: "ИЕП"},
	{ORTH: "ИЕП-у", LEMMA: "ИЕП"},
	{ORTH: "ИЕП-у", LEMMA: "ИЕП"},
	{ORTH: "ИЕП-у", LEMMA: "ИЕП"},
	{ORTH: "ИЕП-у", LEMMA: "ИЕП"},
	{ORTH: "ИЕС-а", LEMMA: "ИЕС"},
	{ORTH: "ИЕС-ом", LEMMA: "ИЕС"},
	{ORTH: "ИЕС-у", LEMMA: "ИЕС"},
	{ORTH: "ИЗБИС-а", LEMMA: "ИЗБИС"},
	{ORTH: "ИЗБИС-ом", LEMMA: "ИЗБИС"},
	{ORTH: "ИЗБИС-у", LEMMA: "ИЗБИС"},
	{ORTH: "ИЗИС-а", LEMMA: "ИЗИС"},
	{ORTH: "ИЗИС-ом", LEMMA: "ИЗИС"},
	{ORTH: "ИЗИС-у", LEMMA: "ИЗИС"},
	{ORTH: "ИЗЈЗ-а", LEMMA: "ИЗЈЗ"},
	{ORTH: "ИЗЈЗ-ом", LEMMA: "ИЗЈЗ"},
	{ORTH: "ИЗЈЗ-у", LEMMA: "ИЗЈЗ"},
	{ORTH: "ИЗС-а", LEMMA: "ИЗС"},
	{ORTH: "ИЗС-ом", LEMMA: "ИЗС"},
	{ORTH: "ИЗС-у", LEMMA: "ИЗС"},
	{ORTH: "ИЗуС-а", LEMMA: "ИЗуС"},
	{ORTH: "ИЗуС-ом", LEMMA: "ИЗуС"},
	{ORTH: "ИЗуС-у", LEMMA: "ИЗуС"},
	{ORTH: "ИЈЗ-а", LEMMA: "ИЈЗ"},
	{ORTH: "ИЈЗ-ом", LEMMA: "ИЈЗ"},
	{ORTH: "ИЈЗ-у", LEMMA: "ИЈЗ"},
	{ORTH: "ИКЛ-а", LEMMA: "ИКЛ"},
	{ORTH: "ИКЛ-ом", LEMMA: "ИКЛ"},
	{ORTH: "ИКЛ-у", LEMMA: "ИКЛ"},
	{ORTH: "ИКС-а", LEMMA: "ИКС"},
	{ORTH: "ИКС-ом", LEMMA: "ИКС"},
	{ORTH: "ИКС-у", LEMMA: "ИКС"},
	{ORTH: "ИКТ-а", LEMMA: "ИКТ"},
	{ORTH: "ИКТ-ом", LEMMA: "ИКТ"},
	{ORTH: "ИКТ-у", LEMMA: "ИКТ"},
	{ORTH: "ИКУМ-а", LEMMA: "ИКУМ"},
	{ORTH: "ИКУМ-ом", LEMMA: "ИКУМ"},
	{ORTH: "ИКУМ-у", LEMMA: "ИКУМ"},
	{ORTH: "ИМПП-а", LEMMA: "ИМПП"},
	{ORTH: "ИМПП-ом", LEMMA: "ИМПП"},
	{ORTH: "ИМПП-у", LEMMA: "ИМПП"},
	{ORTH: "ИМР-а", LEMMA: "ИМР"},
	{ORTH: "ИМР-ом", LEMMA: "ИМР"},
	{ORTH: "ИМР-у", LEMMA: "ИМР"},
	{ORTH: "ИМС-а", LEMMA: "ИМС"},
	{ORTH: "ИМС-а", LEMMA: "ИМС"},
	{ORTH: "ИМС-ом", LEMMA: "ИМС"},
	{ORTH: "ИМС-ом", LEMMA: "ИМС"},
	{ORTH: "ИМС-у", LEMMA: "ИМС"},
	{ORTH: "ИМС-у", LEMMA: "ИМС"},
	{ORTH: "ИМТ-а", LEMMA: "ИМТ"},
	{ORTH: "ИМТ-ом", LEMMA: "ИМТ"},
	{ORTH: "ИМТ-у", LEMMA: "ИМТ"},
	{ORTH: "ИМУС-а", LEMMA: "ИМУС"},
	{ORTH: "ИМУС-ом", LEMMA: "ИМУС"},
	{ORTH: "ИМУС-у", LEMMA: "ИМУС"},
	{ORTH: "ИНА-е", LEMMA: "ИНА"},
	{ORTH: "ИНА-и", LEMMA: "ИНА"},
	{ORTH: "ИНА-ом", LEMMA: "ИНА"},
	{ORTH: "ИНА-у", LEMMA: "ИНА"},
	{ORTH: "ИНИС-а", LEMMA: "ИНИС"},
	{ORTH: "ИНИС-а", LEMMA: "ИНИС"},
	{ORTH: "ИНИС-ом", LEMMA: "ИНИС"},
	{ORTH: "ИНИС-ом", LEMMA: "ИНИС"},
	{ORTH: "ИНИС-у", LEMMA: "ИНИС"},
	{ORTH: "ИНИС-у", LEMMA: "ИНИС"},
	{ORTH: "ИОП-а", LEMMA: "ИОП"},
	{ORTH: "ИОП-ом", LEMMA: "ИОП"},
	{ORTH: "ИОП-у", LEMMA: "ИОП"},
	{ORTH: "ИОРС-а", LEMMA: "ИОРС"},
	{ORTH: "ИОРС-ом", LEMMA: "ИОРС"},
	{ORTH: "ИОРС-у", LEMMA: "ИОРС"},
	{ORTH: "ИПАП-а", LEMMA: "ИПАП"},
	{ORTH: "ИПАП-ом", LEMMA: "ИПАП"},
	{ORTH: "ИПАП-у", LEMMA: "ИПАП"},
	{ORTH: "ИПАРД-а", LEMMA: "ИПАРД"},
	{ORTH: "ИПАРД-ом", LEMMA: "ИПАРД"},
	{ORTH: "ИПАРД-у", LEMMA: "ИПАРД"},
	{ORTH: "ИПИ-ја", LEMMA: "ИПИ"},
	{ORTH: "ИПИ-јем", LEMMA: "ИПИ"},
	{ORTH: "ИПИ-ју", LEMMA: "ИПИ"},
	{ORTH: "ИПН-а", LEMMA: "ИПН"},
	{ORTH: "ИПН-ом", LEMMA: "ИПН"},
	{ORTH: "ИПН-у", LEMMA: "ИПН"},
	{ORTH: "ИПС-а", LEMMA: "ИПС"},
	{ORTH: "ИПС-ом", LEMMA: "ИПС"},
	{ORTH: "ИПС-у", LEMMA: "ИПС"},
	{ORTH: "ИПЦ-а", LEMMA: "ИПЦ"},
	{ORTH: "ИПЦ-ом", LEMMA: "ИПЦ"},
	{ORTH: "ИПЦ-у", LEMMA: "ИПЦ"},
	{ORTH: "ИРА-е", LEMMA: "ИРА"},
	{ORTH: "ИРА-и", LEMMA: "ИРА"},
	{ORTH: "ИРА-ом", LEMMA: "ИРА"},
	{ORTH: "ИРА-у", LEMMA: "ИРА"},
	{ORTH: "ИРК-а", LEMMA: "ИРК"},
	{ORTH: "ИРК-ом", LEMMA: "ИРК"},
	{ORTH: "ИРК-у", LEMMA: "ИРК"},
	{ORTH: "ИСДАКОН-а", LEMMA: "ИСДАКОН"},
	{ORTH: "ИСДАКОН-ом", LEMMA: "ИСДАКОН"},
	{ORTH: "ИСДАКОН-у", LEMMA: "ИСДАКОН"},
	{ORTH: "ИСДАЦОН-а", LEMMA: "ИСДАЦОН"},
	{ORTH: "ИСДАЦОН-ом", LEMMA: "ИСДАЦОН"},
	{ORTH: "ИСДАЦОН-у", LEMMA: "ИСДАЦОН"},
	{ORTH: "ИСЕМ-а", LEMMA: "ИСЕМ"},
	{ORTH: "ИСЕМ-ом", LEMMA: "ИСЕМ"},
	{ORTH: "ИСЕМ-у", LEMMA: "ИСЕМ"},
	{ORTH: "ИСИ-ја", LEMMA: "ИСИ"},
	{ORTH: "ИСИ-ја", LEMMA: "ИСИ"},
	{ORTH: "ИСИ-јем", LEMMA: "ИСИ"},
	{ORTH: "ИСИ-јем", LEMMA: "ИСИ"},
	{ORTH: "ИСИ-ју", LEMMA: "ИСИ"},
	{ORTH: "ИСИ-ју", LEMMA: "ИСИ"},
	{ORTH: "ИСИБ-а", LEMMA: "ИСИБ"},
	{ORTH: "ИСИБ-ом", LEMMA: "ИСИБ"},
	{ORTH: "ИСИБ-у", LEMMA: "ИСИБ"},
	{ORTH: "ИСИС-а", LEMMA: "ИСИС"},
	{ORTH: "ИСИС-ом", LEMMA: "ИСИС"},
	{ORTH: "ИСИС-у", LEMMA: "ИСИС"},
	{ORTH: "ИСМ-а", LEMMA: "ИСМ"},
	{ORTH: "ИСМ-ом", LEMMA: "ИСМ"},
	{ORTH: "ИСМ-у", LEMMA: "ИСМ"},
	{ORTH: "ИСС-а", LEMMA: "ИСС"},
	{ORTH: "ИСС-ом", LEMMA: "ИСС"},
	{ORTH: "ИСС-у", LEMMA: "ИСС"},
	{ORTH: "ИТ-ја", LEMMA: "ИТ"},
	{ORTH: "ИТ-јем", LEMMA: "ИТ"},
	{ORTH: "ИТ-ју", LEMMA: "ИТ"},
	{ORTH: "ИТМ-а", LEMMA: "ИТМ"},
	{ORTH: "ИТМ-ом", LEMMA: "ИТМ"},
	{ORTH: "ИТМ-у", LEMMA: "ИТМ"},
	{ORTH: "ИУП-а", LEMMA: "ИУП"},
	{ORTH: "ИУП-ом", LEMMA: "ИУП"},
	{ORTH: "ИУП-у", LEMMA: "ИУП"},
	{ORTH: "ИХТМ-а", LEMMA: "ИХТМ"},
	{ORTH: "ИХТМ-ом", LEMMA: "ИХТМ"},
	{ORTH: "ИХТМ-у", LEMMA: "ИХТМ"},
	{ORTH: "ИЦБЦ-а", LEMMA: "ИЦБЦ"},
	{ORTH: "ИЦБЦ-ом", LEMMA: "ИЦБЦ"},
	{ORTH: "ИЦБЦ-у", LEMMA: "ИЦБЦ"},
	{ORTH: "ИЦЕФ-а", LEMMA: "ИЦЕФ"},
	{ORTH: "ИЦЕФ-ом", LEMMA: "ИЦЕФ"},
	{ORTH: "ИЦЕФ-у", LEMMA: "ИЦЕФ"},
	{ORTH: "ИЦТ-а", LEMMA: "ИЦТ"},
	{ORTH: "ИЦТ-ом", LEMMA: "ИЦТ"},
	{ORTH: "ИЦТ-у", LEMMA: "ИЦТ"},
	{ORTH: "ЈАЗАС-а", LEMMA: "ЈАЗАС"},
	{ORTH: "ЈАЗАС-ом", LEMMA: "ЈАЗАС"},
	{ORTH: "ЈАЗАС-у", LEMMA: "ЈАЗАС"},
	{ORTH: "ЈАТ-а", LEMMA: "ЈАТ"},
	{ORTH: "ЈАТ-ом", LEMMA: "ЈАТ"},
	{ORTH: "ЈАТ-у", LEMMA: "ЈАТ"},
	{ORTH: "ЈВП-а", LEMMA: "ЈВП"},
	{ORTH: "ЈВП-ом", LEMMA: "ЈВП"},
	{ORTH: "ЈВП-у", LEMMA: "ЈВП"},
	{ORTH: "ЈГС-а", LEMMA: "ЈГС"},
	{ORTH: "ЈГС-ом", LEMMA: "ЈГС"},
	{ORTH: "ЈГС-у", LEMMA: "ЈГС"},
	{ORTH: "ЈДП-а", LEMMA: "ЈДП"},
	{ORTH: "ЈДП-ом", LEMMA: "ЈДП"},
	{ORTH: "ЈДП-у", LEMMA: "ЈДП"},
	{ORTH: "ЈДС-а", LEMMA: "ЈДС"},
	{ORTH: "ЈДС-ом", LEMMA: "ЈДС"},
	{ORTH: "ЈДС-у", LEMMA: "ЈДС"},
	{ORTH: "ЈИСП-а", LEMMA: "ЈИСП"},
	{ORTH: "ЈИСП-ом", LEMMA: "ЈИСП"},
	{ORTH: "ЈИСП-у", LEMMA: "ЈИСП"},
	{ORTH: "ЈИЦА-е", LEMMA: "ЈИЦА"},
	{ORTH: "ЈИЦА-и", LEMMA: "ЈИЦА"},
	{ORTH: "ЈИЦА-ом", LEMMA: "ЈИЦА"},
	{ORTH: "ЈИЦА-у", LEMMA: "ЈИЦА"},
	{ORTH: "ЈКП-а", LEMMA: "ЈКП"},
	{ORTH: "ЈКП-ом", LEMMA: "ЈКП"},
	{ORTH: "ЈКП-у", LEMMA: "ЈКП"},
	{ORTH: "ЈКРВ-а", LEMMA: "ЈКРВ"},
	{ORTH: "ЈКРВ-ом", LEMMA: "ЈКРВ"},
	{ORTH: "ЈКРВ-у", LEMMA: "ЈКРВ"},
	{ORTH: "ЈЛЗ-а", LEMMA: "ЈЛЗ"},
	{ORTH: "ЈЛЗ-ом", LEMMA: "ЈЛЗ"},
	{ORTH: "ЈЛЗ-у", LEMMA: "ЈЛЗ"},
	{ORTH: "ЈМБГ-а", LEMMA: "ЈМБГ"},
	{ORTH: "ЈМБГ-ом", LEMMA: "ЈМБГ"},
	{ORTH: "ЈМБГ-у", LEMMA: "ЈМБГ"},
	{ORTH: "ЈНОФ-а", LEMMA: "ЈНОФ"},
	{ORTH: "ЈНОФ-ом", LEMMA: "ЈНОФ"},
	{ORTH: "ЈНОФ-у", LEMMA: "ЈНОФ"},
	{ORTH: "ЈНС-а", LEMMA: "ЈНС"},
	{ORTH: "ЈНС-ом", LEMMA: "ЈНС"},
	{ORTH: "ЈНС-у", LEMMA: "ЈНС"},
	{ORTH: "ЈОБ-а", LEMMA: "ЈОБ"},
	{ORTH: "ЈОБ-а", LEMMA: "ЈОБ"},
	{ORTH: "ЈОБ-ом", LEMMA: "ЈОБ"},
	{ORTH: "ЈОБ-ом", LEMMA: "ЈОБ"},
	{ORTH: "ЈОБ-у", LEMMA: "ЈОБ"},
	{ORTH: "ЈОБ-у", LEMMA: "ЈОБ"},
	{ORTH: "ЈОК-а", LEMMA: "ЈОК"},
	{ORTH: "ЈОК-ом", LEMMA: "ЈОК"},
	{ORTH: "ЈОК-у", LEMMA: "ЈОК"},
	{ORTH: "ЈП-а", LEMMA: "ЈП"},
	{ORTH: "ЈП-ом", LEMMA: "ЈП"},
	{ORTH: "ЈП-у", LEMMA: "ЈП"},
	{ORTH: "ЈПП-а", LEMMA: "ЈПП"},
	{ORTH: "ЈПП-ом", LEMMA: "ЈПП"},
	{ORTH: "ЈПП-у", LEMMA: "ЈПП"},
	{ORTH: "ЈРБ-а", LEMMA: "ЈРБ"},
	{ORTH: "ЈРБ-ом", LEMMA: "ЈРБ"},
	{ORTH: "ЈРБ-у", LEMMA: "ЈРБ"},
	{ORTH: "ЈРЗ-а", LEMMA: "ЈРЗ"},
	{ORTH: "ЈРЗ-ом", LEMMA: "ЈРЗ"},
	{ORTH: "ЈРЗ-у", LEMMA: "ЈРЗ"},
	{ORTH: "ЈРМ-а", LEMMA: "ЈРМ"},
	{ORTH: "ЈРМ-ом", LEMMA: "ЈРМ"},
	{ORTH: "ЈРМ-у", LEMMA: "ЈРМ"},
	{ORTH: "ЈРС-а", LEMMA: "ЈРС"},
	{ORTH: "ЈРС-ом", LEMMA: "ЈРС"},
	{ORTH: "ЈРС-у", LEMMA: "ЈРС"},
	{ORTH: "ЈС-а", LEMMA: "ЈС"},
	{ORTH: "ЈС-ом", LEMMA: "ЈС"},
	{ORTH: "ЈС-у", LEMMA: "ЈС"},
	{ORTH: "ЈСПН-а", LEMMA: "ЈСПН"},
	{ORTH: "ЈСПН-ом", LEMMA: "ЈСПН"},
	{ORTH: "ЈСПН-у", LEMMA: "ЈСПН"},
	{ORTH: "ЈУЛ-а", LEMMA: "ЈУЛ"},
	{ORTH: "ЈУЛ-ом", LEMMA: "ЈУЛ"},
	{ORTH: "ЈУЛ-у", LEMMA: "ЈУЛ"},
	{ORTH: "ЈУНИС-а", LEMMA: "ЈУНИС"},
	{ORTH: "ЈУНИС-ом", LEMMA: "ЈУНИС"},
	{ORTH: "ЈУНИС-у", LEMMA: "ЈУНИС"},
	{ORTH: "ЈУС-а", LEMMA: "ЈУС"},
	{ORTH: "ЈУС-ом", LEMMA: "ЈУС"},
	{ORTH: "ЈУС-у", LEMMA: "ЈУС"},
	{ORTH: "ЛЕАДЕР-а", LEMMA: "ЛЕАДЕР"},
	{ORTH: "ЛЕАДЕР-ом", LEMMA: "ЛЕАДЕР"},
	{ORTH: "ЛЕАДЕР-у", LEMMA: "ЛЕАДЕР"},
	{ORTH: "МЕРС-а", LEMMA: "МЕРС"},
	{ORTH: "МЕРС-ом", LEMMA: "МЕРС"},
	{ORTH: "МЕРС-у", LEMMA: "МЕРС"},
	{ORTH: "ОЛАФ-а", LEMMA: "ОЛАФ"},
	{ORTH: "ОЛАФ-ом", LEMMA: "ОЛАФ"},
	{ORTH: "ОЛАФ-у", LEMMA: "ОЛАФ"},
	{ORTH: "РАИ-ја", LEMMA: "РАИ"},
	{ORTH: "РАИ-јем", LEMMA: "РАИ"},
	{ORTH: "РАИ-ју", LEMMA: "РАИ"},
	{ORTH: "СЕД-а", LEMMA: "СЕД"},
	{ORTH: "СЕД-ом", LEMMA: "СЕД"},
	{ORTH: "СЕД-у", LEMMA: "СЕД"},
	{ORTH: "СЕЦО-а", LEMMA: "СЕЦО"},
	{ORTH: "СЕЦО-ом", LEMMA: "СЕЦО"},
	{ORTH: "СЕЦО-у", LEMMA: "СЕЦО"},
	{ORTH: "СИЕПА-е", LEMMA: "СИЕПА"},
	{ORTH: "СИЕПА-и", LEMMA: "СИЕПА"},
	{ORTH: "СИЕПА-ом", LEMMA: "СИЕПА"},
	{ORTH: "СИЕПА-у", LEMMA: "СИЕПА"},
	{ORTH: "СИЛК-а", LEMMA: "СИЛК"},
	{ORTH: "СИЛК-ом", LEMMA: "СИЛК"},
	{ORTH: "СИЛК-у", LEMMA: "СИЛК"},
	{ORTH: "СИЛЦ-а", LEMMA: "СИЛЦ"},
	{ORTH: "СИЛЦ-ом", LEMMA: "СИЛЦ"},
	{ORTH: "СИЛЦ-у", LEMMA: "СИЛЦ"},
	{ORTH: "СИПА-е", LEMMA: "СИПА"},
	{ORTH: "СИПА-и", LEMMA: "СИПА"},
	{ORTH: "СИПА-ом", LEMMA: "СИПА"},
	{ORTH: "СИПА-у", LEMMA: "СИПА"},
	{ORTH: "УНАИДС-а", LEMMA: "УНАИДС"},
	{ORTH: "УНАИДС-ом", LEMMA: "УНАИДС"},
	{ORTH: "УНАИДС-у", LEMMA: "УНАИДС"},
	{ORTH: "УНЕЦЕ-а", LEMMA: "УНЕЦЕ"},
	{ORTH: "УНЕЦЕ-ом", LEMMA: "УНЕЦЕ"},
	{ORTH: "УНЕЦЕ-у", LEMMA: "УНЕЦЕ"},
	{ORTH: "УНИЦЕФ-а", LEMMA: "УНИЦЕФ"},
	{ORTH: "УНИЦЕФ-ом", LEMMA: "УНИЦЕФ"},
	{ORTH: "УНИЦЕФ-у", LEMMA: "УНИЦЕФ"},
	{ORTH: "УНПРОФОР-а", LEMMA: "УНПРОФОР"},
	{ORTH: "УНПРОФОР-ом", LEMMA: "УНПРОФОР"},
	{ORTH: "УНПРОФОР-у", LEMMA: "УНПРОФОР"},
	{ORTH: "УНХЦР-а", LEMMA: "УНХЦР"},
	{ORTH: "УНХЦР-ом", LEMMA: "УНХЦР"},
	{ORTH: "УНХЦР-у", LEMMA: "УНХЦР"},
	{ORTH: "УРИ-ја", LEMMA: "УРИ"},
	{ORTH: "УРИ-јем", LEMMA: "УРИ"},
	{ORTH: "УРИ-ју", LEMMA: "УРИ"},
	{ORTH: "УРЛ-а", LEMMA: "УРЛ"},
	{ORTH: "УРЛ-ом", LEMMA: "УРЛ"},
	{ORTH: "УРЛ-у", LEMMA: "УРЛ"},
	{ORTH: "УСАИД-а", LEMMA: "УСАИД"},
	{ORTH: "УСАИД-ом", LEMMA: "УСАИД"},
	{ORTH: "УСАИД-у", LEMMA: "УСАИД"},
	{ORTH: "ФЕСТ-а", LEMMA: "ФЕСТ"},
	{ORTH: "ФЕСТ-ом", LEMMA: "ФЕСТ"},
	{ORTH: "ФЕСТ-у", LEMMA: "ФЕСТ"},
	{ORTH: "ФИАТ-а", LEMMA: "ФИАТ"},
	{ORTH: "ФИАТ-ом", LEMMA: "ФИАТ"},
	{ORTH: "ФИАТ-у", LEMMA: "ФИАТ"},
	{ORTH: "ФМИС-а", LEMMA: "ФМИС"},
	{ORTH: "ФМИС-ом", LEMMA: "ФМИС"},
	{ORTH: "ФМИС-у", LEMMA: "ФМИС"},
	{ORTH: "ФРОНТЕКС-а", LEMMA: "ФРОНТЕКС"},
	{ORTH: "ФРОНТЕКС-ом", LEMMA: "ФРОНТЕКС"},
	{ORTH: "ФРОНТЕКС-у", LEMMA: "ФРОНТЕКС"},
	{ORTH: "ХИВ-а", LEMMA: "ХИВ"},
	{ORTH: "ХИВ-ом", LEMMA: "ХИВ"},
	{ORTH: "ХИВ-у", LEMMA: "ХИВ"},
	{ORTH: "ЦАП-а", LEMMA: "ЦАП"},
	{ORTH: "ЦАП-ом", LEMMA: "ЦАП"},
	{ORTH: "ЦАП-у", LEMMA: "ЦАП"},
	{ORTH: "ЦДХН-а", LEMMA: "ЦДХН"},
	{ORTH: "ЦДХН-ом", LEMMA: "ЦДХН"},
	{ORTH: "ЦДХН-у", LEMMA: "ЦДХН"},
	{ORTH: "ЦЕВ-а", LEMMA: "ЦЕВ"},
	{ORTH: "ЦЕВ-ом", LEMMA: "ЦЕВ"},
	{ORTH: "ЦЕВ-у", LEMMA: "ЦЕВ"},
	{ORTH: "ЦЕН-а", LEMMA: "ЦЕН"},
	{ORTH: "ЦЕН-ом", LEMMA: "ЦЕН"},
	{ORTH: "ЦЕН-у", LEMMA: "ЦЕН"},
	{ORTH: "ЦЕНЕЛЕЦ-а", LEMMA: "ЦЕНЕЛЕЦ"},
	{ORTH: "ЦЕНЕЛЕЦ-ом", LEMMA: "ЦЕНЕЛЕЦ"},
	{ORTH: "ЦЕНЕЛЕЦ-у", LEMMA: "ЦЕНЕЛЕЦ"},
	{ORTH: "ЦЕПОЛ-а", LEMMA: "ЦЕПОЛ"},
	{ORTH: "ЦЕПОЛ-ом", LEMMA: "ЦЕПОЛ"},
	{ORTH: "ЦЕПОЛ-у", LEMMA: "ЦЕПОЛ"},
	{ORTH: "ЦЕРН-а", LEMMA: "ЦЕРН"},
	{ORTH: "ЦЕРН-ом", LEMMA: "ЦЕРН"},
	{ORTH: "ЦЕРН-у", LEMMA: "ЦЕРН"},
	{ORTH: "ЦЕРП-а", LEMMA: "ЦЕРП"},
	{ORTH: "ЦЕРП-ом", LEMMA: "ЦЕРП"},
	{ORTH: "ЦЕРП-у", LEMMA: "ЦЕРП"},
	{ORTH: "ЦПИ-ја", LEMMA: "ЦПИ"},
	{ORTH: "ЦПИ-јем", LEMMA: "ЦПИ"},
	{ORTH: "ЦПИ-ју", LEMMA: "ЦПИ"},
	{ORTH: "џи-ес-ем", LEMMA: "џи-ес-ем", NORM:"ГСМ"},
	{ORTH: "џи-ес-ема", LEMMA: "џи-ес-ем", NORM:"ГСМ-а"},
	{ORTH: "џи-ес-емом", LEMMA: "џи-ес-ем", NORM:"ГСМ-ом"},
	{ORTH: "џи-ес-ему", LEMMA: "џи-ес-ем", NORM:"ГСМ-у"},
	{ORTH: "ABAF-а", LEMMA: "ABAF", NORM:"АБАФ-а"},
	{ORTH: "ABAF-ом", LEMMA: "ABAF", NORM:"АБАФ-ом"},
	{ORTH: "ABAF-у", LEMMA: "ABAF", NORM:"АБАФ-у"},
	{ORTH: "ABC-ја", LEMMA: "ABC", NORM:"АБЦ-ја"},
	{ORTH: "ABC-јем", LEMMA: "ABC", NORM:"АБЦ-јем"},
	{ORTH: "ABC-ју", LEMMA: "ABC", NORM:"АБЦ-ју"},
	{ORTH: "ABS-а", LEMMA: "ABS", NORM:"АБС-а"},
	{ORTH: "ABS-ом", LEMMA: "ABS", NORM:"АБС-ом"},
	{ORTH: "ABS-у", LEMMA: "ABS", NORM:"АБС-у"},
	{ORTH: "ADP-а", LEMMA: "ADP", NORM:"АДП-а"},
	{ORTH: "ADP-ом", LEMMA: "ADP", NORM:"АДП-ом"},
	{ORTH: "ADP-у", LEMMA: "ADP", NORM:"АДП-у"},
	{ORTH: "AMP-а", LEMMA: "AMP", NORM:"АМП-а"},
	{ORTH: "AMP-ом", LEMMA: "AMP", NORM:"АМП-ом"},
	{ORTH: "AMP-у", LEMMA: "AMP", NORM:"АМП-у"},
	{ORTH: "ASEAN-а", LEMMA: "ASEAN", NORM:"АСЕАН-а"},
	{ORTH: "ASEAN-ом", LEMMA: "ASEAN", NORM:"АСЕАН-ом"},
	{ORTH: "ASEAN-у", LEMMA: "ASEAN", NORM:"АСЕАН-у"},
	{ORTH: "ATP-а", LEMMA: "ATP", NORM:"АТП-а"},
	{ORTH: "ATP-а", LEMMA: "ATP", NORM:"АТП-а"},
	{ORTH: "ATP-ом", LEMMA: "ATP", NORM:"АТП-ом"},
	{ORTH: "ATP-ом", LEMMA: "ATP", NORM:"АТП-ом"},
	{ORTH: "ATP-у", LEMMA: "ATP", NORM:"АТП-у"},
	{ORTH: "ATP-у", LEMMA: "ATP", NORM:"АТП-у"},
	{ORTH: "BBC-ја", LEMMA: "BBC", NORM:"ББЦ-ја"},
	{ORTH: "BBC-јем", LEMMA: "BBC", NORM:"ББЦ-јем"},
	{ORTH: "BBC-ју", LEMMA: "BBC", NORM:"ББЦ-ју"},
	{ORTH: "BIRN-а", LEMMA: "BIRN", NORM:"БИРН-а"},
	{ORTH: "BIRN-ом", LEMMA: "BIRN", NORM:"БИРН-ом"},
	{ORTH: "BIRN-у", LEMMA: "BIRN", NORM:"БИРН-у"},
	{ORTH: "BIS-а", LEMMA: "BIS", NORM:"БИС-а"},
	{ORTH: "BIS-ом", LEMMA: "BIS", NORM:"БИС-ом"},
	{ORTH: "BIS-у", LEMMA: "BIS", NORM:"БИС-у"},
	{ORTH: "BRIC-а", LEMMA: "BRIC", NORM:"БРИЦ-а"},
	{ORTH: "BRIC-ом", LEMMA: "BRIC", NORM:"БРИЦ-ом"},
	{ORTH: "BRIC-у", LEMMA: "BRIC", NORM:"БРИЦ-у"},
	{ORTH: "BRICS-а", LEMMA: "BRICS", NORM:"БРИЦС-а"},
	{ORTH: "BRICS-ом", LEMMA: "BRICS", NORM:"БРИЦС-ом"},
	{ORTH: "BRICS-у", LEMMA: "BRICS", NORM:"БРИЦС-у"},
	{ORTH: "CAP-а", LEMMA: "CAP", NORM:"ЦАП-а"},
	{ORTH: "CAP-ом", LEMMA: "CAP", NORM:"ЦАП-ом"},
	{ORTH: "CAP-у", LEMMA: "CAP", NORM:"ЦАП-у"},
	{ORTH: "CEN-а", LEMMA: "CEN", NORM:"ЦЕН-а"},
	{ORTH: "CEN-ом", LEMMA: "CEN", NORM:"ЦЕН-ом"},
	{ORTH: "CEN-у", LEMMA: "CEN", NORM:"ЦЕН-у"},
	{ORTH: "CENELEC-а", LEMMA: "CENELEC", NORM:"ЦЕНЕЛЕЦ-а"},
	{ORTH: "CENELEC-ом", LEMMA: "CENELEC", NORM:"ЦЕНЕЛЕЦ-ом"},
	{ORTH: "CENELEC-у", LEMMA: "CENELEC", NORM:"ЦЕНЕЛЕЦ-у"},
	{ORTH: "CEPOL-а", LEMMA: "CEPOL", NORM:"ЦЕПОЛ-а"},
	{ORTH: "CEPOL-ом", LEMMA: "CEPOL", NORM:"ЦЕПОЛ-ом"},
	{ORTH: "CEPOL-у", LEMMA: "CEPOL", NORM:"ЦЕПОЛ-у"},
	{ORTH: "CERN-а", LEMMA: "CERN", NORM:"ЦЕРН-а"},
	{ORTH: "CERN-ом", LEMMA: "CERN", NORM:"ЦЕРН-ом"},
	{ORTH: "CERN-у", LEMMA: "CERN", NORM:"ЦЕРН-у"},
	{ORTH: "CERP-а", LEMMA: "CERP", NORM:"ЦЕРП-а"},
	{ORTH: "CERP-ом", LEMMA: "CERP", NORM:"ЦЕРП-ом"},
	{ORTH: "CERP-у", LEMMA: "CERP", NORM:"ЦЕРП-у"},
	{ORTH: "CPI-ја", LEMMA: "CPI", NORM:"ЦПИ-ја"},
	{ORTH: "CPI-јем", LEMMA: "CPI", NORM:"ЦПИ-јем"},
	{ORTH: "CPI-ју", LEMMA: "CPI", NORM:"ЦПИ-ј"},
	{ORTH: "DDT-ја", LEMMA: "DDT", NORM:"ДДТ-ја"},
	{ORTH: "DDT-јем", LEMMA: "DDT", NORM:"ДДТ-јем"},
	{ORTH: "DDT-ју", LEMMA: "DDT", NORM:"ДДТ-ју"},
	{ORTH: "DJ-а", LEMMA: "DJ", NORM:"ДЈ-а"},
	{ORTH: "DJ-ева", LEMMA: "DJ", NORM:"ДЈ-ева"},
	{ORTH: "DJ-еве", LEMMA: "DJ", NORM:"ДЈ-еве"},
	{ORTH: "DJ-еви", LEMMA: "DJ", NORM:"ДЈ-еви"},
	{ORTH: "DJ-евима", LEMMA: "DJ", NORM:"ДЈ-евима"},
	{ORTH: "DJ-ем", LEMMA: "DJ", NORM:"ДЈ-ем"},
	{ORTH: "DJ-у", LEMMA: "DJ", NORM:"ДЈ-у"},
	{ORTH: "DVD-а", LEMMA: "DVD", NORM:"ДВД-а"},
	{ORTH: "DVD-а", LEMMA: "DVD", NORM:"ДВД-а"},
	{ORTH: "DVD-е", LEMMA: "DVD", NORM:"ДВД-е"},
	{ORTH: "DVD-и", LEMMA: "DVD", NORM:"ДВД-и"},
	{ORTH: "DVD-има", LEMMA: "DVD", NORM:"ДВД-има"},
	{ORTH: "DVD-ја", LEMMA: "DVD", NORM:"ДВД-ја"},
	{ORTH: "DVD-ја", LEMMA: "DVD", NORM:"ДВД-ја"},
	{ORTH: "DVD-је", LEMMA: "DVD", NORM:"ДВД-је"},
	{ORTH: "DVD-јем", LEMMA: "DVD", NORM:"ДВД-јем"},
	{ORTH: "DVD-ји", LEMMA: "DVD", NORM:"ДВД-ји"},
	{ORTH: "DVD-јима", LEMMA: "DVD", NORM:"ДВД-јима"},
	{ORTH: "DVD-ју", LEMMA: "DVD", NORM:"ДВД-ју"},
	{ORTH: "DVD-ом", LEMMA: "DVD", NORM:"ДВД-ом"},
	{ORTH: "DVD-у", LEMMA: "DVD", NORM:"ДВД-у"},
	{ORTH: "DW-а", LEMMA: "DW", NORM:"ДВ-а"},
	{ORTH: "DW-ом", LEMMA: "DW", NORM:"ДВ-ом"},
	{ORTH: "DW-у", LEMMA: "DW", NORM:"ДВ-у"},
	{ORTH: "EAR-а", LEMMA: "EAR", NORM:"ЕАР-а"},
	{ORTH: "EAR-ом", LEMMA: "EAR", NORM:"ЕАР-ом"},
	{ORTH: "EAR-у", LEMMA: "EAR", NORM:"ЕАР-у"},
	{ORTH: "EASO-а", LEMMA: "EASO", NORM:"ЕАСО-а"},
	{ORTH: "EASO-ом", LEMMA: "EASO", NORM:"ЕАСО-ом"},
	{ORTH: "EASO-у", LEMMA: "EASO", NORM:"ЕАСО-у"},
	{ORTH: "EBRD-а", LEMMA: "EBRD", NORM:"ЕБРД-а"},
	{ORTH: "EBRD-ом", LEMMA: "EBRD", NORM:"ЕБРД-ом"},
	{ORTH: "EBRD-у", LEMMA: "EBRD", NORM:"ЕБРД-у"},
	{ORTH: "EBU-а", LEMMA: "EBU", NORM:"ЕБУ-а"},
	{ORTH: "EBU-ом", LEMMA: "EBU", NORM:"ЕБУ-ом"},
	{ORTH: "EBU-у", LEMMA: "EBU", NORM:"ЕБУ-у"},
	{ORTH: "ECB-а", LEMMA: "ECB", NORM:"ЕЦБ-а"},
	{ORTH: "ECB-ом", LEMMA: "ECB", NORM:"ЕЦБ-ом"},
	{ORTH: "ECB-у", LEMMA: "ECB", NORM:"ЕЦБ-у"},
	{ORTH: "ECDC-а", LEMMA: "ECDC", NORM:"ЕЦДЦ-а"},
	{ORTH: "ECDC-ом", LEMMA: "ECDC", NORM:"ЕЦДЦ-ом"},
	{ORTH: "ECDC-у", LEMMA: "ECDC", NORM:"ЕЦДЦ-у"},
	{ORTH: "ECHR-а", LEMMA: "ECHR", NORM:"ЕЦХР-а"},
	{ORTH: "ECHR-ом", LEMMA: "ECHR", NORM:"ЕЦХР-ом"},
	{ORTH: "ECHR-у", LEMMA: "ECHR", NORM:"ЕЦХР-у"},
	{ORTH: "ECJ-а", LEMMA: "ECJ", NORM:"ЕЦЈ-а"},
	{ORTH: "ECJ-ом", LEMMA: "ECJ", NORM:"ЕЦЈ-ом"},
	{ORTH: "ECJ-у", LEMMA: "ECJ", NORM:"ЕЦЈ-у"},
	{ORTH: "ECOSOC-а", LEMMA: "ECOSOC", NORM:"ЕЦОСОЦ-а"},
	{ORTH: "ECOSOC-ом", LEMMA: "ECOSOC", NORM:"ЕЦОСОЦ-ом"},
	{ORTH: "ECOSOC-у", LEMMA: "ECOSOC", NORM:"ЕЦОСОЦ-у"},
	{ORTH: "ECPD-а", LEMMA: "ECPD", NORM:"ЕЦПД-а"},
	{ORTH: "ECPD-ом", LEMMA: "ECPD", NORM:"ЕЦПД-ом"},
	{ORTH: "ECPD-у", LEMMA: "ECPD", NORM:"ЕЦПД-у"},
	{ORTH: "EEAS-а", LEMMA: "EEAS", NORM:"ЕЕАС-а"},
	{ORTH: "EEAS-ом", LEMMA: "EEAS", NORM:"ЕЕАС-ом"},
	{ORTH: "EEAS-у", LEMMA: "EEAS", NORM:"ЕЕАС-у"},
	{ORTH: "EFA-е", LEMMA: "EFA", NORM:"ЕФА-е"},
	{ORTH: "EFA-е", LEMMA: "EFA", NORM:"ЕФА-е"},
	{ORTH: "EFA-е", LEMMA: "EFA", NORM:"ЕФА-е"},
	{ORTH: "EFA-и", LEMMA: "EFA", NORM:"ЕФА-и"},
	{ORTH: "EFA-и", LEMMA: "EFA", NORM:"ЕФА-и"},
	{ORTH: "EFA-и", LEMMA: "EFA", NORM:"ЕФА-и"},
	{ORTH: "EFA-ом", LEMMA: "EFA", NORM:"ЕФА-ом"},
	{ORTH: "EFA-ом", LEMMA: "EFA", NORM:"ЕФА-ом"},
	{ORTH: "EFA-ом", LEMMA: "EFA", NORM:"ЕФА-ом"},
	{ORTH: "EFA-у", LEMMA: "EFA", NORM:"ЕФА-у"},
	{ORTH: "EFA-у", LEMMA: "EFA", NORM:"ЕФА-у"},
	{ORTH: "EFA-у", LEMMA: "EFA", NORM:"ЕФА-у"},
	{ORTH: "EFI-ја", LEMMA: "EFI", NORM:"ЕФИ-ја"},
	{ORTH: "EFI-јем", LEMMA: "EFI", NORM:"ЕФИ-јем"},
	{ORTH: "EFI-ју", LEMMA: "EFI", NORM:"ЕФИ-ју"},
	{ORTH: "EFSA-е", LEMMA: "EFSA", NORM:"ЕФСА-е"},
	{ORTH: "EFSA-и", LEMMA: "EFSA", NORM:"ЕФСА-и"},
	{ORTH: "EFSA-ом", LEMMA: "EFSA", NORM:"ЕФСА-ом"},
	{ORTH: "EFSA-у", LEMMA: "EFSA", NORM:"ЕФСА-у"},
	{ORTH: "EFSF-а", LEMMA: "EFSF", NORM:"ЕФСФ-а"},
	{ORTH: "EFSF-ом", LEMMA: "EFSF", NORM:"ЕФСФ-ом"},
	{ORTH: "EFSF-у", LEMMA: "EFSF", NORM:"ЕФСФ-у"},
	{ORTH: "EFTA-е", LEMMA: "EFTA", NORM:"ЕФТА-е"},
	{ORTH: "EFTA-и", LEMMA: "EFTA", NORM:"ЕФТА-и"},
	{ORTH: "EFTA-ом", LEMMA: "EFTA", NORM:"ЕФТА-ом"},
	{ORTH: "EFTA-у", LEMMA: "EFTA", NORM:"ЕФТА-у"},
	{ORTH: "EHF-а", LEMMA: "EHF", NORM:"ЕХФ-а"},
	{ORTH: "EHF-ом", LEMMA: "EHF", NORM:"ЕХФ-ом"},
	{ORTH: "EHF-у", LEMMA: "EHF", NORM:"ЕХФ-у"},
	{ORTH: "EIB-а", LEMMA: "EIB", NORM:"ЕИБ-а"},
	{ORTH: "EIB-ом", LEMMA: "EIB", NORM:"ЕИБ-ом"},
	{ORTH: "EIB-у", LEMMA: "EIB", NORM:"ЕИБ-у"},
	{ORTH: "EIF-а", LEMMA: "EIF", NORM:"ЕИФ-а"},
	{ORTH: "EIF-ом", LEMMA: "EIF", NORM:"ЕИФ-ом"},
	{ORTH: "EIF-у", LEMMA: "EIF", NORM:"ЕИФ-у"},
	{ORTH: "EIPA-е", LEMMA: "EIPA", NORM:"ЕИПА-е"},
	{ORTH: "EIPA-и", LEMMA: "EIPA", NORM:"ЕИПА-и"},
	{ORTH: "EIPA-ом", LEMMA: "EIPA", NORM:"ЕИПА-ом"},
	{ORTH: "EIPA-у", LEMMA: "EIPA", NORM:"ЕИПА-у"},
	{ORTH: "EJTN-а", LEMMA: "EJTN", NORM:"ЕЈТН-а"},
	{ORTH: "EJTN-ом", LEMMA: "EJTN", NORM:"ЕЈТН-ом"},
	{ORTH: "EJTN-у", LEMMA: "EJTN", NORM:"ЕЈТН-у"},
	{ORTH: "ELSA-е", LEMMA: "ELSA", NORM:"ЕЛСА-е"},
	{ORTH: "ELSA-и", LEMMA: "ELSA", NORM:"ЕЛСА-и"},
	{ORTH: "ELSA-ом", LEMMA: "ELSA", NORM:"ЕЛСА-ом"},
	{ORTH: "ELSA-у", LEMMA: "ELSA", NORM:"ЕЛСА-у"},
	{ORTH: "EMS-а", LEMMA: "EMS", NORM:"ЕМС-а"},
	{ORTH: "EMS-ом", LEMMA: "EMS", NORM:"ЕМС-ом"},
	{ORTH: "EMS-у", LEMMA: "EMS", NORM:"ЕМС-у"},
	{ORTH: "ENISA-е", LEMMA: "ENISA", NORM:"ЕНИСА-е"},
	{ORTH: "ENISA-и", LEMMA: "ENISA", NORM:"ЕНИСА-и"},
	{ORTH: "ENISA-ом", LEMMA: "ENISA", NORM:"ЕНИСА-ом"},
	{ORTH: "ENISA-у", LEMMA: "ENISA", NORM:"ЕНИСА-у"},
	{ORTH: "ESA-е", LEMMA: "ESA", NORM:"ЕСА-е"},
	{ORTH: "ESA-и", LEMMA: "ESA", NORM:"ЕСА-и"},
	{ORTH: "ESA-ом", LEMMA: "ESA", NORM:"ЕСА-ом"},
	{ORTH: "ESA-у", LEMMA: "ESA", NORM:"ЕСА-у"},
	{ORTH: "ESC-а", LEMMA: "ESC", NORM:"ЕСЦ-а"},
	{ORTH: "ESC-ом", LEMMA: "ESC", NORM:"ЕСЦ-ом"},
	{ORTH: "ESC-у", LEMMA: "ESC", NORM:"ЕСЦ-у"},
	{ORTH: "ESDP-а", LEMMA: "ESDP", NORM:"ЕСДП-а"},
	{ORTH: "ESDP-ом", LEMMA: "ESDP", NORM:"ЕСДП-ом"},
	{ORTH: "ESDP-у", LEMMA: "ESDP", NORM:"ЕСДП-у"},
	{ORTH: "ESM-а", LEMMA: "ESM", NORM:"ЕСМ-а"},
	{ORTH: "ESM-ом", LEMMA: "ESM", NORM:"ЕСМ-ом"},
	{ORTH: "ESM-у", LEMMA: "ESM", NORM:"ЕСМ-у"},
	{ORTH: "ESP-а", LEMMA: "ESP", NORM:"ЕСП-а"},
	{ORTH: "ESP-ом", LEMMA: "ESP", NORM:"ЕСП-ом"},
	{ORTH: "ESP-у", LEMMA: "ESP", NORM:"ЕСП-у"},
	{ORTH: "ETA-е", LEMMA: "ETA", NORM:"ЕТА-е"},
	{ORTH: "ETA-и", LEMMA: "ETA", NORM:"ЕТА-и"},
	{ORTH: "ETA-ом", LEMMA: "ETA", NORM:"ЕТА-ом"},
	{ORTH: "ETA-у", LEMMA: "ETA", NORM:"ЕТА-у"},
	{ORTH: "ETF-а", LEMMA: "ETF", NORM:"ЕТФ-а"},
	{ORTH: "ETF-ом", LEMMA: "ETF", NORM:"ЕТФ-ом"},
	{ORTH: "ETF-у", LEMMA: "ETF", NORM:"ЕТФ-у"},
	{ORTH: "EUMETSAT-а", LEMMA: "EUMETSAT", NORM:"ЕУМЕТСАТ-а"},
	{ORTH: "EUMETSAT-ом", LEMMA: "EUMETSAT", NORM:"ЕУМЕТСАТ-ом"},
	{ORTH: "EUMETSAT-у", LEMMA: "EUMETSAT", NORM:"ЕУМЕТСАТ-у"},
	{ORTH: "EURAMET-а", LEMMA: "EURAMET", NORM:"ЕУРАМЕТ-а"},
	{ORTH: "EURAMET-ом", LEMMA: "EURAMET", NORM:"ЕУРАМЕТ-ом"},
	{ORTH: "EURAMET-у", LEMMA: "EURAMET", NORM:"ЕУРАМЕТ-у"},
	{ORTH: "EUROCONTROL-а", LEMMA: "EUROCONTROL", NORM:"ЕУРОЦОНТРОЛ-а"},
	{ORTH: "EUROCONTROL-ом", LEMMA: "EUROCONTROL", NORM:"ЕУРОЦОНТРОЛ-ом"},
	{ORTH: "EUROCONTROL-у", LEMMA: "EUROCONTROL", NORM:"ЕУРОЦОНТРОЛ-у"},
	{ORTH: "EUROSAI-ја", LEMMA: "EUROSAI", NORM:"ЕУРОСАИ-ја"},
	{ORTH: "EUROSAI-јем", LEMMA: "EUROSAI", NORM:"ЕУРОСАИ-јем"},
	{ORTH: "EUROSAI-ју", LEMMA: "EUROSAI", NORM:"ЕУРОСАИ-ју"},
	{ORTH: "EVS-а", LEMMA: "EVS", NORM:"ЕВС-а"},
	{ORTH: "EVS-ом", LEMMA: "EVS", NORM:"ЕВС-ом"},
	{ORTH: "EVS-у", LEMMA: "EVS", NORM:"ЕВС-у"},
	{ORTH: "FIAT-а", LEMMA: "FIAT", NORM:"ФИАТ-а"},
	{ORTH: "FIAT-ом", LEMMA: "FIAT", NORM:"ФИАТ-ом"},
	{ORTH: "FIAT-у", LEMMA: "FIAT", NORM:"ФИАТ-у"},
	{ORTH: "FMIS-а", LEMMA: "FMIS", NORM:"ФМИС-а"},
	{ORTH: "FMIS-ом", LEMMA: "FMIS", NORM:"ФМИС-ом"},
	{ORTH: "FMIS-у", LEMMA: "FMIS", NORM:"ФМИС-у"},
	{ORTH: "FRONTEX-а", LEMMA: "FRONTEX", NORM:"ФРОНТЕКС-а"},
	{ORTH: "FRONTEX-ом", LEMMA: "FRONTEX", NORM:"ФРОНТЕКС-ом"},
	{ORTH: "FRONTEX-у", LEMMA: "FRONTEX", NORM:"ФРОНТЕКС-у"},
	{ORTH: "GEF-а", LEMMA: "GEF", NORM:"ГЕФ-а"},
	{ORTH: "GEF-ом", LEMMA: "GEF", NORM:"ГЕФ-ом"},
	{ORTH: "GEF-у", LEMMA: "GEF", NORM:"ГЕФ-у"},
	{ORTH: "GRECO-а", LEMMA: "GRECO", NORM:"ГРЕЦО-а"},
	{ORTH: "GRECO-ом", LEMMA: "GRECO", NORM:"ГРЕЦО-ом"},
	{ORTH: "GRECO-у", LEMMA: "GRECO", NORM:"ГРЕЦО-у"},
	{ORTH: "GSM-а", LEMMA: "GSM", NORM:"ГСМ-а"},
	{ORTH: "GSM-ом", LEMMA: "GSM", NORM:"ГСМ-ом"},
	{ORTH: "GSM-у", LEMMA: "GSM", NORM:"ГСМ-у"},
	{ORTH: "HIV-а", LEMMA: "HIV", NORM:"ХИВ-а"},
	{ORTH: "HIV-ом", LEMMA: "HIV", NORM:"ХИВ-ом"},
	{ORTH: "HIV-у", LEMMA: "HIV", NORM:"ХИВ-у"},
	{ORTH: "IBM-а", LEMMA: "IBM", NORM:"ИБМ-а"},
	{ORTH: "IBM-ом", LEMMA: "IBM", NORM:"ИБМ-ом"},
	{ORTH: "IBM-у", LEMMA: "IBM", NORM:"ИБМ-у"},
	{ORTH: "ICBC-а", LEMMA: "ICBC", NORM:"ИЦБЦ-а"},
	{ORTH: "ICBC-ом", LEMMA: "ICBC", NORM:"ИЦБЦ-ом"},
	{ORTH: "ICBC-у", LEMMA: "ICBC", NORM:"ИЦБЦ-у"},
	{ORTH: "ICT-а", LEMMA: "ICT", NORM:"ИЦТ-а"},
	{ORTH: "ICT-ом", LEMMA: "ICT", NORM:"ИЦТ-ом"},
	{ORTH: "ICT-у", LEMMA: "ICT", NORM:"ИЦТ-у"},
	{ORTH: "IEP-а", LEMMA: "IEP", NORM:"ИЕП-а"},
	{ORTH: "IEP-ом", LEMMA: "IEP", NORM:"ИЕП-ом"},
	{ORTH: "IEP-у", LEMMA: "IEP", NORM:"ИЕП-у"},
	{ORTH: "IMS-а", LEMMA: "IMS", NORM:"ИМС-а"},
	{ORTH: "IMS-ом", LEMMA: "IMS", NORM:"ИМС-ом"},
	{ORTH: "IMS-у", LEMMA: "IMS", NORM:"ИМС-у"},
	{ORTH: "IPAP-а", LEMMA: "IPAP", NORM:"ИПАП-а"},
	{ORTH: "IPAP-ом", LEMMA: "IPAP", NORM:"ИПАП-ом"},
	{ORTH: "IPAP-у", LEMMA: "IPAP", NORM:"ИПАП-у"},
	{ORTH: "IPARD-а", LEMMA: "IPARD", NORM:"ИПАРД-а"},
	{ORTH: "IPARD-ом", LEMMA: "IPARD", NORM:"ИПАРД-ом"},
	{ORTH: "IPARD-у", LEMMA: "IPARD", NORM:"ИПАРД-у"},
	{ORTH: "IRA-е", LEMMA: "IRA", NORM:"ИРА-е"},
	{ORTH: "IRA-и", LEMMA: "IRA", NORM:"ИРА-и"},
	{ORTH: "IRA-ом", LEMMA: "IRA", NORM:"ИРА-ом"},
	{ORTH: "IRA-у", LEMMA: "IRA", NORM:"ИРА-у"},
	{ORTH: "ISDACON-а", LEMMA: "ISDACON", NORM:"ИСДАЦОН-а"},
	{ORTH: "ISDACON-ом", LEMMA: "ISDACON", NORM:"ИСДАЦОН-ом"},
	{ORTH: "ISDACON-у", LEMMA: "ISDACON", NORM:"ИСДАЦОН-у"},
	{ORTH: "JICA-е", LEMMA: "JICA", NORM:"ЈИЦА-е"},
	{ORTH: "JICA-и", LEMMA: "JICA", NORM:"ЈИЦА-и"},
	{ORTH: "JICA-ом", LEMMA: "JICA", NORM:"ЈИЦА-ом"},
	{ORTH: "JICA-у", LEMMA: "JICA", NORM:"ЈИЦА-у"},
	{ORTH: "LEADER-а", LEMMA: "LEADER", NORM:"ЛЕАДЕР-а"},
	{ORTH: "LEADER-ом", LEMMA: "LEADER", NORM:"ЛЕАДЕР-ом"},
	{ORTH: "LEADER-у", LEMMA: "LEADER", NORM:"ЛЕАДЕР-у"},
	{ORTH: "MERS-а", LEMMA: "MERS", NORM:"МЕРС-а"},
	{ORTH: "MERS-ом", LEMMA: "MERS", NORM:"МЕРС-ом"},
	{ORTH: "MERS-у", LEMMA: "MERS", NORM:"МЕРС-у"},
	{ORTH: "OLAF-а", LEMMA: "OLAF", NORM:"ОЛАФ-а"},
	{ORTH: "OLAF-ом", LEMMA: "OLAF", NORM:"ОЛАФ-ом"},
	{ORTH: "OLAF-у", LEMMA: "OLAF", NORM:"ОЛАФ-у"},
	{ORTH: "RAI-ја", LEMMA: "RAI", NORM:"РАИ-ја"},
	{ORTH: "RAI-јем", LEMMA: "RAI", NORM:"РАИ-јем"},
	{ORTH: "RAI-ју", LEMMA: "RAI", NORM:"РАИ-ју"},
	{ORTH: "SECO-а", LEMMA: "SECO", NORM:"СЕЦО-а"},
	{ORTH: "SECO-ом", LEMMA: "SECO", NORM:"СЕЦО-ом"},
	{ORTH: "SECO-у", LEMMA: "SECO", NORM:"СЕЦО-у"},
	{ORTH: "SILC-а", LEMMA: "SILC", NORM:"СИЛЦ-а"},
	{ORTH: "SILC-ом", LEMMA: "SILC", NORM:"СИЛЦ-ом"},
	{ORTH: "SILC-у", LEMMA: "SILC", NORM:"СИЛЦ-у"},
	{ORTH: "UNAIDS-а", LEMMA: "UNAIDS", NORM:"УНАИДС-а"},
	{ORTH: "UNAIDS-ом", LEMMA: "UNAIDS", NORM:"УНАИДС-ом"},
	{ORTH: "UNAIDS-у", LEMMA: "UNAIDS", NORM:"УНАИДС-у"},
	{ORTH: "UNECE-а", LEMMA: "UNECE", NORM:"УНЕЦЕ-а"},
	{ORTH: "UNECE-ом", LEMMA: "UNECE", NORM:"УНЕЦЕ-ом"},
	{ORTH: "UNECE-у", LEMMA: "UNECE", NORM:"УНЕЦЕ-у"},
	{ORTH: "UNHCR-а", LEMMA: "UNHCR", NORM:"УНХЦР-а"},
	{ORTH: "UNHCR-ом", LEMMA: "UNHCR", NORM:"УНХЦР-ом"},
	{ORTH: "UNHCR-у", LEMMA: "UNHCR", NORM:"УНХЦР-у"},
	{ORTH: "UNICEF-а", LEMMA: "UNICEF", NORM:"УНИЦЕФ-а"},
	{ORTH: "UNICEF-ом", LEMMA: "UNICEF", NORM:"УНИЦЕФ-ом"},
	{ORTH: "UNICEF-у", LEMMA: "UNICEF", NORM:"УНИЦЕФ-у"},
	{ORTH: "UNPROFOR-а", LEMMA: "UNPROFOR", NORM:"УНПРОФОР-а"},
	{ORTH: "UNPROFOR-ом", LEMMA: "UNPROFOR", NORM:"УНПРОФОР-ом"},
	{ORTH: "UNPROFOR-у", LEMMA: "UNPROFOR", NORM:"УНПРОФОР-у"},
	{ORTH: "URI-ја", LEMMA: "URI", NORM:"УРИ-ја"},
	{ORTH: "URI-јем", LEMMA: "URI", NORM:"УРИ-јем"},
	{ORTH: "URI-ју", LEMMA: "URI", NORM:"УРИ-ју"},
	{ORTH: "URL-а", LEMMA: "URL", NORM:"УРЛ-а"},
	{ORTH: "URL-ом", LEMMA: "URL", NORM:"УРЛ-ом"},
	{ORTH: "URL-у", LEMMA: "URL", NORM:"УРЛ-у"},
	{ORTH: "USAID-а", LEMMA: "USAID", NORM:"УСАИД-а"},
	{ORTH: "USAID-ом", LEMMA: "USAID", NORM:"УСАИД-ом"},
	{ORTH: "USAID-у", LEMMA: "USAID", NORM:"УСАИД-у"},
	{ORTH: "VJ-а", LEMMA: "VJ", NORM:"ВЈ-а"},
	{ORTH: "VJ-ева", LEMMA: "VJ", NORM:"ВЈ-ева"},
	{ORTH: "VJ-еве", LEMMA: "VJ", NORM:"ВЈ-еве"},
	{ORTH: "VJ-еви", LEMMA: "VJ", NORM:"ВЈ-еви"},
	{ORTH: "VJ-евима", LEMMA: "VJ", NORM:"ВЈ-евима"},
	{ORTH: "VJ-ем", LEMMA: "VJ", NORM:"ВЈ-ем"},
	{ORTH: "VJ-у", LEMMA: "VJ", NORM:"ВЈ-у"},
	{ORTH: "ZDF-а", LEMMA: "ZDF", NORM:"ЗДФ-а"},
	{ORTH: "ZDF-ом", LEMMA: "ZDF", NORM:"ЗДФ-ом"},
	{ORTH: "ZDF-у", LEMMA: "ZDF", NORM:"ЗДФ-у"}
]:
    _exc[exc_data[ORTH]] = [exc_data]


# non-declinables with periods should go here (if we don't want to normalize them or anytrhing like that)
# vs. or wiss.
# just testing
for orth in [
    "сл.",
    "др."
]:
    _exc[orth] = [{ORTH: orth}]


TOKENIZER_EXCEPTIONS = _exc
